### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by mxsrc** [philc/vimium#1048]
Hi,

I´d like to use vimium with firefox. There are alternatives which I dont want to use since they dont work properly or have a design I dont like.
Would it be possible to port vimium to Firefox?

**Comment by darsain** [comment]
I'd also love to use this in Firefox.

Maybe you could look at [gorhill/uBlock](https://github.com/gorhill/uBlock), he managed to make an extension that builds to multiple platforms.

**Comment by willsALMANJ** [comment]
It might be worth revisiting this issue some time soon because Firefox is aiming for its new WebExtension API to be close to fully compatible with Chrome's.

In this [fork](https://github.com/willsALMANJ/vimium), I made a few small changes to `manifest.json` which allowed for Vimium to be installed in Firefox with minimal output to the Error Console. I tried it in the latest Firefox nightly build. It installs and its icon shows up but none of the keys work. I put the Error Console output I got in the `webextension_issues` directory of the fork. I also included the output of `web-ext lint`, but I can't find it documented what version of Firefox the linter corresponds to (it warns about some API's not being implemented like the `sessions` API even though [it was recently added to the alpha version of Firefox](https://blog.mozilla.org/addons/2016/11/18/webextensions-in-firefox-52/)).

I haven't had time to trace through the code and figure out why nothing works in Firefox.
