### ISSUE TITLE
Hope to support Chinese

### ISSUE THREAD

**Issue by zhanggang807** [philc/vimium#1072]
I am a chrome and vi fans from China, Actually I am a Java programmer, so I often use chrome to search information from the google. So, I hope this plugin can support Chinese.
Thank you share this powerful plugin. I like it very much.

**Comment by czzshr** [comment]
I am also a Chinese user, let me add some explanation for author, the problem is:
*Vimium do not support searching Chinese character.*

For example, I want to input "/中文" to search two Chinese character "中文", but I can't input "/中文"， what I get is "/zhongwen", the problem is: while searching, I couldn't input Chinese word using Chinese Input Method.

**Comment by rambo-panda** [comment]
+1

**Comment by czzshr** [comment]
Problem has been fixed, Thanks~!

Tested on OS X 10.11 Chrome.

**Comment by zhanggang807** [comment]
Very good. Thanks a lot !
