### ISSUE TITLE
option to try make link hint based on the link text

### ISSUE THREAD

**Issue by scien** [philc/vimium#1137]
sorry if this is a duplicate, i couldn't find any issue requesting it though...

link hints with numbers and searching by text is useful, but not quite what I want. It feels like an extra step to have to type and then go with the number.

it would be nice to have an option to just try and base the link hint off of the link text as best as possible. for example, if i'm on the github new issue page and press "f". it would be nice if the links at the top "issues", "pull requests", "labels", "milestones" were labeled "i", "p", "l", "m". 

your hand may have to move a little farther to get to the correct key, but it would be awesome to know 90% of the time what the link hint is going to be even before it pops up.

anybody have thoughts on this?

**Comment by raboof** [comment]
I would prefer more link hint predictability, too

**Comment by smblott-github** [comment]
Not answering directly, but...

In soon-to-be-released 1.52, filtered hints have been substantially improved.  Links are scored such that, if you type the text at the start of the link, then you nearly always select the right link after just a few characters.  If not, `Tab` now takes you to the next link.

This can be substantially faster because it eliminates the cognitive step of looking to see what hint has been assigned.

**Comment by smblott-github** [comment]
Closing.
We don't know how to do this in the general case.
