### ISSUE TITLE
Add support for external editor

### ISSUE THREAD

**Issue by agzam** [philc/vimium#1310]
Would be awesome to be able to edit text in in vim. Vrome does that (cVim does that too). I like Vimium better and only that thing keeps me on Vrome. How difficult would be to implement something like that?

**Comment by dragon788** [comment]
Agzam, are you on Windows/Mac/Linux? I can suggest some helpful alternatives depending on your platform.

Windows I use TextEditorAnywhere + NotepadReplacer + gVim to allow me to Win+A in any text field on the system and use gVim to edit the text. I absolutely love this, and there is a portable version of TEA if you are restricted from installing software, and it can reference the portable version of gVim as well (with just a bit of setup).

On Mac since they killed off the ability to use QuickCursor (and the developers didn't have the energy to workaround sandbox mode) you can use an Alfred or Automator workflow to take a shortcut and automatically Cmd+A, Cmd+C, open MacVim with a known /tmp/file, insert Cmd+V, allow you to edit, and then when you save and quit it can use that temp file to populate the field by using cat /tmp/file > pbcopy or something similar. Making a completely open source solution would be awesome, but my poor Macbook Air barely lets me browse the web, let alone do any serious development (plus I work in Windows and Linux all day every day, so Mac is a distant 3rd place on my priority list).

On Linux there are a couple scripts that combine xsel and xkeyboard events and xdotool to basically go through the motions the same as on Mac above.

On a Chromebook, well, that's where we need to be able to trigger the gVim Chrome app or embed a copy in Vimium somehow, but reinventing the wheel probably isn't the best wayt o go about it.

**Comment by BohrShaw** [comment]
+1 to feature!

> This would be great to have. In the meantime, you can always use TextAid.

But it seems the client is not open-source.

**Comment by smblott-github** [comment]
> But it seems the TextAid client is not open-source.

Or try this... https://github.com/smblott-github/text-aid-too

(I wrote this to have a text-aid like editor that works in GMail and the like.)

**Comment by BohrShaw** [comment]
Thanks! @smblott-github It works well.

But I notice the editor can't be set to `gvim --remote ...` which I think it exits too early. This is a pity because vanilla `gvim` would take a second to lauch on my machine(Ubuntu Trusty).

Maybe this is due to more limitations in Chrome than in Firefox.

**Comment by smblott-github** [comment]
@BohrShaw.  The editor has to block until it's done, otherwise we don't know when to tidy up.

(This is off-topic for Vimium; suggest move [here](https://github.com/smblott-github/text-aid-too/issues) if you want to continue discussion.)
