### ISSUE TITLE
Custom search engines should not require a colon

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1398]
A custom search engine is defined with:

    w: http://www.wikipedia.org/w/index.php?title=Special:Search&search=%s

Why is that colon needed?  Could it not just be:

    w http://www.wikipedia.org/w/index.php?title=Special:Search&search=%s

Moreover, it would be simple enough to support both formats.

Edit: Or migrate legacy definitions.

**Comment by gdh1995** [comment]
In my opinion, to define a search engine, we should use NOT a white-space BUT a more obvious symbol. Because of this, I also don't like the implement of declaring a description.
Say there is a search engine which means to execute given javascript code. Then if we write:
> `js: javascript: alert("Hello, value = %s"); JavaScript` // the last "JavaScript" is its description
Then, the current version will generate a search engine:
> `{js: {url: "javascript: alert(\"Hello,", description: "value = %s\"); JavaScript"}}`
An ugly example, but persuasive, isn't is?

I have made a crack of this. In my vim, it is
`js=JavaScript code: javascript: alert("Hello, value = %s");`
In this declaration, the first ":" is used to split a key(with a title, maybe) and a url, and the first "=" to split key and title.
<key> [=title] : <url>
* key.indexOf(":") == -1 && key.indexOf("=") == -1;
* title.indexOf(":")  == -1; (title.indexOf("=") may be any value)
* url can have any character, including ":" and "="

**Comment by smblott-github** [comment]
Regarding overloading search engines for the execution of arbitrary JS and syntax, there's a long discussion in #1169.

> js=JavaScript: javascript: alert("Hello, value = %s");

It's not going to look very nice once we URLencode the argument!  From my perspective, the feature is custom search engines.  If we want a hook to run arbitrary JS, then we should build one, not overload an existing feature.

Also relevant: #1392.

**Comment by gdh1995** [comment]
Yes, you're right. JavaScript is a problem much harder than what I thought.
However, I insist that we still need an obvious mark to split those options including key, url, description, and something others - if more options are added in the future, can we use white space to split ALL things?

**Comment by mrmr1993** [comment]
> if more options are added in the future, can we use white space to split ALL things?

What kind of other options would we want? Also, this causes issues since you can have spaces in the description.

**Comment by gdh1995** [comment]
I'm sorry. I wrote the last sentence "can we use ..." to say "we can not split all things with spaces" but it did not express it successfully.
I changed my mind: if more things needed, we can allow a escape char like "\ ".
BTW, maybe I can add a "favIconUrl" option.
