### ISSUE TITLE
Characters used for link hints - mix left and right hands

### ISSUE THREAD

**Issue by glittle** [philc/vimium#1421]
It would be nice if the "Characters used for link hints" could be set up to make combined keystrokes use keys from each hand, or at least different fingers.  So, avoid "VF" since they would use the same finger. Better would be "VJ" since that uses both hands.

This would, of course, have to be a personal preference, and most helpful to people touch-typing. 

Maybe there could be two input boxes to enter "characters used for link hints", and the shortcuts could alternate keys between the two. So, in one box I'd put "ASDF" and in the other "JKL" and the shortcuts using two or more characters would alternate between them, so I'd get "AJ", "AJS", etc, but not "AS".

**Comment by gdh1995** [comment]
Um, I don't like shortcuts like "VJ", because it need me to place tow hands on my keyboard. My favorite way is use "asdqwerzxcv" for hints , and then I can do most things with just one hand.
---- My right hand is used for grabing a mouse, food, drink, or somthing more interesting.

**Comment by z0rch** [comment]
This is an interesting idea, but I'm afraid most people just don't care, thus the priority would not be that high to see this any time soon (unless you send a PR :smile:).

In regards of implementation details, I would find 2 input boxes rather confusing (but may be easier to implement).

Assuming we can resolve from the code, which key is on the left or on the right side of a keyboard, let me throw in another idea of having just a single radio button: "Prefer single hand: [left], [right], [no]".

"Left" or "Right" would result in generating link hints for one hand, like `SD` or `JK`. "No" would result in the behavior, proposed by @glittle, to use both hands -- like `DJ`. 

Let "No" be the default option, since it is closer to what we have right now.

**Comment by terraqout** [comment]
I've implemented such stuff one time.
We don't need checkbox, because if you have compact line of keyboard symbols like "asdqwerzxcv" algorithm would create more comfortable ones as ad,ae,ac and only in the end the most uncomfortable aa,aq,az. So it means that perfect algorithm would prefer:
1. "one hand" length between symbols
2. keys of middle stroke a-l, and then low one: z-m, and after top - q-p

BUT two symbols link hint is non default, so who really cares about it?

**Comment by akfish** [comment]
Hmm. I was hoping for an exact opposite feature. See #1455
Not trying to be a troll or something. But sometimes you really need to hold food with one hand. That leaves you only the other hand on the keyboard and you don't want the keys to be that far a part.

Though I agree with your reasoning too. When you are not eating, pressing adjacent keys are not comfortable, especially on some narrow keyboards. And your feature request promotes a healthier life style by preventing users from eating in front of a computer. 

I guess to accommodate this, maybe a concept called "key mapping strategy" could be extracted and implemented. User can choose whatever strategy he/she/it wants.

**Comment by dragon788** [comment]
I think the current behavior of letting you define the letters used for link hints is great, though I've found I like enabling the number mode so I can type the text of links to select them, but I'll regularly waffle back and forth.

I think overall the behavior of custom characters for link hints is the way to go, but like someone said, maybe have a couple quick toggles that let you pick "handedness" so you could change which hand you prefer to input the hints with and it selects many/most of the characters reachable by that hand.

**Comment by gdh1995** [comment]
Since Vimium has supported commands with options, we may add a short key to set the page's `linkHintCharacters` to `options.***`, and in the second time to reset characters to the global one.

**Comment by smblott-github** [comment]
Closing.
Lack of interest.
