### ISSUE TITLE
another way to show a search engine

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1429]
It's a good change that a search engine is allowed to have a title ("description", in coffee code) in PR 1407. But I have some different ideas:
1. Commit 094753c "delay recognising query as search-engine query", after which I could not recognize "wiki" as a search engine keyword again UNLESS I type a space and then another char. I believe this change is inconvenient to those forgetful like me, or who have many search engines.
2. It may be better to display its description in the title, not type.

I'm using a vimium customized by myself. This is my vomnibar for information:
![vomni_snap](https://cloud.githubusercontent.com/assets/5547703/5725415/8f954978-9b8d-11e4-851c-d52a1dd611ee.png)

**Comment by smblott-github** [comment]
> after which I could not recognize "wiki" as a search engine keyword again UNLESS I type a space and then another char

Yes.  that was a decision (not necessarily a good one, but a decision nevertheless).

Say the shortcut is `w`.  Then we could activate after:
1. `w`
2. `w<Space>`
3. `w<Space>X`

1. is the old behaviour.  It feels really odd in many use cases, and it's not what Chrome does.
2. would be ideal.  It *is* what Chrome does.  However, it might require either an ugly hack or considerable internal re-plumbing.  I might take another look at it.
3. is what we do now.  It's reasonable because it's the first point at which we actually have a query to send.

> It may be better to display its description in the title, not type.

Yes, maybe.  That's what Chrome does.  Fancy taking a crack at it?  It would have to be consistent with the rest of the vomnibar UX.

**Comment by gdh1995** [comment]
What you said are better.
In fact, I adjusted most CSS styles of Vomnibar, and made text of types aligned to both ends, which requires "type" can only be some specialized words, such as ["history", "bookm", "search"] (width of "type" text depends on its font-family). That's why I don't want any search engine description to be a type.
