### ISSUE TITLE
Requirements for visual mode...

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1435]
Visual mode is a significant goal for the next release.  What are the requirements?

Assumption:

- There is an initial (non-`None`) selection.  Possibly established via "find" or the mouse.

Use cases:

- Select some text to copy into a document or text area.
- Select some text to send to a search engine.
- Select a URL or email address which is not a link.
- Others?

Some starters for ten:

- As many basic character, word, line and paragraph movement commands as we can achieve.
- The `o` command (switch focus/node).  This is super important.
- `v`/character mode, `V`/line mode.  Possibly switch between the two while visual mode is active.
- Leaving visual mode:
  - `Escape`: leave and do nothing.
  - `y`: yank.
  - `p`: send the selection to the default search engine (unless it looks like a URL, in which case, visit it).
  - `P`: same, but in a new tab.  Similarly `Ctrl-Shift-p`, for new window.
- Optionally, constrained to working within a given `isEditable` element (so that we can reuse the mode within any future edit mode).

Questions:

- Customisable key mappings?  My sense is no.  I'll justify that if asked.
- What do we do if the selection in `None`?  Do we require there to be an initial selection?
- What happens if the user clicks while visual mode is active?  Suggest bail (the user knows best).

Please post ideas.

**Comment by z0rch** [comment]
> What do we do if the selection in None? Do we require there to be an initial selection?

I'm inspired by the way cVim solved this problem. 

* Pressing `v` for the first time moves you into a `caret mode`, where a caret appears at the top of the screen. 
* You can use basic navigation keys (arrows, `hjkl`, `w`, `e`, etc.) to move around (move the caret). 
* When you are ready to start selection, you hit `v` again, and now you are in `visual mode`. 
* Now you can use the same navigation keys to expand the selection. 
* After you are done, do what you want: `y` to copy, `p` to search, etc.

Sounds interesting?

**Comment by smblott-github** [comment]
> Sounds interesting?

Yes.

> a caret appears at the top of the screen...

What is the definition of the "top of the screen"?

**Comment by z0rch** [comment]
The caret appears right before the first visible letter on the page.

I'm going to play more with cVim, and then come back and give a more detailed review on you proposal.

**Comment by z0rch** [comment]
I agree with @smblott-github's proposal. This is the only part I don't really understand:

> Optionally, constrained to working within a given isEditable element (so that we can reuse the mode within any future edit mode).

Could you please explain it a bit?

------------------------------

Here is what I think about placing the initial selection:

* Use `/` to make an initial selection, hit `v` to select current match and enter `visual mode`.
* Use mouse to make an initial selection, hit `v` to enter `visual mode`.
* `Caret mode` (inspired by cVim):
  * Hit `v` to enter `caret mode`. It will place a caret before the first visible letter on a page.
  * Move cursor with the same movement commands, that we will implement for `visual mode`.
  * Hit `v` to enter `visual mode`, caret position will indicate the starting point of the selection.
* `EasyMotion mode` ([inspired by the awesome vim plugin](https://github.com/Lokaltog/vim-easymotion)):
  * I took the liberty of putting their gif animation below, and here is how it works:
  * Hit `v` (`\s` is used in the animation) to enter `EasyMotion` state.
  * Vimium asks you the first letter of a word, where you want to start selection.
  * Suppose you want to select `s:flag`, so hit `s`.
  * All occurrences of an `s` are highlighted with different letters now. The `s` that you need is highlighted as `fk`, so press `fk` and you enter visual mode, started at the letter `s`.

![EasyMotion](https://camo.githubusercontent.com/d5f800b9602faaeccc2738c302776a8a11797a0e/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333739373036322f323033393335392f61386539333864362d383939662d313165332d383738392d3630303235656138333635362e676966)

If you have never experienced `EasyMotion` on vim (or `ace-jump` on Emacs), the last idea may sound complicated and awful. In that case, I urge you to try this plugin in vim!

It allows you to reach absolutely any point on the screen with just 3-4 keypresses. That is my personal favorite.

Due to this, `Caret mode` doesn't work very nice for me. I can't find a reason why would I want to drag caret around, if I could simply mark my starting point with 3-4 keypresses, and then expand selection as I want.

However, it doesn't mean that we need to implement only one possibility! I can imagine some people will find `EasyMotion` not easy at all, and so prefer to use slower, but predictable `Caret` mode.

I'm interested to hear your thoughts. Let me know if you want me to explain something more.

**Comment by smblott-github** [comment]
All very interesting.  The EasyMotion stuff looks cool, but is probably beyond scope.  It looks like the plan is pretty straightforward:
- Initially, implement a visual mode which *requires* an initial selection position.
- Subsequently, implement a caret mode which can be used if there is no initial selection.
- These two (and any future edit mode) should implement the same movement keys.  So we need to think carefully about how to build just one movement engine that can be reused.

(Actually, a caret mode might be just a vim-like normal mode, but without the commands for entering insert mode.)

**Comment by andrewsanchez** [comment]
EasyMotion in Vimium would be incredible :)

**Comment by rrsahutwo** [comment]
It is essential to talk about the installment methods, warehousing and storerooms with them. We are presumed company and will be more than happy to answer such inquiries. Our policies are obvious and transparent and we have no hidden expenses.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
We have all Indian permit and are allowed to take your items and items to any aspect of the nation. But in case you are going to seek the services of some other company, you must check the permit of the company you select for moving your family or workplace merchandise and confirm their permit with the encompassing DOT workplace. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
There are diverse sorts of licenses and the guidelines contrast from one state to the next. At the point when moving inside of the state the mover and packers ought to have a permit from the state's transportation division or Bureau of Consumer Affairs. When you seek the services of our expert Packers and Movers Services in Bangalore or any other places of Indian, you need not worry about all that as we have all these factors completed.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
We know that it is also very essential to have the service of insurance strategy with the movers or company. As International movers and packers it is imperative to have excellent and appropriate policy for damaging your items and items. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by dragonxlwang** [comment]
+1. But I am having a problem of reentering caret mode after any visual mode before. Say that I want to move to a new location and make a selection in visual mode, how can I move around? it always starts from the initial location...

**Comment by smblott-github** [comment]
@dragonxlwang... Perhaps use "find" to position the selection?  Find mode works within visual/caret mode too.

**Comment by dragonxlwang** [comment]
@smblott-github . that indeed changes the position for visual selection but still not intuitive enough. if I want to select the next two words after the find, I need to redo search again and go over all the  previous possible matches.

Hope that there would be a way to change position in caret mode.


But thanks.

**Comment by andrewsanchez** [comment]
Normal vim motion commands , ie w, b, h, l, etc. work just fine for me in caret mode.  I have to enter visual mode first, then caret mode, then I can move around. .

**Comment by dragonxlwang** [comment]
@andrewsanchez how do you enter caret mode after visual mode? can you enter caret mode more than once for a single page??

**Comment by smblott-github** [comment]
@dragonxlwang... `c`... [wiki](https://github.com/philc/vimium/wiki/Visual-Mode).

**Comment by dragonxlwang** [comment]
@smblott-github that didn't answer my question....

**Comment by innaterebel** [comment]
@dragonxlwang
> `v` and `c` can be used to move back and forward between visual and caret modes.

**Comment by dragonxlwang** [comment]
thanks! @innaterebel 

it would be great if the keymap can be updated to include this.

**Comment by dragonxlwang** [comment]
@innaterebel @smblott-github , my apologies.. Thanks you all!

**Comment by fabriziobertoglio1987** [comment]
the issue here that the cursor is not allways positioned on the page. Would be nice having the Caret Cursor highlighted 

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **Caret Cursor is positioned on the page/div** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109666176-3d99ad80-7b6f-11eb-95bc-87fe4f7855df.mp4" width="700" height="" /> |

| **Caret Cursor is not positioned on that html element** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109666209-44c0bb80-7b6f-11eb-8474-264b2d64f976.mp4" width="700" height="" /> |

</p>
</details>

This can be done as by the following instructions

https://support.mozilla.org/en-US/questions/1280609

so I changed the cursor and enabled caret browsing with F7. Now I can clearly see the cursor moving to the correct position in the screen


**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **after** | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109668027-088e5a80-7b71-11eb-8e5f-707b2e208765.mp4" width="700" height="" /> |

</p>
</details>

**Comment by fabriziobertoglio1987** [comment]
@smblott-github after some troubleshooting .. I think it is not worth using this functionalities of Vimium.. The README should have some explanation that this functionalities do not work very well, otherwise users may invest lots of time troubleshooting them

Vimium needs the `find` functionality to work on the entire page, so we can move our cursor using find without having to move the cursor with tab to the correct position

similar to how ctrl+f works in firefox 

Open below the videos to understand better what I mean. Thanks a lot :peace_symbol: 

**<details><summary>CLICK TO OPEN TESTS RESULTS OF WHAT I'M TALKING ABOUT</summary>**
<p>

| firefox ctrl+f allways works and finds any text in the page  | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109961240-fedc3280-7ce9-11eb-9b22-d27c4ddb100d.mp4" width="700" height="" /> |

| vimium find does not work | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109961246-000d5f80-7cea-11eb-8d77-0b5e797dd89c.mp4" width="700" height="" /> |

| I need to move my caret cursor to that paragraph and then I can select or search that area | 
|:-------------------------:|
| <video src="https://user-images.githubusercontent.com/24992535/109961485-59758e80-7cea-11eb-9196-7a9a1f3ddea2.mp4" width="700" height="" /> |

</p>
</details>

**Comment by bushnerd** [comment]
> EasyMotion in Vimium would be incredible :)

But there is nothing, i am also waiting for this feature.
