### ISSUE TITLE
[Feature request] Ability to import/export settings

### ISSUE THREAD

**Issue by vitorgalvao** [philc/vimium#1440]
I know Vimium can sync its settings, but that requires users to login in Chrome, leaving people who don’t do it without a way to easily keep custom configurations. I currently have three text files with my customisations — excluded URLs, CSS for styling, and key mappings, which have to be saved and reapplied manually (plus a few others that rely on checkboxes).

A way to export and import all settings, even if it just means saving everything to a plain accessible file (so at least we could automate moving it to the correct location) would be very welcome.

**Comment by smblott-github** [comment]
Hi @vitorgalvao.  I'm not sure this is above threshold for the necessary extra options-page infrastructure.  After all, if someone chooses not to log in to Chrome, there are consequences...

Suggest we let this sit, and see whether further use cases emerge.

**Comment by vitorgalvao** [comment]
> After all, if someone chooses not to log in to Chrome, there are consequences...

I have no data on what percentage of Chrome users actually do it, but I’m guessing a good number of technically-inclined users (more likely to look for and use something like Vimium) might not do it due to privacy concerns.

Speaking for my usage exclusively, I’d be happy if there were a single file in the OS’s directory structure where configurations would be read from. Something we could `cp` and `mv` at will to achieve the same effect.

For reference, here’s how [Vrome](https://github.com/jinzhu/vrome) does it

![](http://i.imgur.com/Ek9adEx.png)

**Comment by dragon788** [comment]
I'd like to second this one. I've already been considering unmapping and
rewriting everything into the custom field, but I've actually be having some
trouble getting unmap and map to work on some of the preconfigured keys like t
and T (I want to swap them) and some others like moving i to I (so I can pass
through i to Inbox and Gmail without having to learn extra behaviors).

**Comment by smblott-github** [comment]
I swap `t` and `T` too...

```
map t Vomnibar.activateTabSelection
map T createTab
```

You don't have to "move" `i` to `I`, just add an extra mapping...

```
map I enterInsertMode
```

(I use a similar trick mapping `J` and `K` to scrolling commands so that they are available on GMail and the like too, even while using the page's `j` and `k` bindings.)

**Comment by dragon788** [comment]
@smblott-github does mapping J and K affect switching tabs using them then, because I use that pretty heavily in between my vomnibar tab jumping.

**Comment by fnkr** [comment]
I lost all my Vimium settings today. Chrome said the extension is broken and after I clicked "Repair" everything was gone. It took half an hour to configure everything again.

Now I managed to create a backup by doing `JSON.stringify(localStorage)` on the Vimium options page.

**Comment by vitorgalvao** [comment]
> I'm not sure this is above threshold for the necessary extra options-page infrastructure.

Looking at that again, there are already a bunch of options hidden under a `Show Advanced Options` button, so why would it be an issue to have two buttons on the bottom?
![image](https://cloud.githubusercontent.com/assets/1699443/10222760/9bbe4d02-684d-11e5-88bb-038eccd73ffb.png)

I’d understand if you didn’t want to pollute a settings page with too many options, but from the moment some of those are hidden and labeled “advanced”, all bets are off, there.

**Comment by smblott-github** [comment]
> ... I managed to create a backup by doing `JSON.stringify(localStorage)`...

@fnkr.... Be careful with this.  First, `localStorage` is not the primary storage location for settings.  For most users, they're in `chrome.storage.sync`, and for a (thought to be) very small group of legacy users they're actually in `chrome.storage.local`.  Second, we sometimes make changes to both how and where settings are stored, and implement migration code accordingly.  Diddling with settings directly could cause unexpected errors.

If you **must** access your settings in the way you describe, then the `Settings` API is safer (since it handles storage and propagation correctly):

    Settings.get(key)
    Settings.set(key, value)




The keys are [here](https://github.com/philc/vimium/blob/master/lib/settings.coffee#L97)

For the big-ticket settings... `keyMappings` and `searchEngines` are just text, so you'd be better off just saving them somewhere. `exclusionRules` is stored as structured data.

**Comment by vitorgalvao** [comment]
Another example, [chromium-vim](https://github.com/1995eaton/chromium-vim) (does the same as Vrome)

![](https://cloud.githubusercontent.com/assets/1699443/10543830/0f1e424a-7418-11e5-8ef3-228e2d32bedc.png)

**Comment by gramic** [comment]
+1
The same "Repair" problem like [fnkr](https://github.com/philc/vimium/issues/1440#issuecomment-144725063) happened to me today.

**Comment by vitorgalvao** [comment]
As a small note, I no longer use Vimium. If the others that expressed interest in this also do not care for this anymore, it can be closed.

**Comment by fnkr** [comment]
I do care.

**Comment by hervethouzard** [comment]
Hello,

At my work I am logged with my job profile and at home I use my own (personnal) profile.
In both cases I would love to be able to sync settings between then with the help of an export / import button.

**Comment by d-nnis** [comment]
> After all, if someone chooses not to log in to Chrome, there are consequences...

Giving my two cents for this issue:
Of course, it is true, not signing in to Chrome leads to consequences which are, for one, not giving away private data, as some might call those...
With Vimium however, those consequences are of a technical nature, since it is being _decided_, for now, to not give the ability to sync Vimium settings w/o Google's sync service. I, for one, see technical matters as matters of freedom, so just choosing Chromium and choosing Vimium should not lead to get stuck with the Google's way of doing things.

**Comment by lindhe** [comment]
I think this is something that many of the incoming VimFX users (me included) would want to have. We are used to having it, so it's even more prevalent as a missing feature.

**Comment by vab9** [comment]
+1. This would also allow users to sync Vimium settings between Chrome and Firefox. Should be relevant now that [vimium-ff](https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/) exists.
