### ISSUE TITLE
Requirements for [``] command

### ISSUE THREAD

**Issue by pakchoi** [philc/vimium#1442]
In the vim, we can use [``] command to jump cursor to the last position. This operation is such convenient to use it with [m] markup...
Forgive my poor English...

**Comment by smblott-github** [comment]
Hi @pakchoi.  What do you have in mind as the target for [``]?  In Vimium, we mostly have scrolling, which is not quite the same thing as the movements.  The exceptions might be marks and find mode.

**Comment by pakchoi** [comment]
When I read long news article, and I want to compare some paragraph. [``]command can help. It don't mean you can't use marks or find mode. What I mean is this method can make vimium more convenient and more vimalike...

**Comment by Darkwater** [comment]
Yeah, I'd like this too. Sometimes I want to jump to the header of a page, and then jump back to where I just came from. It'd work the same as setting a mark, then jump away (eg. to the top using gg), then jump back to said mark.

**Comment by talbright** [comment]
I think some level of support for markers would be very useful (http://vim.wikia.com/wiki/Using_marks). This would be great for technical documents, reading directions, etc when they are on one long page.  
Unlike vim however, I would show the marks with labels similar to what you get when using the ```f``` shortcut, but perhaps a different color.

I would not expect vimium to remember my markers between page reloads.

**Comment by smblott-github** [comment]
@talbright.  Vimium already supports (intra-page) marks.  Use `ma` to set mark `a`, and ``a` to return to that position.  Is that what you had in mind?

**Comment by talbright** [comment]
![image](https://cloud.githubusercontent.com/assets/212177/6755722/93c19faa-cefb-11e4-9bb1-8bdd731ba239.png)

That being said, it kinda makes me wonder if I'm not the first person to miss this because I didn't notice to click on **show advanced commands**. At some point as your feature list grows, you might want to think about how the help documentation is organized. Not sure I have any specific suggestions though, UI design isn't my forte. 

Regardless, super awesome plugin it's quickly becoming indispensable to me :+1:
