### ISSUE TITLE
Seach engine Shortcuts do not work, "occasionally"

### ISSUE THREAD

**Issue by esster** [philc/vimium#1449]
I have 3 vbar search engine shortcuts:

> w:
> i:
> a:

w and i work, as expected, "a" does not, for no recognizable reason.

I, of course, "naively" assumed that the vbar checks the shortcut list first
before doing anything else, but this does not seem to be the case ...

#1397

**Comment by smblott-github** [comment]
Might this be a symptom of #1384?

Could you post exactly what you have for `a`, please?

**Comment by esster** [comment]
in "reality" it presently looks like this:

> a: http://dict.leo.org/frde/index_de.html#/search=%s
> b: http://dict.leo.org/ende/index_de.html#/search=%s

and b does not work,

this works:

> dxf: https://www.google.com/search?q=define+%s

but I had to try out a dozen different shortcuts before I finally
found one that worked ...

**Comment by esster** [comment]
Closed by accident!

**Comment by smblott-github** [comment]
I tried...

```
b: http://dict.leo.org/ende/index_de.html#/search=%s
```

... and it seemed fine:
- `o`, `a something`, `Enter`.

What are you seeing?

**Comment by nebenjamin** [comment]
I believe I may be experiencing a similar issue. I have the following search engine defined:
mdn: https://developer.mozilla.org/en-US/search?q=%s

When I attempt to use the CSE, I would expect to run into #1384, which is what happens if I use the provided Wikipedia CSE. Instead, my search gets sent to my default search engine. So entering `mdn array.slice` in the Vomnibar results in being directed to https://duckduckgo.com/?q=mdn%20array.slice.

**Comment by mrmr1993** [comment]
Using which version, `master` or Chrome Web Store?

**Comment by nebenjamin** [comment]
Chrome Web Store.

Chrome Version: 41.0.2272.101 m
Vimium Version: 1.49

**Comment by smblott-github** [comment]
@nebenjamin. This is odd.  Unfortunately, I can't seem to reproduce it in either 1.49 or master....

**Comment by nebenjamin** [comment]
I added Chrome and Vimium to a Linux VM and couldn't reproduce it either. I did go ahead and debug what I've got installed rather than installing Node.js, npm and coffeescript. Looking at the compiled javascript, the debugger was showing me an object that looks like this:
```javascript
{
  mdn: https://developer.mozilla.org/en-US/search?q=%s,
  w: "http://www.wikipedia.org/w/index.php?title=Special:Search&search=%s"
}
```

I changed my CSE to:
`mdn: 'https://developer.mozilla.org/en-US/search?q=%s'`

Then I saved my settings which then results in behavior like #1384. I then removed the single-quotes and the CSE works without #1384 behavior.

It seems like `master` may fix the issue since parseSearchEngines appears to have been modified since 1.49.
