### ISSUE TITLE
Feature request: Option to map some key to Escape

### ISSUE THREAD

**Issue by saheel1115** [philc/vimium#1463]
Hi, I find it tedious to go all the way to the Escape key to stop some command (link-hints or text search, etc.) or to lose focus from edit mode. Is there a way (or can it be added) to map a custom key to do this job?

BTW, I'm really love Vimium because of its simplicity and unintrusiveness. It doesn't mess up with what the browser already has to offer. Thank you, guys! :)

**Comment by RobertCompton** [comment]
I second this idea. I also think there should be a way to map to arrow keys and such (for expanding Vimium hotkeys to work as site hotkeys, eg; shift right arrow on Soundcloud). Should be support like .vimrc does; <ESC>

**Comment by mrmr1993** [comment]
> I also think there should be a way to map to arrow keys and such (for expanding Vimium hotkeys to work as site hotkeys, eg; shift right arrow on Soundcloud).

@RobertCompton This is a much more difficult thing to implement; certainly, it is beyond the scope of the original issue. I have some ideas for how we might implement this, and, if you open a new issue for this, I will happily discuss them there.

**Comment by smblott-github** [comment]
On the topic of remapping `Esc`.  What is the use case?  What would you expect the configuration/mapping to look like?  Why should this be done in Vimium (as opposed to at the OS/window manager level)?

**Comment by RobertCompton** [comment]
In vim I have \<c-k\> mapped to \<ESC\> so that I can break from insert mode or v-block easier. Being able to break out of inserting text (like from this text box right now) without having to tab into a non insert element or reaching to the escape key would be great. Don't think Chrome would allow this, but would also be a great feature to allow breaking out of the omnibar in a new tab instead of the current and unreliable double tab tap I use.

Would definitely be an advanced support feature, but would be really nice. Also mapping to other key combos instead of just commands in Vimium would allow for fantastic support of hotkeys native to sites. Not only could you add exclusions (as I have), but could map alternate commands for site hotkeys. This whole thing becomes pretty .rc, which someone already opened as issue for (and I think that's a fantastic idea).

**Comment by smblott-github** [comment]
> Also mapping to other key combos instead of just commands in Vimium would allow for fantastic support of hotkeys native to sites.

As @mrmr1993 said, that's really another matter entirely.

On `Esc`, I can see the use case.  And it wouldn't, I think, be too hard or disruptive to implement it. @mrmr1993: I'm thinking just of pushing the mapping to the content script and extending the implementation of `isEscapeKey`.  What do you think, @mrmr1993?  Would that work?

**Comment by mrmr1993** [comment]
> Would that work?

Should work, but I'm not really a fan.

I'd rather see something like

```
gmap <esc> exitCurrentMode
gmap <c-]> exitCurrentMode
```

in the default mappings (where `gmap` means global map and `exitCurrentMode` is the only `gmap`-able command, at least for now), showing this command in the help dialog, and letting the user use this mechanism to specify their own keys/unmap the defaults.

`isEscapeKey` is already a lie (because `<c-]` isn't really escape), but I'd rather not make the situation worse, and just be a bit more honest in the code with what we're actually doing.

**Comment by saheel1115** [comment]
+1 for gmap. Looks neat and is clearly comprehensible.

**Comment by Zamicol** [comment]
I would also greatly benefit from this.  

I would like to map <c-space> to <esc>, or something like that, because escape is very small on my keyboard and very far away from everything else.  I always have to look down at the keyboard in order to hit escape which is far from ideal.  

On the same note, is there any other way to escape from a text box in vimium and get back to "command mode" without using the mouse or escape? It would be nice to have a key binding that always returns you to a base command mode state.

**Comment by smblott-github** [comment]
Would it not be better to do this at the OS/window-manager level?  Presumably you'd want `<c-space>` to close popups and dialogues too.

**Comment by Zamicol** [comment]
In emacs if I need to stop a command at any point and go back to a "base state" I type `<Control-g>`.  Stock vim does the same thing using `<Control-c>` which exits insert mode putting the user back into command mode, the "base state".  

I could map `<esc>` to some more convenient keybinding at the OS/window-manager level, but this feels like there should be some other key binding for getting out of a text area or insert mode and back into command mode.  Right now I only have the one option, `<esc>`, and I have no means to map this inside of vimium to some other keybinding.  

Also, `<esc>` isn't a sure way to get back to a base state.  Take for example when I'm focused on the location bar. When the address bar is in focus I have to press `<tab tab>` to focus back onto the page, the base vimium state.  This also has the unintended side effect of scrolling to the top of the page.  ([See here for a stackoverflow question regarding this](https://superuser.com/questions/324266/google-chrome-mac-set-keyboard-focus-from-address-bar-back-to-page/324267#324267)).  

Escaping out of a text area is a task I'm finding I do all the time while using vimium and it would be nice if Vimium had the vim equivalent of `<Control-c>`.  Granted, `<Control-c>` would be a terrible binding since Chrome already uses this for "copy".  I was thinking maybe `<Control-space>`?

For reference, here is the vim wiki page ["Avoid the escape key"](http://vim.wikia.com/wiki/Avoid_the_escape_key)

**Comment by truth1ness** [comment]
I would also like a different button for escaping out of things, the escape key is the only one where I have to stretch my hand far out of position and slows things down.

**Comment by rrsahuone** [comment]
When you are looking for right provides by best packers movers Bangalore , keep your stress on to us. Now we are available to help you with a compiled record of best packers and movers in Bangalore and across India. Once you will begin working with us, you will come at the same position for your moving and shifting problems. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
We help you to select best movers and packers in Bangalore assuring price range provides and satisfactory client solutions. We are providing solutions not only in significant places of Bangalore but across India.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
We provide you with a record of effective and established packers and movers in Bangalore with their finished information that are necessary to get in touch with like complete address, Name, Phone no, Email id etc. we also provide you with website link so that you can examine their stage of solutions itself. We provide you with a chance to get in touch with best Companies yourself without compromising on high quality standards.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
Secondly, we record you estimates from best product packaging moving Companies in Bangalore or close by locations. It creates your searching procedure mush simpler and simple. You just need to compare quotes and select the best cope as per your convenience. Don’t be afraid of stability as we have been checked everything to guarantee the best cope for you.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
