### ISSUE TITLE
Open new tab in incognito mode should open new tab in same window

### ISSUE THREAD

**Issue by wadkar** [philc/vimium#1507]
Vimium version 1.49 (stable downloaded from Chrome Store)

Expected behavior: Pressing `t` while in incognito mode should open a new tab in the same incognito window
Actual behavior: Pressing `t` while in incognito mode opens a new window, i.e. _non-incognito window_

How to reproduce: Open a new incognito window and browse to any page. Press `t`
Comments: It is interesting to note that `Vomnibar.` shortcuts (`o`,`O`) and follow link shortcuts (`f`, `F`) do not open a new _non-incognito window_. They merely open a new tab in the current window.

**Comment by wadkar** [comment]
After a little bit of digging around the source code and looking through Chrome JS APIs, it appears to be an upstream [bug](https://code.google.com/p/chromium/issues/detail?id=308171)
Not sure whats the policy on closing the issue. But keeping it open for the sake of posterity.

**Comment by mrmr1993** [comment]
We can fix this easily by changing the `openUrlInNewTab` function (`background_scripts/main.coffee`) from

```coffee
chrome.tabs.create({ url: Utils.convertToUrl(request.url), index: tab.index + 1, selected: true }))
```

to

```coffee
chrome.tabs.create({ url: Utils.convertToUrl(request.url), index: tab.index + 1, selected: true, windowId: tab.windowId }))
```

**Comment by wadkar** [comment]
Actually, the appropriate place for the change would be [Line 223](https://github.com/philc/vimium/blob/master/background_scripts/main.coffee#L223) where createTab is called.
I might suggest that we could change
`createTab: (callback) -> chrome.tabs.create({url: Settings.get("newTabUrl")}, (tab) -> callback())`
to
`createTab: (callback) -> chrome.tabs.create({url: Settings.get("newTabUrl"), windowId: tab.windowId}, (tab) -> callback())`
Could you please try it out and see if it works?

**Comment by mrmr1993** [comment]
I don't think that would work, since tab is undefined in that context. This bug will also affect the `openUrlInNewTab` function, so we need a fix there too.

`createTab` should be rewritten anyway. This (with my above fix) should work:

```coffee
createTab: openUrlInNewTab Settings.get "newTabUrl"
```

**Comment by rajeevksahu** [comment]
However the moving alternatives have changed the scenario absolutely. Today, everybody require packaging and movers to shift to their valuables as he himself can’t do it on his own due to the lack of required moving features. For all those who want best moving alternatives, our packers and movers alternatives in Mangalore would be the best according to their likings. Relocation to a town or a position can be of different types such as professional shift, personal moving, company moving, domestic moving and so on. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We are here to solve each and every problem related with your moving. If you are being transferred to another town then we can help you out in moving to that position in the most secure way with the help of our packaging moving Mangalore alternatives. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We are one of the best packers and movers in Mangalore who are equipped with the most advanced features using which we can provide best moving alternatives to the those who are looking for efficient movers in packers in Mangalore. Everyone should be happy after choosing our Mangalore packers and movers alternatives as we are one of the most renowned packers and movers in the town. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Choosing our alternatives will provide you freedom from all your issues related with moving alternatives. At our company, we believe in providing our alternatives in the most secure way so that all the needy people always select us whenever they are in need of any workplace moving or house moving.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
