### ISSUE TITLE
Incorporating Scroll Step Size into Commands

### ISSUE THREAD

**Issue by davidleejy** [philc/vimium#1510]
Do you think it'd be a good idea to Incorporate step size into page navigation commands (e.g. scrollUp, scrollDown) to result in commands like scrollUp(x), scrollDown(x)?

A user's key mappings could then be:
map j scrollDown(60)               " scroll down 60 step size.
map J scrollDown(120)            " scroll down 120 step size.
map d scrollPageDown(0.5)     " scroll down half a page.
map D scrollPageDown(1)       " scroll down a full page.
...

Currently, scroll step size is exposed in Advanced Options.  I think changing this step size affects all scrolling commands.

Thanks for reading.  I'm new to vimium and it's my first time writing an issue.  I apologize if I've raised a silly "non-issue".

**Comment by smblott-github** [comment]
Closing.
Lack of interest.

**Comment by Madd0g** [comment]
I was thinking today about a new possible shortcut for me to be even lazier - instead of having all the usual link hint letters, my new shortcut will only have left/right side of the keyboard, depending on which hand I'm using.

This params syntax would've solved the problem for me (if the LinkHints.activateMode supported params as well, that is).
