### ISSUE TITLE
main.coffee: generateCompletionKeys treats keysToCheck mistakenly

### ISSUE THREAD

**Issue by gdh1995** [philc/vimium#1545]
main.coffee:
507: `generateCompletionKeys = (keysToCheck) ->`
508: >>`splitHash = splitKeyQueue(keysToCheck || keyQueue)`

Then, if `keysToCheck` is `""`, `keysToCheck || keyQueue` will be `keyQueue`, which makes

578: `completionKeys: generateCompletionKeys("")`

build `completionKeys` with `keyQueue`.

However, when sending "executePageCommand" messages, `keyQueue` can be a non-empty string, if the current is a two-key command. So I think `generateCompletionKeys` works mistakenly.

**Comment by smblott-github** [comment]
Thanks, @gdh1995.  This does indeed look odd.  It appears that the `completionKeys` field of the `executePageCommand` message is actually ignored in the front end. `executePageCommand` then asks (again) for the completion keys via `refreshCompletionKeys` and the `getCompletionKeys` message.  And by the time that message gets to the background page, `keyQueue` has been reset.

All of which is (probably?) correct, but pretty odd.  Looks like technical debt.  I'll take a closer look soon.

**Comment by gdh1995** [comment]
If possible, we may:
* remember `singleKeyCommands` in the frontend;
* pass "left" `completionKeys` except `singleKeyCommands`, if any key pressed.

I think, this will reduce the message's size a lot - executePageCommand and many other key-press messages will not need to send a huge array of `completionKeys` - only `[]` will be sent `if !keyQueue`

**Comment by mrmr1993** [comment]
I'm always surprised by how hellish this section of the code is.. Anyway, for this particular case:
* `splitKeyQueue` returns `{count: NaN, command: ""} `.
* `completionKeys` is preloaded with a copy of `singleKeyCommands`.
  - this is redundant anyway, since everywhere `currentCompletionKeys` is checked in the frontend, `isValidFirstKey` is also called, which covers this.
* `getActualKeyStrokeLength(command)` returns `0`, so the conditional doesn't get run.
* the function returns `completionKeys` which is a copy of `singleKeyCommands`.

This isn't doing anything *wrong*, but it's definitely *unclear*. Changes I would make:
* initialise `completionKeys` without `singleKeyCommands` in `generateCompletionKeys`
  - so, `completionKeys = []` instead of `completionKeys = singleKeyCommands.slice(0)`.
  - this also allows us to get rid of `singleKeyCommands` and `populateSingleKeyCommands` completely.
* combine all frontend checks of `isValidFirstKey` and `currentCompletionKeys` into a single call to a helper function, to make sure we never accidentally check one and not the other. So,
  - rename `isValidFirstKey` to `isValidKey` (in the frontend) and change it from
```coffee
isValidFirstKey = (keyChar) ->
  validFirstKeys[keyChar] || /^[1-9]/.test(keyChar)
```
to
```coffee
isValidKey = (keyChar) ->
  validFirstKeys[keyChar] or /^[1-9]/.test(keyChar) or keyChar in currentCompletionKeys
```
  - replace all `currentCompletionKeys.indexOf(foo) != -1 || isValidFirstKey(foo)` with `isValidKey(foo)`.

We also leak key events when `0` is typed as part of the number prefix, so we could mitigate that by having:
```coffee
generateCompletionKeys = (keysToCheck) ->
  {command, count} = splitKeyQueue(keysToCheck || keyQueue)

  if not isNaN(count) and command == ""
    ["0"] # Handle key events for 0s in the number prefix properly.
  else if getActualKeyStrokeLength(command) == 1
    completionKeys = []
    for key of Commands.keyToCommandRegistry
      splitKey = splitKeyIntoFirstAndSecond(key)
      if (splitKey.first == command)
        completionKeys.push(splitKey.second)
    completionKeys
  else
    []
```

**Comment by gdh1995** [comment]
Another problem:
* `unmapAll`; map `Ft` ...; map `v` `nextTab`
* press: `F`, `2`, `v`

Expect: skip one tab and select the third tab (says the old current tab is "first");
Fact:  # no tab is skipped - tab[index + 1] will become selected

This is because `count` is set `1` in `checkKeyQueue` - when dealing with `F2`, checkKeyQueue:
* 589: `getActualKeyStrokeLength(command) > 1` is true;
* `Commands.keyToCommandRegistry[splitKey.second]` is false;
* `newKeyQueue = (if validFirstKeys[command] then count.toString() + command else "")`
* this statement makes `newKeyQueue` := "", since it doesn't know "1-9"

**Comment by gdh1995** [comment]
This issue has been useless, because all background handlers for the key queue will be removed soom or later - #1775 is not so bad.
