### ISSUE TITLE
Search text box on github "stealing" focus after "follow next link"

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#1588]
This is a similar issue to the one I opened for [cVim here](https://github.com/1995eaton/chromium-vim/issues/276).

**Comment by smblott-github** [comment]
Thanks @infokiller.  I don't understand how reproduce this.

**Comment by infokiller** [comment]
Sorry for the lack of clarity on my part. To reproduce:
1. Set "Don't let pages steal the focus on load" in Vimium settings.
2. Do any search on Github, like [this one](https://github.com/1995eaton/chromium-vim/issues/276).
3. Execute "follow next link" (by default it is mapped to ]]).

**Comment by infokiller** [comment]
Urgh, the search link example is wrong, try this one:
https://github.com/search?utf8=%E2%9C%93&q=whatever

**Comment by smblott-github** [comment]
OK.  I see it now.

The issue is that the `]]` is not loading a new page (on github).  It's doing a web navigation.  No-grab-focus should probably apply in that case too.

**Comment by mrmr1993** [comment]
> It's doing a web navigation. No-grab-focus should probably apply in that case too.

There's no API for detecting `history.pushState`, and detecting the navigation in the background page is asynchronous, and so will open us up to race conditions. Can I suggest that when a user uses Vimium to click a link which has
* `link.href.split("#")[0] != document.location.toString().split("#")[0]`
* `link.target == "" `
then we call `new GrabBackFocus()`? Most `history.pushState` links take this form to support older browsers (and if it's a normal link then there'll be a redirect anyway) so activating `GrabBackFocus` mode should be safe to do.

**Comment by smblott-github** [comment]
Are you sure there's a race condition, @mrmr1993?  E.g. 061e99f895e5655d351ad1585af028a12abf3ec0 seems to work.

(If there's a race condition with 061e99f895e5655d351ad1585af028a12abf3ec0, then there's also a race condition with #1580, is there not?)

**Comment by mrmr1993** [comment]
> Are you sure there's a race condition, @mrmr1993?

Yes. We're doing an asynchronous round-trip of the background page, so the user may have manually selected a textbox 'while we were away', especially on slower computers or when the page runs `history.pushState` 'late' (eg. after images have finished loading).

> then there's also a race condition with #1580, is there not?

Yes, but there isn't any better way of detecting URL changes that I'm aware of.

Other thoughts:
* if a page uses `history.pushState` to generate autosave urls as a user types, they'll be dumped out of their textbox each time an autosave happens.
* ditto for if the user can save using a keyboard shortcut from inside a textbox.
* trigger on hash change stops intentional focus changes when a programmer has forgotten to cancel the default action of a click on an `<a href="#">` in their handler. (I think we should ignore hash changes entirely.)
* overlays which change url (eg. to support legacy users/dropped internet connections) but close on blur will be rendered completely unusable by any attempts to fix this issue.

These were the (main) reasons why I settled on my last suggestion. I probably should have mentioned them then instead of trying to keep the comment length down. 061e99f is far too aggressive, in my opinion.

**Comment by smblott-github** [comment]
On the other hand, @mrmr1993, 061e99f895e5655d351ad1585af028a12abf3ec0 would also work if the user just plain-old clicked on "Next" (whereas the alternatives wouldn't).

**Comment by mrmr1993** [comment]
My original suggestion, minus the requirement that Vimium should be the cause of the click would do the same. And, unlike 061e99f, it wouldn't kick the user out of textboxes indiscriminately every time `history.pushState` is run.

A 'don't let page scripts focus inputs' option would be much more straighforward to implement, much more transparent for users, and lets us avoid trying to come up with a heuristic for javascript page loads.

**Comment by smblott-github** [comment]
@mrmr1993.  Might we not take 061e99f895e5655d351ad1585af028a12abf3ec0, but filter based on the [transition type](https://developer.chrome.com/extensions/webNavigation#type-TransitionType)?

**Comment by mrmr1993** [comment]
That `link` transition type sounds ideal, lets go with them!

**Comment by smblott-github** [comment]
Reopening.
#1609 gives a hideous UX on Google Inbox.  Losing the focus on web navigation might be something we just have to live with.

(Although, to a user, they don't see the difference.  Perhaps the *grab-back-focus* lark is fatally flawed.)

**Comment by mrmr1993** [comment]
@smblott-github I don't think you actually re-opened this issue with your last comment?
