### ISSUE TITLE
Vimium failing to activate on startup.

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1683]
I rarely stop chrome entirely.  However, I've done so a couple of times recently.  And the content scripts are failing to activate on startup.  Looks like yet another race condition.  `response` in `isEnabledForURL` is coming back `null`.

**Comment by gdh1995** [comment]
I've run into this situation before. This is because background ran later than the front-end, and `chrome.runtime.sendMessage "isEnabledForURL"` found no listener. In this case, a simple retrying will be fine.

But, the port returned by `chrome.runtime.connect` will auto-disconnect if no receiver (in 0~16ms), so we need to test whether the port is disconnected, which will be a little troublesome, since we have listened `keyPort.onDisconnect` in `initializePreDomReady` and turn off Vimium at once if disconnected.

We can simulate this race condition by closing the background page:
* close Vimium's pages like the options.
* open [chrome://extensions/](chrome://extensions/)
* select Vimium and check its background page
* type `close()` on the console of the Developer Tools and enter
* then there's no backend listeners
