### ISSUE TITLE
Is there a way to load Vimium on chrome-extension:// pages?

### ISSUE THREAD

**Issue by deiga** [philc/vimium#1710]
I'm using [Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) and I wold still like to be able to use Vimium whenever a page is suspended. 

Are there any options for it? Is it even possible to do?

**Comment by smblott-github** [comment]
I think that's not possible.  Chrome just doesn't run extensions like Vimium on `chrome-extension://` pages.

(We even have to specially inject our own content scripts into our own extension pages, like the options page.)

**Comment by smblott-github** [comment]
Closing, @deiga. Probably nothing we can do.

**Comment by gdh1995** [comment]
We may write a injector file, and if other extensions are likely to be compatible with Vimium, they may just add `<script src="chrome-extension://***/...injector.js">`, and then this file do the rest of injecting work.

If so, Vimium's front-end should be reworked to achieve greater compatibility: 
* `window.onbeforeunload` should be changed to an event listener;
* `Utils.invokeCommandString` should search commands from a special variable, not `window`
* chrome's messages logic must be considered

Benefits:
* I've checked the code, and Vimium's front-end commands just including these:  
    `LinkHints.**`, `Vomnibar.**`, `Marks.**`, and those `extend`ed in `vimium_frontend.coffee:301,315`
* An advanced user can modify his extensions' files in the Chrome UserData folder, which is easy enough to make all extensions Vimium-enabled in one computer.

I've made a lot changes to my custom Vimium, and now I'm able to use `f` to click something in Chrome's new bookmark extension pages.
![image](https://cloud.githubusercontent.com/assets/5547703/7954240/3ab9a1ce-0a00-11e5-89cf-94f1f868967f.png)

Here's my project: https://github.com/gdh1995/vimium-plus  
and the injector file is https://github.com/gdh1995/vimium-plus/blob/master/lib/injector.js

**Comment by wblankenship** [comment]
@gdh1995 hmmmm this is promising.

Think we could write a util to auto-patch extensions?

**Comment by mrmr1993** [comment]
> We may write a injector file, and if other extensions are likely to be compatible with Vimium, they may just add

@gdh1995 there are a few things we need to consider here:
* Vimium is designed to need to run before all other scripts so that we can capture key event handlers and defer to page handlers only when we're in insert mode.
* The new Settings implementation will not work, since our `chrome.storage` isn't available from other extensions.
* An ill-intentioned extension could use our messaging API to do things it hasn't got permissions for.
* Any time we use the global scope (which we need to communicate between scripts) or touch the DOM, we can have name collisions with the native code.
* Any resources we fetch with `chrome.runtime.getURL` will point to the host extension and not Vimium resources (so we can't use the HUD, Vomnibar, or the link to the options page in the help dialog).

To avoid these problems, we would need a substantial rewrite of a lot of code.

It might be simpler and less painful to petition the Chromium devs to provide a mechanism for injecting an extension's content scripts into another extension's pages. If someone can come up with a reasonable proposal that the Chromium team approves, I'm happy to work on implementing it in their codebase.

**Comment by gdh1995** [comment]
@wblankenship: No auto-path extension can work. A Chrome extension can not write any files on the disk even in the folder belonging to itself, and it's refused to access others extensions' files except by XHR. Besides, this work needs to modify `.html` files, but machines do not know what files are wanted.

@mrmr1993 All of what you says are right, and I'm agree that we may not implement this.

Here are just some further thoughts:
* If an extension imports Vimium, we may assume it will not setup blocking listeners which do harm to Vimium. And DOM should have been safe.
* `Settings` will not work: Yes, so we still need a separate way (like the early `settings`), not in common content scripts, but injected into other extensions only.
* "ill-intentioned" extensions: This problem is the most harmful one. I've tried some authentication logic, but find that in fact no way can strictly protect the messaging mechanism.
* global scope: I'm not very sure what's "scoped needed between scripts"; Frontend files may be joined into one file and wrapped by `(function(){...})();`, and then no variable needs to be added to `window`.
* `chrome.runtime`: Yes, they are all untrusted, so we can only send all messages to Vimium's background.

This method is not perfect at all. I also want a official mechanism. If there is one, I think, it may be in the form of a whitelist of extensions allowed to be injected.

What inspires me to make rework in my [vimium-plus](https://github.com/gdh1995/vimium-plus) is that I'm able to force other extensions to import Vimium by modifying their files, and don't need to wait for their authors to add this feature.
