### ISSUE TITLE
Global marks don't work (and may never have worked?)

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1712]
(Am I going mad?)

Going right back to this commit aeb455a577c0a20684f357ff737203b5cb419cd4, it looks like global marks don't work, and may never have worked. (Seriously, am I getting this wrong?)

[This](https://github.com/philc/vimium/commit/aeb455a577c0a20684f357ff737203b5cb419cd4#diff-d1acbe0799862381d234f7aa6f4cffacR8) test never succeeds, because the preceding `keydown` event for `<Shift>` causes the handler to exit.

(So, if I'm right -- and I have tested this -- then we can conclude that nobody is using global marks.)

**Comment by mrmr1993** [comment]
I believe that Windows will work as intended, so the feature isn't dead completely.

This is essentially the same issue we had with modifiers in `LinkHints` before (#1096). It would be nice to fix it in general, rather than having to keep rediscovering that `KeyboardUtils.getKeyChar` on `<shift>` returns `&nbsp;` on non-Windows platforms.

**Comment by smblott-github** [comment]
Thanks for that, @mrmr1993.

In the case of link hints (and marks) we should be using `keypress` instead of `keydown`, no?
