### ISSUE TITLE
Remove "CSS for link hints" option

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1719]
(@philc has proposed this before, but met some fairly mild resistance.)

We should remove the *CSS for link hints* option.

I've just started looking at tweaking the link hints UX for filtered hints:
- `Enter` activates the "first" hint, but there's currently no visual indication as to which one that is.
- Add `Tab` to make the next hint the active one for `Enter`.

(Why? When you're down to two or three hints, hitting `Tab`-`Enter` requires less thought than actually working out what to type to activate the second or third hint -- or even to figure out which is the first hint.)

So I went looking for the CSS to tweak this, and it's in ~~`options.coffee`~~ `settings.coffee`.  That's crazy.  We can't tweak the appearance of link hints for users who aren't using the default value.

(We don't allow users to customise the appearance of vomnibar, or the HUD.  Why on earth do we allow customisation of the appearance of hints?)

**Comment by gdh1995** [comment]
Well, in fact custom CSS is very useful for me: Vimium will filter out those nodes whose width or height is less than 3px, but I have turned off showing-image on most websites, which makes `<a><img></img></a>` often with a size of 0x0...

Then, I've set:
``` CSS
img {
  min-width: 3px;
  min-height: 3px;
}
```

Cool, isn't it?

**Comment by smblott-github** [comment]
@gdh1995. But that has nothing to do with link hints, and nothing really to do with Vimium at all.  You'd probably be better off doing that kind of thing with TamperMonkey or your own custom extension.

**Comment by mrmr1993** [comment]
@smblott-github it's part of a workaround for a decision we've made. Having a place that people can put css to make the extension work better for them is a good thing.

The real issue is that the default value isn't a no-op, which means that we have to take it into account for any changes we make. Simple fix: move the actual css content into `vimium.css`, and just keep the default as the selectors without any rules. I can see no benefits from removing it entirely.

(Full disclosure: I have a few custom styles on mine too, and so I'd be a bit peeved if this went away.)

**Comment by gdh1995** [comment]
> doing that kind of thing with TamperMonkey

I know, but it's too heavy than just what I need.

We may rename `userDefinedLinkHintCss` to  `userDefinedCss`.
