### ISSUE TITLE
cannot exclude '#' keybinding

### ISSUE THREAD

**Issue by wang-d** [philc/vimium#1757]
I would like to use the Gmail keybinding '#' to delete mail, but
if I type '#' into the exclude field, it seems to comment out the rest
of the field instead.

Steps to reproduce:

- open vimium options
- exclude url mail.google.com/*
- exclude keys jknp#c
- C-RET to save
- open Gmail

At this point, I expect that
* j selects the next message
* # deletes it
* c opens a compose buffer

Instead I observe that
* j select the next message
* # does nothing
* c does nothing

If I instead move the 'c' before the '#', I find that 'c' opens the
compose buffer as I would expect if it were being excluded.

Are you maybe running the exclude field through a parser that
interprets Python/bash style comment syntax?

**Comment by smblott-github** [comment]
Thanks for the detailed report, @wang-d.

This is weird.

First, there's no special meaning for `#`, so it's not being treated as a comment marker.

Second, I cannot reproduce the ordering problem you're seeing (so, `#c` is the same as `c#`, for me, and `c` is correctly excluded in both cases).

Thirdly, I *am* seeing an issue with `#`, though.  I do not map `#`.  So it should be passed through anyway.  I do, however, map `'`.  With `'` mapped, `#` is never passed through.  Without `'` mapped, `#` is always correctly passed through.

This looks like a keyboard locale issue.  On my keyboard, when I press '#' I get `'` on `keydown` and `keyup`, but `#` on `keypress`.  By adding `'` as an excluded key `#` works as expected on GMail.

I think what's happening is that (with `'` mapped) we suppress the `keydown` (because `'` is mapped and not excluded), and *that's* the event GMail is looking for.

Workaround: Find out what keyChar your keyboard produces on `keydown` for `#`, and exclude the corresponding character.

(What a mess.)

**Comment by wang-d** [comment]
I was wrong about the ordering.  I can no longer reproduce that either.  Sorry for not double-checking.

I typed `monitorEvents(document.body, 'key')` into my dev tools console, typed a `#` into GMail, and got `keydown` and `keyup` on keyCode 16 keyIdentifier 'U+00A0', and `keypress` on keyCode 35 keyIdentifier 'End'.  (Which, may I say, is crazy: `xev` gives me a KeyPress event on `keycode 50 (keysym 0xff31, Shift_L)`, KeyPress event on `keycode 12 (keysym 23, numbersign)`, and then KeyRelease on each, as expected.)

Am I doing this right?  It seems unlikely that Chrome is really interpreting '#' as 'End' but Gmail and all the other websites have somehow worked around that.  Much more likely that I'm not a Chrome dev and misunderstood something in the two links I read five minutes ago to do this.

**Comment by gdh1995** [comment]
Then what's your system?

My Windows works mostly well and gets `keyCode: 16, keyIdentifier: "U+0033"` when meeting `'#'`, which is just like `'3'` (with `shiftKey: true`).

For Mac OS, it's `keyIdentifier: "U+0023"` when I tested, just as [DOM-Level-3-Events-20060413](http://www.w3.org/TR/2006/WD-DOM-Level-3-Events-20060413/keyset.html) says.

**Comment by smblott-github** [comment]
@wang-d...  You could try [this](https://drive.google.com/file/d/0B-PWDBroAYxrOEdCSjdwWEJzd1k/view?usp=sharing).  It's just master with some additional frontend key-event logging.

- Create a new chrome account.
- Enable developer mode.
- Drag and drop this file onto the extensions page.
- Try it out on any old page...
- Press `#`, see what keyChars are reported on the (foreground) console.

**Comment by enochhsiao** [comment]
I'm actually having the same issue with the '#' shortcut not deleting emails in Inbox/Gmail and seeing the same `monitorEvents` output as @wang-d: `keydown` (16 - 'Shift'), `keypress` (35 - 'End'), `keyup` (16 - 'Shift').

Entering Insert Mode in Vimium and trying to type '#' again shows a different sequence:
`keydown` (16 - 'Shift'), `keydown` (51 - 'U+0033'), `keypress` (35 - 'End'), `keyup` (51 - 'U+0033'), `keyup` (16 - 'Shift').

Somehow the second `keydown` (which actually triggers the '#' shortcut) is being blocked?

**Comment by enochhsiao** [comment]
Update: I'm only seeing this on my Windows PC, Chrome+Vimium on my MacBook Air is behaving wonderfully.

**Comment by sid-kap** [comment]
I'm not sure why, but excluding '3' on Gmail solves this problem for me.
(I'm running Chromium 43.0.2357.81 on Ubuntu 14.10)

**Comment by mrmr1993** [comment]
We have no reliable way to convert a `keydown` for a number key with modifiers pressed into the symbol that that represents. Since we always (plan to) handle number keys, we always suppress their `keydown` events unless they're explicitly a passkey.

The shift modifier is calculated as changing the key to upper-case, which obviously has no effect on numbers, and so `#` is treated as `3` for layouts where they share a key. This is what causes this issue.

The 2 obvious approaches are:
* the current code, where we interpret the `keydown` as a number, so we correctly block `$` in `g$`, but incorrectly block `#` (in `en_US` et al.).
* interpreting the `keydown` as an unknown key, so we incorrectly pass `$` (except `keypress`) in `g$`, but correctly pass `#`.

These are both poor options. Obviously, when [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=227231) is resolved we can use `event.key` to handle the key correctly in all layouts and this will resolve itself.

In the meantime, possible painful but effective fixes could include:
* creating a mapping of keys to printing characters for every keyboard layout, and using those to treat keys correctly
* add a shift modifier `<s-KEY>` (perhaps only usable in passkeys mode), allow passkeys to work on complex keys (as in #1368), and then use `<s-3>` as a passkey to achieve this effect.
* hardcode an `en_US` conversion table, causing hard-to-explain issues for non-`en_US` layout users.
  - this might be workable as a default-off option
  - @gdh1995 seems to be pushing towards this in #1778

I'm personally inclined to just wait for the Chromium issue to be resolved, and having the GMail `#` shortcut require `i#<esc>` for the time being.

**Comment by gdh1995** [comment]
Yes, I made a conversion table for `en_US`, but I think it also works on others, since I use [`KeyIdentifier`](http://www.w3.org/TR/2006/WD-DOM-Level-3-Events-20060413/keyset.html) only.

Here is a obvious rule: if `event.shift` is `true`, then it's not `3` but `#`. So I use
``` javascript
keyId = parseInt(keyIdentifier.substring(2), 16);
// ...
(event.shiftKey && keyId >= 48 && keyId < 58)
 ? ")!@#$%^&*("[keyId - 48]
 : String.fromCharCode(keyId)
```

This is for Mac OS, since it show the same `keyIdentifier` for `3` and `#`, and as for Windows, `#` has its own identifier.

PS: I think this rule is easy to merge into the current version of `KeyboardUtils.getKeyChar`.
