### ISSUE TITLE
crowdin project requests

### ISSUE THREAD

**Issue by flashlab** [philc/vimium#1759]
I really hope vimium can implement i18n. To start a project in crowdin may simplify this process.

**Comment by gdh1995** [comment]
Now there's a problem: different keyboard layouts have some different keys which are hard to recognize and map.

As for the UI language, most words are easy to convert.

**Comment by jorgesumle** [comment]
Why did you closed this issue, @smblott-github? Vimium design goals says:

> A secondary goal is to make Vimium approachable, or in other words, to minimize the barriers which will prevent a new user from feeling awesome.

Now, Vimium is only approachable to English-speaking people. I think that translation support should be added. I don't like the idea of Crowdin, as it is proprietary software. Just a pot file is necessary for us to submit translations. But if you prefer a GUI webpage to translate, I suggest the free software website [Weblate](https://weblate.org/). I can work on the Spanish translation and the Esperanto translation if the issue is reopened.
