### ISSUE TITLE
Search Engines doesn't work when use "Use google to search the current site you're on" 

### ISSUE THREAD

**Issue by crpig** [philc/vimium#1768]
Here is the Custom Search Engine Settings:
# Use google to search the current site you're on
site: javascript:location='http://www.google.com/search?num=100&q=site:'%20+%20escape(location.hostname)%20+%20'%20%S'%20;%20void%200

**Comment by gdh1995** [comment]
`%S` is not a valid term. It may be `%s`?

After adding this line, I failed to use `site`: Vimium tests the query string and refuses every one which is not a valid url.

**Comment by wickles** [comment]
I'm interested in reviving this issue. I also tried this string because it is listed [here on the wiki](https://github.com/philc/vimium/wiki/Search-Engines). Played around with the formatting but could not even get the search to proc via the keyword. Could it be something to do with Chrome having disabled pasting javascript: into the url bar?

**Comment by mimkorn** [comment]
Does not work for me neither, also used the one from wiki.
