### ISSUE TITLE
Link hints handling

### ISSUE THREAD

**Issue by terraqout** [philc/vimium#1769]
I don't like the way selection of links  when using open link feature.
I'll explain with Jira page (which I hate and use everyday):

![jira](https://cloud.githubusercontent.com/assets/1011721/8749070/9d055e94-2ca7-11e5-965f-8eb9ffb878e3.png)

on this page I press f(to call open links) and "sta" to press "start". What I see unexpected:
1. Shortest label should be more preferable
2. Position of word should play role in ranking: 'sta' is for "start", and not for 'inSTAgram'
3. Top-down if rank are equal

I can implement it by myself with ease, but if this would find a relevant answer from community. So let's discuss

**Comment by mrmr1993** [comment]
[This line here](https://github.com/philc/vimium/blob/master/content_scripts/link_hints.coffee#L574) is responsible for sorting, and [this function](https://github.com/philc/vimium/blob/master/content_scripts/link_hints.coffee#L587) is responsible for generating the scores on which we sort.


> 1\. Shortest label should be more preferable

This should be easily handled by changing the sorting code to

```coffee
hintMarkers = hintMarkers[..].sort (a,b) -> b.score - a.score || b.linkText.length - a.linkText.length
```

Can you think of any cases where this wouldn't be the right thing to do? In general, this might be confusing because it doesn't respect the order of hints, but I never use this mode, so I don't know.

> 2\. Position of word should play role in ranking: 'sta' is for "start", and not for 'inSTAgram'

The code for the scores seems to already do this.

> 3\. Top-down if rank are equal

I think the reason this isn't already the case seems to be Chrome's `Array.prototype.sort ` implementation; hints which score equally may be reordered by `sort`, as seems to be happening here. I expect that storing the original index of each hint and also comparing on that will work.

So, my proposed solution is to replace the sorting code with:

```coffee
hintMarker.originalIndex = i for hintMarker, i in hintMarkers
hintMarkers = hintMarkers[..].sort (a,b) -> b.score - a.score || b.linkText.length - a.linkText.length || b.originalIndex - a.originalIndex
```

Thoughts?

**Comment by terraqout** [comment]
I can purpose to add font-size to scoring too.

**Comment by mrmr1993** [comment]
I'm much less of a fan of this idea for a few reasons:
* it involves a `getComputedStyle` hit
* if the clickable element has a low font size (I've seen `font-size: 0px` in the wild before) with a larger size for a decendant containing the text, then we'll penalise the link incorrectly
* when the 'link' is an input, should we care about the font size?
  - moreover, the label for inputs can be taken from a label if one exists; do we need to consider the font size for that too?

I'm also not sure about the length condition either; the initial order will jump around based on length, and the lowest numbers will go to those elements with no `linkText`.

To fix the original issue, I think we should make the simple change to

```coffee
hintMarker.originalIndex = i for hintMarker, i in hintMarkers
hintMarkers = hintMarkers[..].sort (a,b) -> b.score - a.score || b.originalIndex - a.originalIndex
```

It seems as though anything else will cause weirdness that's hard to explain to the user (and hard for them to work out themselves), and I can't see that it adds much benefit.

**Comment by smblott-github** [comment]
> Position of word should play role in ranking: 'sta' is for "start", and not for 'inSTAgram'

This idea is already in `master`: https://github.com/philc/vimium/blob/master/content_scripts/link_hints.coffee#L600 (https://github.com/philc/vimium/commit/5aaed906b94337bb2136d74672e16679ab457c49).

Scoring by length could backfire on news websites (where the links for articles tend to have long texts).

**Comment by smblott-github** [comment]
Just to add, @terraqout, in `master`, `<Enter>` selects the link labelled "1", and `<Tab>-<Enter>` selects the link labelled "2".  I find this easier/quicker to type.
