### ISSUE TITLE
SalesForce "locked" links un-navigatable

### ISSUE THREAD

**Issue by TreyBlancher** [philc/vimium#1784]
I'm not sure this is a bug report or a feature request, though I'm inclined to think it's
the latter.

Sadly I have to use SalesForce for my daily work activities, there's absolutely no way
around it.  SalesForce is laden with nasty Javascript:  hover-over popups, "locked"
links and fields, the various UI design decisions are horrid.

What I mean by "locked links:"  things that appear as links or fields (vimium can
delineate them with the usual 'f' key letter code), but when I press the code to "click"
that link, nothing happens.  These links and fields are designed to be double-clicked
(with a mouse) to "unlock" their control, whether it be a text input field, a dropdown
menu, or some other GUI widget.  It's a terrible UI design, but SFDC seems to be stuck
with it.

Essentially this makes me have to resort to my mouse whenever I want to change these
fields.  It'd be great if I could send a double-click event to the desired field.

**Comment by mrmr1993** [comment]
The actual fix for adding double click should be very simple to do. Unfortunately, we're in a position where we're loathe to add new commands at the moment because of the state of the help dialog (#1269 for some discussion).

There are some suggestions about for how we could stop this being a problem (#1269, #1280 and #1312 for some examples). If you have any other suggestions and/or would be willing to submit a PR to improve the situation, that would be much appreciated. Sorry I haven't had time to work on these things to date.

**Comment by TreyBlancher** [comment]
Matthew,

I would think a counter code (e.g. "2f <code>" for double click, "3f
<code>" for triple, etc.) would make sense, though it might get absurd
if someone types e.g. a phone number in accidentally, and vimium
dutifully executes millions of clicks on whatever link.

That was my first thought on getting it working.

Trey

**Comment by mrmr1993** [comment]
> I would think a counter code (e.g. "2f \<code\>" for double click, "3f
\<code\>" for triple, etc.) would make sense

Thanks @TreyBlancher. The problem with this, and what I was eluding to, is considering how we would *convey* this to a user. 

This also has the problem that we might use the binding for something more widely useful, such as clicking a known number of links (consider `3f<some keys><some keys><some keys>` vs `<a-f><some keys><some keys><some keys><esc>` for a repetetive workflow), and furthermore that it could complicate our mapping system to make it remappable.

Personally, I would rather have `gf<something>` for the various link hint types (although first we will have to overcome the need for `gf`), and then users are free -- as usual -- to remap these as they find convenient to their workflow. Or even to not map them at all, leaving it to users who find them useful to give them a home. But this still requires the same discussion into how we could readily show a user which commands are available and their associated keys, so that we can continue to add commands at all.

**Comment by rrsahutwo** [comment]
EXPERT Packers is a well well-known packaging and movers helping people in moving to and from most of the significant places like Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , Bangalore , and so on. We are devoted packers movers Bangalore to create your moving simple, secure, relaxed and affordable. You can have the best moving alternatives at affordable expenses.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Relocating from one position to other remote places is a difficult and stressful time. You may have a lot of doubts and fears of bad happenings while traveling with your useful factors. When moving from your house, people have to face a variety of unwanted troublesome and hectic issues. For the relaxed moving, a lot of factors have to be done by expert packers & movers in Bangalore . 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
The process of relaxed moving or moving consist of appropriate packaging of different items, secure running, moving, unloading, unpacking, puting in order and so on. For most of you, all these necessary projects are very difficult to be handled by your own and can create you stressed and uncomfortable. The whole process of moving from one position to another also takes a lengthy time. If you want to get everything done well, you need to take help of expert packers and movers at EXPERT Packers.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
EXPERT Packers takes all features and precautions to end your all doubts, fears and issues Expert to all your moving needs. We are knowledgeable and devoted packers & movers in Bangalore and are helpful to the people from across the nation. If you do the choosing of expert packers and movers in Bangalore , you can travel with confidence even to the remotest locations. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
