### ISSUE TITLE
Add ide.c9.io to default exclusion rules

### ISSUE THREAD

**Issue by nightwing** [philc/vimium#1789]
Currently vimium completely breaks vim keyboard bindings on cloud9, and people often report issues to cloud9 about esc key not working.
Would you accept a pull request changing `lib/settings.coffee` to

```diff
@@ -124,8 +124,9 @@ Settings =
     # Default exclusion rules.
     exclusionRules:
       [
-        # Disable Vimium on Gmail.
-        { pattern: "https?://mail.google.com/*", passKeys: "" }
+        # Disable Vimium on Gmail and cloud9.
+        { pattern: "https?://mail.google.com/*", passKeys: "" },
+        { pattern: "https?://ide.c9.io/*", passKeys: "" }
       ]
 
     # NOTE: If a page contains both a single angle-bracket link and a double angle-bracket link, then in
```
?

A better solution might be to check for some attribute on textarea to not intercept keys on textareas belonging to Ace or Codemirror.

**Comment by mrmr1993** [comment]
A while ago I created #1372 to address this and related issues (#1463, #1741 and #1285, to name a few). It works by allowing complex keys in passkeys by separating them with spaces (eg. `hjkl <c-[> <a-f>`); with a rebase , it should be possible to merge that and simply set `<esc>` as a passkey.

I'd be concerned about changing the default, since it will make Vimium 'stop working' on the site completely, which some users may not expect. If the PR I mentioned provides a reasonable solution, perhaps we should default an exclusion for `<esc>`, which would prove far less disruptive.

> check for some attribute on textarea to not intercept keys on textareas belonging to Ace or Codemirror.

I'd personally rather not see site-specific code in the codebase. However, it's nice to have this to fall back on if our other options aren't flexible enough.
