### ISSUE TITLE
Scrolling not working on google play music

### ISSUE THREAD

**Issue by jck** [philc/vimium#1795]
https://play.google.com/music/listen#/now

**Comment by smblott-github** [comment]
Hmm.  Correct.

And a "Vimium Tap" on the mouse doesn't even solve the issue.

**Comment by dragon788** [comment]
Google really likes to take over the keyboard for their own shortcuts. Try disabling Vimium and pressing ? and see if Google will show you the secrets of their shortcuts. (This works in Inbox and a few other places).

**Comment by mrmr1993** [comment]
There seem to be a couple of things at play here:
* the scrolling element has a 0-height ancestor
  - this would have been solved by a "Vimium Tap" normally.
* the actual element that scrolls is in a shadow DOM hierarchy, which we don't traverse when looking for an element to scroll.
  - the currently focused element may be nested in a shadow DOM, but present in the main DOM, and so we would have to discover where by examining the `<content>` tags in the shadow DOM (which is, in general, non-trivial because of the `select` attribute).
  - the currently focused element may also be in a shadow DOM along with its scrolling parent, so we will have to track `DOMActivate` events across shadow DOMs.

**Comment by mrmr1993** [comment]
> * the actual element that scrolls is in a shadow DOM hierarchy, which we don't traverse when looking for an element to scroll.

I've opened PR #1803 to address this. With that, scrolling should work after clicking the scrolling area.

**Comment by smblott-github** [comment]
#1803 is merged.  It mostly fixes this issue, but still requires a Vimium tap.  It'll be in 1.52, which will probably be released soon.
