### ISSUE TITLE
Tweaking vomnibar custom search engine completion UX?

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1802]
Here are a couple of pre-release UX issues we could think about for the vomnibar.

1. There is currently no proper way to explicitly disable completion.  Do we need one?

    (A hokey workaround is for the user to use custom search engine URLs which don't match our built-in regexps -- e.g. by adding bogus parameters.)

2. There is currently a delay of up to 200ms before we launch a completion request (up to 100ms from the vomnibar front end, then a guaranteed 100ms in the back end).  The idea is to avoid sending completion requests if the user is still typing.  However, the delay can make completion feel sluggish compared to the omnibox.

(Also on the pre-release to-do list: check that the relevant section of the wiki is up to date and well written.)

**Comment by mrmr1993** [comment]
Sorry for the slow reply, missed the email for this.

> no proper way to explicitly disable completion. Do we need one?

I don't feel strongly about this.

> There is currently a delay of up to 200ms before we launch a completion request (up to 100ms from the vomnibar front end, then a guaranteed 100ms in the back end).

* Looks to me like there's a strict 150ms delay in the front end for all omni mode queries
  - this covers all completions
  - exception: when the entire query is a keyword, there is no delay. (Or, at least, I *think* there's no delay; the code is hard to read.)
* There's then another strict 100ms delay in `CompetionSearch`
  - this would seem to be redundant if we're already delaying by 150ms in the front end.
  - we're wasting 100ms of the front end's 150ms in a delay, so we only have 50ms to make the request and get the information to the front end before it's sent another request and invalidated the ID of the last one.

I think we should
* drop the delay in `CompletionSearch` (perhaps just change it to 0 to keep the change small and revertable).
  - I've implemented this, with a brief commit message to explain, in ad93e1cb2e74a40af8149c501d7a8026eb18efdd.
* use the delay in the front end to block the sending of rapid multiple requests, but send the first request immediately
  - this means that the 150ms delay only applies when we have a request being processed, and not for every update indiscriminately.
  - I've implemented this, and renamed a variable for clarity, in a5a978ed3da9b0bda19f86efce196e916b69310d.

I've also just discovered that, if you stop typing during the front end 150ms delay, you won't ever get a match for your full query, since that request is never sent. This might be more of an issue now we're using web completions, and should probably be fixed. I'll write a fix for it tomorrow if nobody beats me to it.

**Comment by smblott-github** [comment]
(You're right; the front-end delay is 150 and the back-end delay is 100.)

You may be mistaken, @mrmr1993.  The front-end delay is not "strict".  It is between 0ms and 150ms.  The first keystroke starts a timer, subsequent keystrokes within 150ms are ignored.  When the timer expires, the vomnibar is updated.  See [here](https://github.com/philc/vimium/blob/master/pages/vomnibar.coffee#L231).  This approach and this logic is not new.  The delay is throttling vomnibar updates while the user is typing, but not preventing them.  (As you observe, there is no delay for certain custom search engine cases.)

Since the front-end delay can be as little as 0ms (even if the user is still typing), we need the back-end delay to prevent unnecessary completion requests.  This back-end delay is the only new thing here.

> I've also just discovered that, if you stop typing during the front end 150ms delay,

I suspect you may have misread the code, here.

**Comment by mrmr1993** [comment]
> You may be mistaken, @mrmr1993.

I may well be, sorry. The only reading I can get out of the code is:
* typing causes an `input` event,
* the `input` event triggers `VomnibarUI::onInput`.
* `if 0 <= @selection and @completions[@selection].customSearchMode and not @customSearchMode` runs its code only the first time after getting suggestions for a custom search engine
  - so `updateSynchronously` is `undefined` all other times
  - we'll ignore this one time, and just say it's `undefined` 'always', for ease
* `VomnibarUI::update updateSynchronously` is called, and `updateSynchronously` is set to `false`
* hence, we always hit the `else if not @updateTimer?`
* the call to `@updateCompletions` is in the `Utils.setTimeout` callback, and thus *always delayed by 150ms*.

> > I've also just discovered that, if you stop typing during the front end 150ms delay,

> I suspect you may have misread the code, here.

It's an issue with a5a978ee, not `master`, sorry. I'll update that branch later to squash the issue.

**Comment by smblott-github** [comment]
> the call to @updateCompletions is in the Utils.setTimeout callback, and thus always delayed by 150ms

Unless there's already a timer set (note `if not @updateTimer?`); in which case we do nothing at all and let the timer trigger an update whenever it happens to expire (which could be anything from 0ms to 150ms).

Also, there's a trick here.  We don't pick up the actual query text until the timer expires.

(This is pretty old logic -- several years, at least.)

**Comment by mrmr1993** [comment]
> Unless there's already a timer set

Indeed. So the behaviour is right when the user is already typing, but we impose a delay of 150ms for no reason when they start typing. If we want the Vomnibar to seem more responsive, we would do well not to apply this delay every time.
