### ISSUE TITLE
Feature request: scroll top, scroll bottom, center

### ISSUE THREAD

**Issue by s-kramer** [philc/vimium#1836]
I'm really missing vim's normal mode zt (scroll top), zz (center) and zb (scroll bottom) key mappings. The reference point could be the current focus or the last search match. Would it be possible to implement this feature in vimium?

**Comment by nfischer** [comment]
I like the idea of being able to focus around the last search match. To me, this would be more useful than pressing `nN` (jump to next match, then back to the one I was at). Some concerns I have:

 - In vim, using `zz` when at the bottom of the file lets you scroll past the end of the file. In chrome, I don't think this would be possible. What would be useful behavior in this case for Vimium?
 - In vim, you always have the notion of a cursor, and `zz` scrolls such that the center of the window is now around the cursor. In Vimium, do we have the same notion of a cursor? And if we use last search match as a substitute, what happens when there is no last search match?

**Comment by smblott-github** [comment]
The use case for this would be when a "find" ends up selecting text at the bottom of the viewport, and you can't see the following context, right?  In this case, why not just use `d`?  Granted, it's not quite the same thing.  But, since there normally is no notion of a cursor in a web browser, the use case in Vimium doesn't seem as compelling as it is in vim, say.

**Comment by s-kramer** [comment]
I was thinking only about the results of find command. 
* I didn't consider scrolling past the page. I believe scrolling the page top down would be a proper solution. 
* All I had in mind was making the currently highlighted search result appear on the top, middle or the bottom of the screen using zt,zz,zb respectively. I believe that there's no point in modifying the insert mode to a similar one as in Firefox's Vimperator plugin.

The use case I had in mind was being able to find the result of the find command on the screen when the page is really colorful and it's hard to find the yellow highlight, but when I think about it now I believe that we could benefit from this feature even with plain white pages - the user wouldn't have to search the whole page for the highlight, he could just put the result in the expected place of the screen.

**Comment by nfischer** [comment]
The use case for me is as follows:

Search for 'is' (or something very common) on a webpage (such as this one). Press `n` to jump to each match. It can be hard to see which 'is' is highlighted. If we can press `zz` to adjust the window to be centered around the match, that would be helpful in finding the match on the page (because the orange highlight can be hard to see).

I'm concerned with the edge cases though, as I mentioned above. And a little concerned that `zz` in vim doesn't exactly translate. Maybe this could be an option for `n`'s behavior, that the user could select or not select via a checkbox in the settings?

**Comment by rajeevksahu** [comment]
We have a sufficient encounter to deal with all the types of hurdles. Backed by all the relevant automobiles, equipment and devoted employees, we are committed to take you to your new targeted position. Our experts are geared up to help you in your need. We do not worry about plenty of time as we are prepared to assist you 24 hours. You can get in touch with our experts for alternatives of packaging and moving Nagpur and any other places of the nation.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We provide personalized alternatives fit to every type of needs. Different types of the automobiles we have create us able to do so. We comprehend the value of our clients’ cash and so we recommend the best suited strategy for to meet their need. We do not force our clients to seek the services of a automobile larger than what they need to fulfill their need. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
We try to handle their need in the minimum possible price range. Our strength reflects in our new and well handled automobiles which are strong enough to take you and your items to the remotest position. Because of the well handled automobiles and our efficient alternatives, we become the leading packers & movers in Nagpur. We have already curved a niche in the market. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
Our unique group of experienced mechanics creates Expertular observation of the automobiles to make sure the fitness of them. This gives us confidence to provide our countrywide clients and creates us able build a believe in on our clients. If you are also going to seek the services of the packers and movers in Nagpur, you can with confidence seek the services of our alternatives which will make sure your protection during your trip. We will fulfill your need with the best strategy and management.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by nkgm** [comment]
I believe `caret mode` also begs the implementation of `zz`, `zt`, and `zb`, as well as every other vimium operation whose vim equivalent would reposition the caret in vim (search, n/N, visual mode). As for not being able to scroll past the end of the page, it's not such a nasty edge case, and there doesn't need to be full parity with vim - just needs to come as close as it makes sense.

**Comment by yangmillstheory** [comment]
I use this all the time in `vim`, would love this so much here!

**Comment by dmocek** [comment]
I would also like to see this feature implemented.  Why?  Because I use zz all the time in other programs with Vi keybindings.  I'd rather not have to learn to use d (which really should be Ctrl-d to be like default Vi) to go up 1/2 page to "center this text in the middle of the page" only while using Vimium and zz everywhere else.

As far as what would be the behavior if the text is at the bottom of the page?  Scroll up as far as you can go, the same as if you hit 'd' while at the bottom of the page.

Regarding not having a cursor?  Just use it with search.

**Comment by mcp292** [comment]
2022 and I still want to see this implemented. 

Simple use case:
1. Reading through docs.
2. Search for keyword.
3. `n` to header of section.
4. `zt` to bring that header to the top of the page. 

I wouldn't mind having to enter `visual` or `caret` mode first and then issuing `zt`.

**Comment by eggbean** [comment]
I just want to state my interest in this issue, which was closed to lack of interest. For me, it is the only feature I would like to see added to Vimium, as well as the ability to move tabs to the previous window.
