### ISSUE TITLE
Can Vimium be more friendly to users of Chrome Dev Tools?

### ISSUE THREAD

**Issue by philc** [philc/vimium#1838]
I haven't done much research on this, but when I'm using the dev tools to work on non-extension web apps, it's annoying that Vimium adds many entries to the network requests tab.

Workarounds for this that I'm familiar with are to filter out requests from extensions by setting `-scheme:chrome-extension` to your request filter, or using Incognito mode for development. Both of those are annoying when you're just having a one-off look at the network tab.

This review on the Chrome store resonated with me:

> Everything great, love it except that js files are not concatenated, it pollutes network log with 9 files for each frame.

The ideal solution is probably for Chrome to have a persistent checkbox to "hide requests from extensions" in the dev console. Barring that, any other ideas for ways to improve the situation? What do you think about concatenating JS in production builds?

**Comment by mrmr1993** [comment]
> What do you think about concatenating JS in production builds?

`coffeescript --join` seems up to the job, and sounds like a good idea. Obviously, per directory would be most sensible, so content scripts aren't attached to background scripts, etc.

If we're going to concatenate scripts, it might also be worth offering a cake command (`cake buildmap`?) that uses coffeescript's `--map`, so there's the option to debug through the individual .coffee files in the Chrome console instead of a mass of concatenated js.

**Comment by smblott-github** [comment]
`coffee --join` ... "concatenate the source CoffeeScript before compiling".

That would put all of the per-file globals in the same name space.

This only matters for content scripts.  It would be enough to `cat` the `.js` files together (in the correct order), I think.  Which would also speed up page load times a bit.

For development, error messages which refer to the original file are helpful.  So we would probably need two build targets (and manifests?).  Which might become confusing.

**Comment by mrmr1993** [comment]
> That would put all of the per-file globals in the same name space.

My mistake, I misspoke there.

> This only matters for content scripts.

Looking in the network tab in dev tools, it seems to only show requests from the `<iframe>`s we inject and the `XMLHttpRequest` we use to style them, not the content scripts. So, the things we can do to reduce the number of requests are:

1. find a way to only inject the HUD into the top frame, like we already do with the Vomnibar,
2. concatenate all the JS to be loaded into each frame,
3. inject the CSS directly into the iframe documents at build time, and
4. add another content script containing `vimium.css` as a string, so that `ui_component.js` doesn't need to use an `XMLHttpRequest`.

To my mind, these could be easily approached by

1. Creating a `MessageChannel` from each frame to the top frame, and marshalling the HUD commands/responses through it.
2. Using [mapcat](https://github.com/edc/mapcat), which would allow us to trace through the coffeescript sources of the concatenated js file in Chrome's dev tools.
3. Using [EJS](http://www.embeddedjs.com/) or a similar templating language for the `UIComponent` HTML documents.
4. Using [EJS](http://www.embeddedjs.com/) file to read, JSON encode, and inline the CSS as a global variable.

Are these changes we could and should consider making?

**Comment by smblott-github** [comment]
I'm not convinced that @philc's concern is sufficiently significant to warrant any substantial re-working of either the build setup or the runtime system -- sorry Phil.  Most users never look at the dev tools.  Those that use the dev tools regularly probably want a separate Chrome profile anyway -- because they probably need to be isolated from *all* extensions.  Which leaves us with a minor irritation for a small number of occasional dev-tools users -- which would be worth fixing only if we can do so at almost zero cost.

**Comment by gdh1995** [comment]
> zero cost
CSS text may be sent using Chrome extension port, and iframes, too. This seems to be the only method.

**Comment by mrmr1993** [comment]
> and iframes, too

There are security reasons why it's a good idea to have the Vomnibar frame with the extension as its origin: otherwise a malicious website can

* read arbitrary history/bookmarks/open tabs,
* open arbitrary URLs, and
* probably run arbitrary JS on arbitrary urls (opening the url and a `javascript:` bookmaklet in fast succession).

I suggest not messing with the iframes.

**Comment by gdh1995** [comment]
Yes, you are right.

**Comment by KnutHelland** [comment]
Do you know who is using this extension? I think its userbase is over-represented by developers, and probably a lot of them are web developers.

I really like to have Vimium enabled while developing, because I'll then always get reminded if I've created a button/link and forgot to give it `role="button"` or `role="link"`. For that reason only, I would really like if _all_ web developers used Vimium. It would make web applications more accessible.

Would we have an discussion on it if I made an merge request for it, or would that just be wasted time?

**Comment by es6Test** [comment]
+1 this makes this great plugin frustrating for devs.

**Comment by smblott-github** [comment]
#2033 looks like the simple way to address this.

**Comment by es6Test** [comment]
How do we apply these fixes?

**Comment by es6Test** [comment]
1.56 still has this issue

**Comment by smblott-github** [comment]
@es6Test... Do you still have this issue when you disable Vimium on the page (via the popup).

**Comment by kyranjamie** [comment]
Came here to report same thing. 

Understand the mechanism of delivering the functionality is the load the js, but a single concatenated file would keep things a lot cleaner than:

![image](https://cloud.githubusercontent.com/assets/1618764/22300062/9b4bf086-e326-11e6-89b5-fb9672f5ee04.png)

**Comment by philc** [comment]
Chrome made the situation better for us. See #2238.
