### ISSUE TITLE
When opening a link with link-hint mode, add a delay before listening to new actions

### ISSUE THREAD

**Issue by tkumse** [philc/vimium#1842]
The link-hint mode is a good feature which lets the user save time. However, as this feature is implemented for now it steals time instead. The user has to wait for every letter that is pressed to see if the link has started loading. Otherwise, the user may press a key that represents unwanted behavior at this point, such as: closing the tab; opening a new one; going to the clipboard URL, and the list continues.

By adding a small delay for say 0.5 seconds, or even letting the user set this delay itself, this feature may become much better.

**Comment by smblott-github** [comment]
Thanks, @tkumse.

Are you using filtered mode (hints are numbers) or normal mode (hints are letters)?

In the former, there is already a 200ms delay.  In the latter there's no delay (because the user has to know what they're typing anyway).

Perhaps we could look at this again.

- In normal mode (no delay currently), if the user mistypes a non-hint key, they're immediately vulnerable to inadvertently launching an unintended Vimium command.

- In filtered mode, 200ms isn't very long for the user to notice that a link has been selected and stop typing.

    In this case, it might be better to reset the timer (possibly with a shorter delay) if the user types within the 200ms window. E.g., we could wait for a gap of 150ms (say) between keystrokes, and for a minimum of 200ms.

**Comment by tkumse** [comment]
Yes, I'm using filtered mode and your suggestion to reset the timer when keys are pressed is the perfect solution in my opinion.
