### ISSUE TITLE
f function

### ISSUE THREAD

**Issue by shoaly** [philc/vimium#1850]
hello, I would like to give a idea, to make f key more fast when open links

now i realize when f key are pressed, the hint keys are random. is it possible to compare all links with previous page we opened, and give exactly same key hints as the last pages. let me explain why.

I know there are  "[" "]" bind for visit next page and previous page . if we make the above function enabled, when i press "f", the current "Next Page" is marked as "PH" , when I go to the next page, it remains the "PH", so i don't need to look at the hint, just type f - PH , I can go to the 3rd page.

**Comment by smblott-github** [comment]
Not answering your question, @shoaly, but... Have you tried using filtered mode for link hints (by selecting `Use the link's name and numbers for link-hint filtering` on the options page.)?  Far superior, in my view, and gives you predictable text to type.

I've wondered about your idea before.  It'd be problematic is the scroll position was different from visit to visit, and we'd have remember a lot of state (the hints assigned would have to be remembered).  And then, we'd have to know how to identify DOM nodes from visit to visit.  Not sure it's so easy.  Filtered mode is better.

**Comment by shoaly** [comment]
thanks reply!

i did not notice that option till you told me. and i tried.  :) thanks.   

However number area is not as good as the main "ASDFGHJKL" area.

If dig into DOM is not a minutes-work. how about apply a simple version of this idea above, my core idea is try to make hints not that random. let me explain by a example.

Again when I press f, the "Next Page" is marked as "PH" , than I press "PH", we only save the link of the PH(It's dom, may be speed up if the links has classes, ids or attribues, we can filter it more fast I think) , on the "Next Page" , if we found the same links, we maked it as f, so I can use double "f" to quickly go "Next Page" , it is like a runtime redo function, how do you think about it?

**Comment by smblott-github** [comment]
> However number area is not as good as the main "ASDFGHJKL" area.

Opinion... Filtered hints are superior because you can ignore the numbers and just type the link's text.  That text is not random, so you know what you need to type before hitting `f`.  And, Vimium scores links, so if you start typing with the start of the link's text, then Vimium very quickly ranks that link highest, and `Enter` activates it.  But that's off topic.

> we only save the link of the PH

We could, but many clickable things don't have links, and -- even if they do -- then the "Next Page" link, say, is different on different pages (even on the same site, e.g. vbulletin).

Perhaps we could sort based on (a hash, perhaps) of the link's text (or perhaps even their CSS), that would work on some pages; but not on pages with variable numbers of links in the viewport.

**Comment by smblott-github** [comment]
(Still off topic, @shoaly.  To use your example, with filtered hints, `fne<Enter>` will **almost certainly** select your "**Ne**xt Page" link.  And you know what to type before hitting `f`. -- I'm on my soap box, here.  I'd love to see filtered hints as the default.)

**Comment by shoaly** [comment]
Thanks again, no doubt , this is your apps, l know your point. 

From your example, I understand how easy to navigate to "Next page" By press "fne"
unfortunately I am a Chinese, a lot of Chinese website use "上一页" as previous page and "下一页" as Next Page, it is more slow if I type "f下" when turning on filtered hints.  

Again this is your App, so all by your call.. if you don't agree with me, that's fine. 

very handy app, I use it almost everyday, thanks your app

**Comment by smblott-github** [comment]
Hmm.  I can't think of way of doing this that would work well in the general case.  I might be possible to "prioritise" the link which would be chosen by `]]`, but that still wouldn't give a predictable hint.

**Comment by rrsahuone** [comment]
Reliable Companies usually follow transparent company strategy to achieve highest possible client care and best provides in price range. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
Due to our unexpected stage of solutions, we are able to establish ourselves as most prominent support agency today.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Undoubtedly, packers movers Bangalore has created moving procedure simpler than it was regarded in previous. Now the problem comes how to get the most effective provides from certified moving and shifting Companies in Bangalore . If you search on the internet then it is simple to get cope but getting reliable protection is very tough today. Here companies like us help you.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
We record you most effective or best packers and movers in Bangalore to whom you can get in touch with directly. Besides, we provide you with estimates from most popular and reliable names in product packaging moving industry. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by smblott-github** [comment]
Move to #2083.
