### ISSUE TITLE
YouTube controls won't hide if a video is opened fullscreen by Vimium

### ISSUE THREAD

**Issue by nfischer** [philc/vimium#1857]
To me, this looks like a bug in the behavior of Vimium on YouTube (although this may not be site-specific to YouTube). I've documented the steps one would do with a mouse, and the resulting behavior, as well as the steps I personally do with Vimium and the results from that.
- Chromium version: `43.0.2357.130 (Developer Build) Ubuntu 14.10 (64-bit)`
- Vimium version: `1.53` from the Chrome Web Store
### Behavior when using a mouse
- Go to any YouTube video and begin watching it
- As it's playing, mouse over to the bottom right-hand corner and click the "fullscreen" button. YouTube will now be fullscreen
- Move the mouse slightly (YouTube seems to need some sort of mouse movement here) and wait a few seconds
- Observe that the play, volume, settings, and "exit fullscreen" buttons disappear (until you move the mouse again, of course)
### Behavior when using Vimium
- Go to any\* YouTube video and begin watching it
- As it's playing, use the `f` command to click the  "fullscreen" button. YouTube will now be fullscreen
- Observe that the play, volume, settings, and "exit fullscreen" buttons will **not** disappear (even if you move the mouse a bit, as was necessary above)
- This is undesirable, since the controls will block part of the video unless I do the workaround I found (see below)
### Desired behavior (when using Vimium)
- Same steps as above, but once YouTube goes fullscreen, but one of two things should happen:
  - Wait a few seconds and the controls will disappear, or
  - Move the mouse slightly, then wait a few seconds, and the controls will disappear
### The Workaround

If you open fullscreen using Vimium and then move the mouse over the "exit fullscreen" button (don't click) and then move it off, the controls will then disappear after a few seconds (which resembles what YouTube would normally do).

_I haven't tested this on *every_ possible video, but I've noticed it on many. I can verify that the bug persists on BlenderFoundation's "Big Buck Bunny" video, however (https://www.youtube.com/watch?v=aqz-KE-bpKQ).

**Comment by mrmr1993** [comment]
This issue regularly annoys me too. To my knowledge:

This occurs because Vimium never simulates `mouseout` events (#1189). Consider that clicking the button with the mouse and leaving the pointer over the controls has the same effect. Moving the mouse over and then off the controls (so a `mouseout` event is triggered) will hide the controls as you would expect, since the controls hide on the `mouseout` event.

I created PR #1032 to expose functionality around this through Vimium (notably the `LinkHints.unhoverLast` command would allow you to hide the YouTube controls at will). This was and is my preferred solution, despite the obvious command zoo (#1269) objection.

> Move the mouse slightly, then wait a few seconds, and the controls will disappear

We can always add an event listener to `mouseover` that sends a `mouseout` event to our previously hovered element. My PR #1819 does this for our simulated `mouseover`s; it is trivial to adapt it to do this for all `mouseover`s. **However**, this will have the effect that moving the mouse in the window at all (eg. nudging the mouse, the element under the mouse is scrolled, the window is moved under the mouse by the WM, etc.) will close dropdown menus etc., which seems undesirable.

**Comment by nfischer** [comment]
@mrmr1993 That sounds like it could definitely be behind the issue. I like the idea of #1032 a lot, since to me hovering and clicking are different things. And I could see it being confusing if a hover persists after a click somewhere else.

Would you be able to rebase your PR onto master so that I can test it out? I think this idea seems like it's worth pursuing

**Comment by nfischer** [comment]
So I got the chance to try out your code. I was able to get `zf` working (hover over link hints), but I couldn't get `zF` working (unhoverLast). Here's the mappings I'm using:

```
map zf LinkHints.activateModeToHover
map zF LinkHints.unhoverLast
```

Anything I should change to get this to work?

**Comment by nfischer** [comment]
@mrmr1993 Pinging this again to make sure I have my setup correct for the mappings, since this doesn't seem to actually solve the problem right now. Thanks!

**Comment by mrmr1993** [comment]
Sorry for the slow reply @nfischer. I screwed up the rebase of #1032; the new version I've just pushed should work correctly.

**Comment by rrsahutwo** [comment]
We provide you our best group to deal with your entire perform, so you do not have any need to perform all alone. We are loyal and diligent. Our company is well-known and well known for our loyalty, ideal perform, effective group and truthful associates. Our organization is one of the top companies. Packing Moving Bangalore becomes really simple with our well effective group.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Our perform do not finished after product packaging and moving it. We unload it and after it, we unpacked it too. No one of our group will charge and additional from you. You just have to pay discussed expenses, and all the required solutions will be paid to you. Our group is knowledgeable, experienced and watchful for everything they do. They done their job professionally and never harm your products while moving and moving it.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
Bangalore packers and movers provide outstanding support on plenty of time when customers need it. Our organization provides product packaging and moving with stability, punctuality and Professional. We have created a well-known identity in the market with our effort and truthful nature. Our emerged identity provides a best remedy for your requirements

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Bangalore is complete of various industries, solutions and amenities that create life simple and practical. Due to these solutions and amenities, there are a large variety of the residents and sufficient residences, building, companies and workplaces and so on. In this series, in order to fulfill a aspect of various specifications and necessities of these individuals living here, Care India Packers, a major product packaging and movers comes up to help them. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by miraxxx** [comment]
Hi @mrmr1993 
Does the mappings still work? 
map zf LinkHints.activateModeToHover
map zF LinkHints.unhoverLast

I can't get them working on any websites, 
http://www.imdb.com/
for example

**Comment by nfischer** [comment]
I forgot to follow up (sorry, got distracted with other projects), but I wasn't able to figure out the mappings either. As best I can remember, I used the same mappings @miraxxx mentions, but saw no change in behavior.

**Comment by mrmr1993** [comment]
@VladTerin @nfischer #1032 merges cleanly onto current master for me, and works correctly with
map zF LinkHints.unhoverLast
map zf LinkHints.activateModeToHover

The mappings *won't* work in either current master or the webstore version, since that PR hasn't been accepted. I was just clarifying before that code for a solution exists among the PRs.

**Comment by nfischer** [comment]
@mrmr1993 I was trying it with that PR and didn't see results. I will try again today and get back to you

**Comment by nfischer** [comment]
@mrmr1993 sorry for the delay. I finally tried this out (I copy-pasted the configs you wrote above).

`zf` seems to work. `zF` doesn't seem to do anything. The way I'm testing this is on the same youtube video. `zf` lets me hover over the youtube controls, making them appear on the screen. `zF` however does not appear to unhover.

If I do another `zf` command on something else (i.e. a video suggestion on the side), then this seems to unhover from the video controls. This does not help my situation with fullscreen, however, because there are no suitable elements to divert the focus to.

**Comment by maiermic** [comment]
Another workaround:

1. `i` Enter insert mode (Vimium's shortcut)
2. `f` open video fullscreen (Youtube's shortcut, video has to be focused)
3. `Esc` exit fullscreen (Youtube's shortcut)
4. `Esc` Enter visual mode (Vimium's shortcut)

**Comment by smblott-github** [comment]
And another workaround...

With:

    map <c-]> passNextKey

Its `<c-]>` `f`.

**Comment by nfischer** [comment]
Looks like the workarounds aren't needed. My guess is that YouTube changed something (unless it was a Vimium change I missed). But using the `f` command to click the fullscreen button always works as desired.
