### ISSUE TITLE
Feature Request - Adjust zoom/fontsize via keypress

### ISSUE THREAD

**Issue by idvorkin** [philc/vimium#1866]
Being able to adjust font size via key press is super handy. There is currently a [vim script](https://github.com/drmikehenry/vim-fontsize) that has this behavior, and the script gives a good precedent.  The script uses the following keybindings:

```
\\+ => Zoom Bigger
\\++ => Zoom 2x Bigger 
\\+++ => Zoom 3x Bigger 
(etc)
\\- => Zoom Smaller
\\-- => Zoom 2x Smaller
\\---- => Zoom 3x Smaller 
(etc)
```

I suspect many users would find this a helpful functionality.

**Comment by friday** [comment]
Changing text size isn't possible because it's defined by a set of absolute or relative measures defined by the developer(s). But you can zoom, which changes the size of all content including text. Ctrl or cmd + and - does this. You can probably remap them outside of vimium, but not to single keys (so it would still be ctrl + something).

Trying to do it with javascript would probably break designs. CSS transforms gives you larger viewport size (so you get vertical and horizontal scrollbars). Meta viewport can't be changed after the page loads.

**Comment by mrmr1993** [comment]
There seems to be a zoom API for Chrome extensions [here](https://developer.chrome.com/extensions/tabs#method-setZoomSettings), does that fit the bill?

**Comment by friday** [comment]
I missed that one. Looks good to me. "These settings are reset to defaults upon navigating the tab." could be a problem, but I'm not sure how to interpret "navigating".

**Comment by idvorkin** [comment]
:(

**Comment by alphaCTzo7G** [comment]
Yeah.. I would love to see something like a zi or zo to zoom in and out without having to use the cntrl + or control - chrome keys. A lot of things that vimium covers can be done with chrome shortcuts, but the reason we love vimium is because we can do them much faster with a vim like browsing language - Vimium. For example https://github.com/jinzhu/vrome/blob/master/Features.mkd, https://github.com/1995eaton/chromium-vim both support "programmatic" zoom in and zoom out.. using zi and zo.. 

I know this thread started a long time back, but I couldnt find any information about whether this has already been implemented or not. 

I found this cheatsheet online which mentions zi and zo for zooming in and out.. but it doesnt work for me. Tried on multiple computers, by disabling every other plugin, incognito mode etc..

Maybe something that can be implemented in future..

**Comment by lindhe** [comment]
Is this still not possible to implement?

**Comment by smblott-github** [comment]
The implementation for cVim is [here](https://github.com/1995eaton/chromium-vim/blob/2ed2c90944ebf8238d3e30ce282b2a9be3bdcdd1/content_scripts/mappings.js#L306).

I think we should consider doing this; perhaps like this...

    map X zoom in factor=1.1
    map Y zoom out factor = 1.1
    map Z zoom reset

**Comment by aarongaber** [comment]
Zoomba Chrome extension worked for me :)  I used shift+alt+i/o so it wouldn't interfere with the "o" and "i" Vimium key bindings.  https://chrome.google.com/webstore/detail/zoomba/oifpkclgpipladdnaioaehmmccmljblh

**Comment by philc** [comment]
There's some good discussion of the implementation of this feature in PR #2978, but that PR is now out-dated, so if someone wants to take a stab at this, please give it a shot.

**Comment by gdh1995** [comment]
Hello, you may use my customized version of Vimium, `Vimium C` (https://github.com/gdh1995/vimium-c), and it supports `zoomIn`, `zoomOut` and `zoomReset` (`zoom in`, `zoom out` and `zoom reset` also work).

**Comment by leitao** [comment]
sakka-key has this feature (zz and ZZ) and they work pretty fine. I miss this feature in vimium

**Comment by dkotik** [comment]
Would love to see this implemented!

**Comment by alphaprads** [comment]
is it possible to make effect not of ctrl + but instead of actual page zoom that just zooms in on the content where our cursor is or maybe center of page from where we can use hjkl to move around

**Comment by meronogbai** [comment]
@philc TYSM for this! Will you release an update to chrome's extension store soon?

**Comment by UncleSnail** [comment]
> @philc TYSM for this! Will you release an update to chrome's extension store soon?

If you want the "manual overhead" of using a different addon file until it is released to the main extension store, you can clone the project to a local repository and load that extension into the browser, which is covered in [CONTRIBUTING.md](https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source).

I use Firefox, so I also keep a [signed ext file](https://github.com/UncleSnail/vimium/blob/signed-ext/web-ext-artifacts/9af0b42645c4435cbe31-2.1.2.5.xpi), that you can add to Firefox and install normally, with my latest changes before they are in the main addon. This is what I personally run in my browser so I have all the latest features. Anyone who wishes can get it from my fork of Vimium. I generally update it whenever I make a pull request.
