### ISSUE TITLE
"Follow link" has no effect on "not interested" button in the Steam store

### ISSUE THREAD

**Issue by matthew-cline** [philc/vimium#1901]
If you have a Steam account, go to the [Steam store](http://store.steampowered.com/) and view a game, "follow link" will hint the "not interested" button, but using that hint does nothing; you have to click on it with the mouse.

**Comment by PickRelated** [comment]
@matthew-cline maybe this button is not an <a> tag. Some <div> with javascript event listener, I guess. I am not sure this will ever be implemented due to high load. You have to look through all javascript files, take all "click" events and extract div classes from there. It even sound quite complex.
