### ISSUE TITLE
F/f don't work in this page http://www.cs.sjtu.edu.cn/en/ .

### ISSUE THREAD

**Issue by LQYMGT** [philc/vimium#1918]
http://www.cs.sjtu.edu.cn/en/ .

**Comment by smblott-github** [comment]
Weird.

**Comment by gdh1995** [comment]
@smblott-github A weird `scroll` event is triggered everytime `LinkHints` has shown itself on the page above, and then `LinkHints` exits itself.

As for me, it's a bad idea to exit immediately when we scroll the page - something like checking `scroll offset > 30` may be better.

**Comment by mrmr1993** [comment]
Happy new year all! Would it not be better to only register the exit listener after we write our elements? Or have I missed something?

**Comment by gdh1995** [comment]
Hint elements are indeed written into the page, which means `LinkHints::constructor` works.

Oh, I find it's the "News" panel on the right part scrolls continuously
* by changing `<div id="demo" class="Scoll">`'s scrollTop
* and then creates `scroll` events.

So we have to listen `mousewheel` events instead of `scroll`s.

**Comment by smblott-github** [comment]
It turns out that the problem is caused by the scrolling "News" ticker on that page.

Since it's not really essential that we exit on scroll, we could just disable that (see #1952).
