### ISSUE TITLE
Angle brackets (< and >) do not work on AZERTY keyboard

### ISSUE THREAD

**Issue by vgaudard** [philc/vimium#1981]
**Problem description**:
When I press `<<` to move the tab left on a Google search results page, focus is given to the main input, and "<<" is appended to the search string (as it would happen without Vimium)
(The same works for `>>`)
After changing keyboard layout to English (US), the mapping works normally.
I only saw this issue on Google search results, but it probably affects other sites.

**Expected behavior**:
When I press `<<` to move the tab left on any page, the tab moves left.

**Additional information**:
- My keyboard layout is: french (alternative)
- If I remap another key (let's say `e`) to `moveTabLeft`, it works (the tab is moved left when `e` is pressed)
- If I map `<` to another command, it works on most sites, and not in Google search results

**Comment by smblott-github** [comment]
Not a solution, but... Does turning off *Google Instant Predictions* help?

**Comment by vgaudard** [comment]
Yes, it does

**Comment by smblott-github** [comment]
Shout if you disagree, but I think we'll close this, @vgaudard.

There's not a lot we can do.  Vimium intentionally leaks keyboard events unless it *knows* it is going to be handling them.  That way, the underlying page can use them.  And *Google Instant Prediction* is particularly zealous about using them to force you back into the search box.

(I've always suspected that UX folks at Google were on holiday the day GIP was introduced.)

**Comment by mrmr1993** [comment]
> There's not a lot we can do.

When [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=227231) is resolved, the fix for this will come basically for free (using `event.key` on the `keydown` event instead of `event.keyCode` on the `keypress` event).

You might want to star it (and its [unresolved blocking issue](https://code.google.com/p/chromium/issues/detail?id=564678)) to register your interest and help encourage the team along.
