### ISSUE TITLE
Feature Request: Leader key support

### ISSUE THREAD

**Issue by danielyli** [philc/vimium#1986]
For those of us whose muscle memories are accustomed to the leader key (e.g., the comma), supporting a leader key would be a very welcome feature.

**Comment by smblott-github** [comment]
Thanks, @danielyli.  My sense would be that `<leader>` support would be overkill for Vimium.  We have a far fewer commands, and we don't support plugins.  And users can always re-map their keys to achieve whatever mapping best meets their needs.

**Comment by danielyli** [comment]
Alright, that's unfortunate, though very understandable.  Thanks.

**Comment by Aaditay** [comment]
Can we please rethink on this ? Because vimium now have so much options to customize.

**Comment by james-gour** [comment]
Seriously, this should be re-thought @smblott-github.

The value proposition of this feature has nothing to do with the limited number of available commands in vimium.

It has _everything_ to do with consistency of developer workflow across platforms. The leader key is a core feature in vim. Vimium is inspired by vim. Every tool that emulates vim should offer the leader key so that users can simply use all of their bindings that they know and love :).

The mental overhead of having to learn yet another set up arbitrary keymaps, instead of just using my our beloved set from vim makes me hesitant to pick up vimium.
