### ISSUE TITLE
Feature Request: Ignore keys after opening a link via link hinting

### ISSUE THREAD

**Issue by danielyli** [philc/vimium#1988]
Chrome version: 48.0.2564.109 (64-bit)
Vimium version: 1.54
OS version: OS X 10.11.3 El Capitan

I use the link name for hinting; if I type a few more letters of the link than necessary, the extra letters are translated to commands on the new page after the link is opened.  It would be great for Vimium to ignore keys for a fraction of a second immediately after opening a link this way.

**Comment by smblott-github** [comment]
Currently, there is a delay to try to address this problem. I find that doesn't always work. #1950 is an attempt to address this problem. It still requires some tweaking, and agreement as to whether we need a new option.

I'll close this, @danielyli , because we know about the issue and it's already under consideration. Thanks.

**Comment by danielyli** [comment]
Great, @smblott-github, thanks.
