### ISSUE TITLE
Merge the functionality of 'o' key and 'T' key?

### ISSUE THREAD

**Issue by voltecrus** [philc/vimium#1995]
Does it make sense to merge those two keys?

A lot of times I want to go `keyword` and I don't care whether it is in tabs, history, bookmarks, etc.

Currently I have many tabs open and whenever I'd like to go to `keyword` I have to:

1) Search through tabs with 'T'
2) See it it's there, if not open a new tab with the 'o' key

Merging those two keys would half the thinking effort. I understand that it's a huge change and probably wont be implemented any time soon in the core(I'll get working on that pull request), but any hacks/pointers/discussion would be helpful.

Also great work on the project, I love Vimium.

**Comment by smblott-github** [comment]
Thanks, @voltecrus.  Merging these two doesn't seem like a great idea, since it would make `T` pretty weird.  `T` is different to `o` in that an entry is always selected.

Throwing tabs into the `o` omni-completer would be possible.  Although I'm not sure it wouldn't just confuse users.  Currently, with `o` I *know* I'm staying in the same tab.  And with `O` I *know* I will get a new tab.  All of that would become murkier and not predicatble if tabs were thrown into the mix.

The use case you describe is, in part, better served by global marks.  Then, we visit an existing tab if there is one, or create a new tab if necessary.

**Comment by voltecrus** [comment]
Thanks @smblott-github. I think that gives me enough context to research on my own.
