### ISSUE TITLE
How to close tab after creating new tab without using the mouse

### ISSUE THREAD

**Issue by jasjuang** [philc/vimium#2017]
When I type t to create a new tab, the cursor is automatically in the place where usually to type the url. I had to hold the mouse and click somewhere below so the cursor is gone, and then type x to close it. Is there a way to close it without using the mouse?

**Comment by atilford** [comment]
If I understand you correctly, this issue is discussed here: https://github.com/philc/vimium/issues/1515
One solution suggested (that I personally use) is to set the 'New Tab URL' setting under Vimium's Advanced Options to 'pages/blank.html'. You can then use 'x' like normal to close the tab, but it obviously means your new tab page will be blank.
![vimium_newtab](https://cloud.githubusercontent.com/assets/13649625/13341770/6b6662a4-dbf0-11e5-9560-1b09e1e4bd4f.png)

**Comment by jasjuang** [comment]
Yes it is the same issue, and I also just found out the the default key bindings from chrome itself ctrl+w will do the job.
