### ISSUE TITLE
Use more characters when generating link hints

### ISSUE THREAD

**Issue by philc** [philc/vimium#21]
Currently we only use the characters ASDFJKL. We should use more so that it's less likely we need 3 characters to display hints for all links on a page.

**Comment by lydell** [comment]
Almost a decade later my curiosity made me end up here…

We all recognize `asdfjkl` as the good ol' QWERTY home row. Vimium's hint chars start with `sadfjkl`. Wait, what – <strong>sa</strong>fjkl?

Turns out commit b578214f49d65791705d11be58993478a7636a3e not only added a few more chars – it also flipped "a" and "s".

```diff
-var hintCharacters = "asdfjkl";
+var hintCharacters = "sadfjkluewcm";
```

The commit message does not explain this, making it look like a mistake – one that's lasted for nearly 10 years?

I love little history nuggets like this :)
