### ISSUE TITLE
Vimium doesn't show link target after page scroll

### ISSUE THREAD

**Issue by k0pernikus** [philc/vimium#2111]
1. Go to long page so that one has to scroll down to see all the content
2. Scroll up `gg`
3. Press `f` to see link targets
4. Scroll down via Page down
5. Links that now become invisible don't have link target boxes; one has to restart the boxes drawing via `esc` + `f`

Optional: scrolling should also be possible via space and j,d. those letters should IMO not be used for link targets.

**Comment by smblott-github** [comment]
Thanks, @k0pernikus, but this is as much a feature as a bug.  Users usually want to click stuff they can see; that's the important use case.  If we used all of the links on a page, then - in addition to being slower - the hint strings would be *longer* (because there would be more of them), meaning slower to read and type.  And if we added hints as we scrolled, then the hint strings would change (which might be weird).
