### ISSUE TITLE
Does not work with SVG files in Opera Beta

### ISSUE THREAD

**Issue by InOurUrbanSociety** [philc/vimium#2126]
It'd be very nice to be able to scroll SVG files.

Version:	37.0.2178.31 - Opera is up to date
Update stream:	beta
System:	Windows 8.1 64-bit (WoW64)
(chrome://version does not work in Opera Beta, I had to click Menu -> About Opera)

Vimium version 1.54

Haven't tested it in any other chrome-based browser.

A fast test is to go to https://upload.wikimedia.org/wikipedia/commons/9/95/Flag_of_Comecon.svg and type /

Thanks! Vimium looks very nice!

**Comment by smblott-github** [comment]
Thanks, @InOurUrbanSociety.  Doesn't work in Chrome either.

The problem is that that's not a regular web page; `document.documentElement` in an SVG node and `document.body` isn't set.  Vimium is running (e.g. `J` and `K`) work, but we can't scroll the page, and our UI components (e.g. the HUD and Vomnibar) aren't rendered.  And there are no links to follow.

It's not obvious (to me) what we can do about this.

**Comment by InOurUrbanSociety** [comment]
My SVG files have links and my browser has support for them, but I did not know extensions were this dependent on the kind of files loaded by the browser. I understand. Thanks for your kind answer, have a nice week.
