### ISSUE TITLE
Chain actions in custom keybindings?

### ISSUE THREAD

**Issue by pathammer** [philc/vimium#2138]
Is it possible to chain several actions to one custom keybindings?

For example, I want to do:
`map gb duplicateTab goBack`
which hopefully, _go back in new tab_ - would be the equivalent of middle clicking on the back button.

**Comment by smblott-github** [comment]
Thanks @pathammer....

Not currently.  And I don't imagine such a feature becoming a priority.  The problem is that it might be more complicated to realise than you might imagine.  Vimium is JavaScript, and many Vimium commands execute asynchronously - in some cases with several asynchronous messages between JS contexts.  There's no single point where we know that a command has completed.

(Personally, I'm also not sure that the feature would be of sufficiently general interested, too.)

**Comment by pathammer** [comment]
That explanation totally makes sense for prohibiting chaining actions. Maybe I can add the action myself *get back url and open in new tab*? Can you estimate the difficulty?
