### ISSUE TITLE
FR: need a toggle for link hints always on

### ISSUE THREAD

**Issue by nameanyone** [philc/vimium#2197]
Sometimes I'd like link hints to be always present, i.e. appear immediately when the page is loaded, without having to hit f.

**Comment by leoj3n** [comment]
It might be interesting to make `f` a global toggle in settings. Then you could be in navigate mode globally, or at least for that tab, until escaping out.

**Comment by nameanyone** [comment]
Yes, something along those lines. I wasn't very clear the first time. I'd say `f` needs to remain as is, plus introduce `<c-f>` (for example) as a toggle for "link hints always on for this tab, until I hit `<c-f>` again".

**Comment by smblott-github** [comment]
I'm not sure about automatically invoking link hints.

However,

    map ??? LinkHints.activateModeWithQueue

or:

    map ??? LinkHints.activateModeToOpenInNewForegroundTab count=999999

might help.

**Comment by nameanyone** [comment]
@smblott-github , could you explain what your advice means. Where do I put this, what does `???` mean, and what is it going to do?

**Comment by smblott-github** [comment]
On the options page, add one (or both?) of these to the *Custom Key Mappings*.  Replace `???` with the key or keys of your choice.

**Comment by nameanyone** [comment]
Thank you, either seems to do what I'm after.
It's pretty esoteric though. I didn't see it explained anywhere that if the links/buttons are for the same page, then, unlike `f`, the other two will keep the hints on.

**Comment by smblott-github** [comment]
On the options page, click *Show available commands*...

![160820-01-snapshot](https://cloud.githubusercontent.com/assets/2641335/17829250/ecb0da3e-66a0-11e6-8c14-853af5ab5b4f.png)

The various link-hint commands are documented there...

![160820-03-snapshot](https://cloud.githubusercontent.com/assets/2641335/17829256/1b37917c-66a1-11e6-998e-eddd4abdde0a.png)

See also [the wiki](https://github.com/philc/vimium/wiki), e.g. [here](https://github.com/philc/vimium/wiki/Tips-and-Tricks#custom-key-mappings-with-a-count).

**Comment by nameanyone** [comment]
Sorry, actually the suggested workaround works on some pages and not on others. I think it works in a situation where "Open in a new tab" is disregarded and the click action is always performed on the same tab, even if you were to right click and select "open in a new tab".

**Comment by nameanyone** [comment]
Perhaps I need to explain my use case. I work with a web console (management console for WebLogic server). It is a rich interface with multiple expandable tree views, drop-downs, checkboxes, elements with tabs etc. Most management tasks require a series of actions like open a tree node, select a line in the tree view, check a checkbox, click drop-down and select an action, which opens up another set of elements to click on. Right now I have to hit `f` in between each of the above clicks. Instead, I'd like to enable hints and have them stay persistently as I click on multiple elements. Not only that, but if a click opened up another div, then hints should mark applicable elements in that newly appeared div as well. Possible?

**Comment by nameanyone** [comment]
Please let me know if I am missing something, or my explanation is not clear. Thanks.
If you agree this is a legit issue, please reopen it.

**Comment by smblott-github** [comment]
The threshold for adding new commands (or new options on the options page) is pretty high.  Our goal is that the Vimium UX should feel natural.  See [here](https://github.com/smblott-github/vimium/blob/master/CONTRIBUTING.md#vimium-design-goals).  Your proposal is pretty niche, and not -- in my opinion -- likely to be of interest to a large number of users.  Since there is a way to achieve pretty much what you want already (albeit esoteric), I don't think it warrants adding any new features.

Thanks, though.

**Comment by aaronshenhao** [comment]
Is there currently a built in way to do this, since the last post was from 2016? I have also found myself having to press `f` multiple times, mostly on navbars and dynamic elements. For example, to navigate to a particular lecture in Canvas, I have to click "Subjects" > "A course" > "Lecture Capture" > "Lecture folder" > "Lecture". Instead of 5 key presses, I now have to press 10 times! Also, I have to make sure the navbar/page properly loads (it is dynamic) before pressing `f`, which adds further delay.

`<a-f>` has persistent hints, except that it is for opening links in new tabs. Given that `f` opens a link in the current tab, and `F` opens a link in a new tab, it would seem natural for `<a-f>` to be used for consecutively clicking on links in the current page, while `<a-F>` would be used to consecutively click on links to be opened in new tabs (currently mapped to `<a-f>`).

**Comment by pimlottc** [comment]
@aaronshenhao I found what might be a partial solution.

Try this:

```
map <a-f> LinkHints.activateMode count=999999
```

The "count" parameter will make the hints stay active after choosing the first link.  However, this will only work for links that do not cause a page load.  So it might work for your menus, but as soon as you hit a new page, you'll have to hit the `<a-f>` again to see hints again.

**Comment by philc** [comment]
Rubaboo described the use case well [here](https://github.com/philc/vimium/issues/2197#issuecomment-241926058) -- navigating single page web apps or trees -- and @pimlottc's [suggested implementation](https://github.com/philc/vimium/issues/2197#issuecomment-985627245) is the best available approach in Vimium right now for that use case.

This is a cool feature idea, but I think rarely used and non-trivial to implement correctly as the page updates itself, so I'm leaving this closed.
