### ISSUE TITLE
Scrolling not working on Chromium 48.0.2564.82 Ubuntu 15.04 (64-bit)

### ISSUE THREAD

**Issue by pixelastic** [philc/vimium#2227]
Hello,

I've been using the extension for the past few years, but it recently stopped working. I'm using Chromium 48.0.2564.82 Ubuntu 15.04 (64-bit) and might have changed versions at the time Vimium stopped working, I cannot really tell if it's linked or not.

I tried disabling all other extensions, to not avail. Some keys are working (`?`, `f`, `yy` for example) but everything that has to do with scrolling just does nothing (`g`, `j`, `k`, `gg`).

Here is the full dump of my current config:
![image](https://cloud.githubusercontent.com/assets/283419/17837967/0e01175a-67c1-11e6-9583-f3411dceb3f4.png)
![image](https://cloud.githubusercontent.com/assets/283419/17837970/1dba6840-67c1-11e6-9c4b-6c839802ea52.png)

Maybe my Chromium version is too old? But it was working with an even older version as far as I remember. I'd be happy to provide any more information if needed.

**Comment by innaterebel** [comment]
Try disabling the `experimental-web-platform-features` flag in chrome://flags first. That experiment is known to cause this kind of issue.

**Comment by pixelastic** [comment]
Thanks. This fixed the issue. I'm not even sure why I enabled this in the first place.

**Comment by smblott-github** [comment]
There's a PR knocking around which might fix this issue.

However, perhaps we should add something to the Wiki?

**Comment by innaterebel** [comment]
That experiment enables A LOT of things at once. It's likely for people to have casually enabled it when they saw some 'performance tips' on the web and forgot about it.

Catalogue it in the Wiki might do very little as most people would instinctively see this as a bug to report rather than an usage to search for instructions. It certainly is a FAQ though.
Perhaps move the FAQ to a more prominent place? Does GitHub provide a "read before submitting a bug report" layout? Or link it in the start of the description of Web Store page.

**Comment by pixelastic** [comment]
I was not even aware that there was a wiki, but I did read the contribution guidelines before posting the issue. I can't speak for the others, but if this information had been in the CONTRIBUTIN.md, I would have been able to fix it myself, so that might be an easy win.
