### ISSUE TITLE
Allow for disabling omnibar

### ISSUE THREAD

**Issue by rightaway** [philc/vimium#2252]
I'd like to be able to disable the omnibar, so that pressing 'o' will highlight the text currently selected in the address bar, allowing me to change things there. The vim extension on firefox does this and I prefer that it's less intrusive and doesn't change the UI elements of chrome.

Also the omnibar doesn't let me search my custom search engines. There are some closed issues about this, where if I've added a custom search engine of youtube with a keyword of 'y', typing 'y stuff' into the omnibar searches google for 'y stuff' rather than searching youtube for 'stuff'.

**Comment by smblott-github** [comment]
You can disable the vomnibar with:

   unmap o
   unmap O
   unmap b
   ....

... and so on for the other vomnibar bindings (on the options page).

There is no programmatic way for Vimium to put the focus in the omnibox.  You need to use Chrome shortcuts for that.

But, just so you know, Vimium supports [custom search engines](https://github.com/philc/vimium/wiki/Search-Engines), with [completion](https://github.com/philc/vimium/wiki/Search-Completion), and you can [bind custom search engines to key sequences](https://github.com/philc/vimium/wiki/Tips-and-Tricks#keyboard-shortcuts-for-custom-search-engines).

There is (I believe) no way for a Chrome extension to access the user's Chrome custom search engines.

**Comment by ronjouch** [comment]
> *There is no programmatic way for Vimium to put the focus in the omnibox. You need to use Chrome shortcuts for that.*

Does this apply to Vimium-FF too? I'm used to the behavior of the native Firefox omnibar and would love to see `o` simply focusing it (like soon-unusable-due-to-webextensions VimFx did). No API for that in Firefox either? 😕

**Comment by smblott-github** [comment]
> Does this apply to Vimium-FF too?

Should do.

**Comment by rmats** [comment]
I'm using Vimium-ff coming from Vimfx, and I too would like to bypass the vomnibar completely.

> But, just so you know, Vimium supports custom search engines, with completion, and you can bind custom search engines to key sequences.

I appreciate the effort that went into it, but it's redundant, since functionality wise all of the vomnibar features are already (much better) implemented by Firefox in the address bar (searching bookmarks/history, search engines shortcuts, etc.).

The only thing that's missing is a keybinding to put the focus on the address bar (ideally `o`). It seems like a simple thing to do, although I'm not sure if there is currently an API for this.

**Comment by mrmr1993** [comment]
> it's redundant, since functionality wise all of the vomnibar features are already (much better) implemented by Firefox in the address bar
>
> The only thing that's missing is a keybinding to put the focus on the address bar (ideally `o`). It seems like a simple thing to do, although I'm not sure if there is currently an API for this.

This is why the Vomnibar exists. If there was an API, it wouldn't.

**Comment by philc** [comment]
Also note that the reason the vomnibar exists is described in [the FAQ](https://github.com/philc/vimium/wiki/FAQ).

**Comment by atav32** [comment]
Since I never use the Vomnibar, I'd still like a setting that can toggle whether the vomnibar automatically renders its iframe.

<img width="508" alt="screen shot 2018-01-11 at 1 36 59 pm" src="https://user-images.githubusercontent.com/622185/34848699-96747c14-f6d4-11e7-9846-18560299c908.png">

Two reasons that bug me everyday
1) As a frontend developer, it's annoying to see it in the DOM
2) It seems to cause all sorts of weird console output in Chromium when it renders it's frame

<img width="584" alt="screen shot 2018-01-11 at 1 38 34 pm" src="https://user-images.githubusercontent.com/622185/34848772-df1873f8-f6d4-11e7-8f18-7195fd2d2ad0.png">

If you guys are open to it, I can work on a PR.

**Comment by smblott-github** [comment]
If you disable Vimium on the site you're working on, then the Vomnibar iframe is not injected at all.

**Comment by atav32** [comment]
Yup. But then I won't be able to use Vimium...

**Comment by leblancfg** [comment]
For anyone coming to this issue to access the Firefox Address Bar from the keyboard, the shortcuts `Ctrl-L` and `F6` should work.

When the Address Bar isactive, `Esc` doesn't take away the focus, though, but tabbing twice (once to the search bar, once to the page) works.

I, too, find the vomnibar redundant. The ability to turn it off would be a plus.

**Comment by smblott-github** [comment]
> The ability to turn it off would be a plus.

    unmap o
    unmap O
    unmap b
    unmap B
    unmap T
    unmap ge
    unmap GE

The Vomnibar shouldn't have any effect whatsoever.

**Comment by verilucis** [comment]
+1
