### ISSUE TITLE
Feature request: Use vim.js for text/input fields

### ISSUE THREAD

**Issue by tobimensch** [philc/vimium#2286]
Why stop at making only navigation use vim like keybindings?

Wouldn't it be awesome if text/input fields would act like
an editor with vim keybindings?

Fortunately there's already a javascript library that implements just that:

http://coolwanglu.github.io/vim.js/emterpreter/vim.html

I would like to see integration of vim.js in vimium. (As an option)

With this option, when an input/text(area) field has focus, it should be replaced
with a vim.js field. When the user releases focus of that field again, the edited
text should then again be placed in a regular input/text(area) field.

**Comment by smblott-github** [comment]
@tobimensch We did have a (beta) edit mode for inputs for a while.  It used the same code as visual mode.

We dropped it though, because it wasn't (and was never going to be) as good as the alternatives (e.g. wasavi).

It would be possible to bundle somebody else's JS in with Vimium, but then we'd be responsible for third-party JS running with Vimium's elevated privileges.

**Comment by tobimensch** [comment]
@smblott-github
Thanks for informing me of wasavi. It's pretty good. Seems to integrate well (so far) with vimium.
