### ISSUE TITLE
Feature request:Key mapping for Page-Open shortcuts

### ISSUE THREAD

**Issue by fivesmallq** [philc/vimium#2298]
Like Vichrome : https://github.com/k2nr/ViChrome/wiki/Vichrome-Home#key-mapping-for-page-open-shortcuts

Some fantastic tips:
## Key mapping for Page-Open shortcuts

```
nmap <Space>tw :OpenNewTab http://www.twitter.com
nmap <Space>gr :OpenNewTab http://www.google.co.jp/reader
nmap <Space>m :OpenNewTab https://mail.google.com/mail/#inbox
```

**Comment by smblott-github** [comment]
Not really answering your request, @fivesmallq, but...

Vimium provides two ways of achieving almost the effect you're looking for.

1 - Global marks:

- Go to Twitter (say).
- *Do not scroll down*.
- Create a global mark: `mT`.

Now, <code>`T</code> either takes you to an existing Twitter tab, or creates one if necessary.

You can remap `Marks.activateGotoMode` to whatever you want.

2 - Bookmarks.  Vimium does a pretty good job of scoring matches in the (bookmarks) Vomnibar (`b`).  Whole-word matches score very highly.  If you put an isolated "t" in the name of your Twitter bookmark, or an unusual word like "gml" in the name of your Gmail bookmark, then `b`, `t`, or `b`, `gml` will usually pick out your bookmark pretty well.

**Comment by kinclma1** [comment]
The main advantage of this vichrome feature is that you can open multiple URLs with one keybind, such as your favourite news sites.

**Comment by smblott-github** [comment]
I'm considering adding a `sendMessage` command to allow messaging of external components (which can then implement commands which wouldn't otherwise make it into Vimium proper).

This request might be in that category.

See 2312 (and, in particular, [here](https://github.com/smblott-github/vimium/blob/sendMessage-command-v2/examples/external-commands/README.md)).

Inspired by this issue, the demo includes an `openUrls` command: [here](https://github.com/smblott-github/vimium/blob/sendMessage-command-v2/examples/external-commands/background.coffee).
