### ISSUE TITLE
remapping c-g to c-[ only partially works

### ISSUE THREAD

**Issue by gdobbins** [philc/vimium#2454]
Using only the custom key mapping `mapkey <c-g> <c-[>` will cause c-g to work as escape in *some* modes, like insert and the vomnibar, but not in find mode or in normal mode. Instead chrome's builtin search bar will be opened. Binding c-g to some other command, like scrollToBottom, works in normal mode so escape should also be able to work.

**Comment by smblott-github** [comment]
From the release notes...

> Vimium can now do simple key mapping **in some modes**; see here.

Related to #2447.

However, I agree that we should look into fixing this.

**Comment by smblott-github** [comment]
OK.  scratch my first response, @gdobbins...

For find mode, there was a bug which I've fixed, here: e19f5c95c19eff13be96b8438711d37dc37884d1.

For normal mode, this is the correct behaviour.  Or, at least, it's the way Vimium handles `Escape`, so it is arguably the correct behaviour for the mappings you describe.  In normal mode, Vimium consumes `Escape` **if there is something to escape**, e.g. the user has begun typing a command but decides to back out, but passes `Escape` on to the page otherwise (in case the page wants to do something with it).

I'm not sure there's a case for handling mapped escape keys differently.

**Comment by gdobbins** [comment]
The reason I want c-g to always be handled as escape is because that is what Emacs does. Vimium works extremely well as an Emacs emulator for chromium except for c-g. When it is passed on you get into the native finder which then can't be escaped except with the real escape key, which is quite annoying.

>In normal mode, Vimium consumes Escape if there is something to escape, e.g. the user has begun typing a command but decides to back out, but passes Escape on to the page otherwise (in case the page wants to do something with it).

Would it be possible to have Vimium actually pass Escape in this case? Currently it is passing on c-g.
