### ISSUE TITLE
not working in mac os

### ISSUE THREAD

**Issue by jingpengwu** [philc/vimium#2511]
there is an old issue in [2010](https://github.com/philc/vimium/issues/154#issuecomment-301315332), I tried to update to the latest chrome in 2017 though. It is still not working. works great in my ubuntu workstation though.
the chrome version is 58.0.3029.110 (64-bit).

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

**Comment by mrmr1993** [comment]
What is the actual issue?
* Is Vimium installed or is it failing to install?
* Is Vimium not updating to the latest version?
* Is the Vimium icon showing as active (blue) or inactive (grey) in the toolbar? On a particular page or on all pages?
* Are keyboard shortcuts working? If not, which ones?
* Are webpages broken when Vimium is installed that work normally without it?

Can you provide any extra information?
* Are there errors in the Vimium background page?
  - Go to `chrome://extensions`, click the "Developer mode" checkbox, click the link labelled "Inspect Views: background page" under Vimium. A window will open.
  - Press the `esc` key to toggle the console in that window, if it's not already showing. Any errors/messages might be helpful or relevent.
* Are there errors in the console for webpages where Vimium isn't working, if applicable. (google.com is probably a good place to test this, as it shouldn't normally have any).
  - Click the three dots menu in the toolbar, select the "More tools" submenu, and click "Developer tools".
  - Again, press the `esc` key to toggle the console, if it isn't showing already.
* Have you customised any options in the options page (accessible from `chrome://extensions`)?
  - If so, which ones, and what happens when you reset them to normal?

**Comment by jingpengwu** [comment]
- both chrome and vimium were updated
- the installation don't have any problem.
- the icon shows as active on all the pages
- keyboard shortcuts are **all** not working
- webpage is normal just like without vimium
- I did not see any errors in the console following the steps

**Comment by jingpengwu** [comment]
I just removed and installed vimium, and it is working now!
