### ISSUE TITLE
Keep focused element on page load

### ISSUE THREAD

**Issue by printercu** [philc/vimium#2586]
Hi!

I've noticed that vimium steals removes focus which is set with js on page load. In http://api.rubyonrails.org/ search field is focused by default if I add this url to vimium's blacklist. But if vimium is enabled, it visible that input is focused for short period of time, and then looses focus.

Is it a bug or this is the way vimium works?

**Comment by innaterebel** [comment]
It's a feature you can find in the advanced section of Vimium options.

**Comment by printercu** [comment]
Do you mean `Don't let pages steal the focus on load`? It's disabled for me. If I enable it, I don't see even blinking outline for focused input - it's not focused at all. And I can't see any other related options.

**Comment by mrmr1993** [comment]
I've had a look at this and been able to reproduce it.

The issue seems to be that the input loses focus when we add an `<iframe>` (in our case, the Vomnibar) to a document containing a `<frameset>` instead of a `<body>`. AFAICT:
* [`<frameset>`](https://developer.mozilla.org/en/docs/Web/HTML/Element/frameset) is deprecated in HTML5, and has not been widely used in some time
* adding the Vomnibar to the top-level frame only has been otherwise working nicely for us
  - we would have to go back to Vomnibar-per-frame to fix this
* focus can be restored to the input manually after the `<iframe>` is added

On this basis, it seems like a Chromium issue, has very little impact, and I don't think that we should try to work around it. Sorry @printercu.

**Comment by printercu** [comment]
Ok, got it. Thank you for your time!

Am I right, that iframe is required only for vomnibar? I'm using vimium mostly for navigation within page and following links with f/F. If it does not require to rewrite almost everything and will fix the issue, can we have toggle in settings to turn of vomnibar and all related actions?

**Comment by mrmr1993** [comment]
> Am I right, that iframe is required only for vomnibar?

We use an iframe for the HUD (for find mode, etc.) too, but it's injected into each frame Vimium is active on. This doesn't include frames containing `<frameset>`, so it isn't an issue here.

**Comment by printercu** [comment]
Ok, thank you!
