### ISSUE TITLE
Vimium-FF last updated on April 22nd? Experimental build availability?

### ISSUE THREAD

**Issue by Dessix** [philc/vimium#2600]
As of today, Version 1.59 is the latest version, updated on April 22nd, 2017. The same is true for the Chrome version of the extension.

Is there a reason that the Firefox (and for that matter Chrome) version isn't being updated regularly? I understand that plenty of compatibility issues still exist, but are they preventing mainline updates from propagating to the FF addon smoothly? Is there a more frequently updated branch we can install from? If it's a matter of stability- the Firefox branch is noted as being experimental, so faster pacing of releases may help there.

**Comment by mrmr1993** [comment]
Since then, the only progress of note that has been made and merged is 9a1b56a899575d71e07eb3466e5fbf16d5a18571 (as you can check in [the commit history](https://github.com/philc/vimium/commits/master)). I'm not involved with releases (or anything else really), but I imagine that there haven't been any new versions because there's essentially nothing new to put out.

I'm always happy to review a PR, if there are changes you'd like to make.

**Comment by Dessix** [comment]
Thanks- I guess I thought that Vimium's development just looked a lot more active than it actually is.
