### ISSUE TITLE
Link targets are shifted when zooming in/out

### ISSUE THREAD

**Issue by romgrk** [philc/vimium#2615]
Version: Version 61.0.3163.49 (Official Build) beta (64-bit)

Problem:
![image](https://image.ibb.co/cBwmrk/Screenshot_from_2017_08_25_20_53_25.png)

Let me know which other details I can provide.

**Comment by mrmr1993** [comment]
This looks to be a duplicate of #2159.

**Comment by jeopsh** [comment]
It's work well if you zooming in/out at first.

**Comment by bclement** [comment]
I just encountered this issue after upgrading my chrome to Version 61.0.3163.79 (Official Build) (64-bit)
on Fedora 26. I don't know what build I was on before the update but the labels were aligned with the links.

This problem is independent of when the zoom is done. I can zoom in, close the browser, open the browser and press 'f' and the labels will still be unaligned. The only time the labels match the links is with no zoom.

**Comment by wchargin** [comment]
@bclement I have the same issue, updating from
```
/var/cache/apt/archives/google-chrome-stable_60.0.3112.90-1_amd64.deb
```
to
```
/var/cache/apt/archives/google-chrome-stable_61.0.3163.79-1_amd64.deb
```

You maybe be able to reinstall from a previous archive?

For Debian-derived users, I'm hosting a working Chrome60 package here:  
https://www.dropbox.com/s/98rwiuohojgmhnr/google-chrome-stable_60.0.3112.90-1_amd64.deb?dl=0

Hash:
```shell
$ shasum -a 256 /var/cache/apt/archives/google-chrome-stable_60.0.3112.90-1_amd64.deb
936eb6dbf6062b4a375593d3289375d3f7823d3168673534f54f037d632283d3  /var/cache/apt/archives/google-chrome-stable_60.0.3112.90-1_amd64.deb
```

**Comment by romgrk** [comment]
Issue has disappeared. Vimium 1.60.3. Chrome still at Version 61.0.3163.49 (Official Build) beta (64-bit).
