### ISSUE TITLE
Non-Latin keyboard layouts do not initiate actions

### ISSUE THREAD

**Issue by giogziro95** [philc/vimium#2618]
When I switch to a non-Latin keyboard layout (e.g. Georgian, Russian, etc.), pressing the keys doesn't do anything. Is it possible to use something like [this](http://keycode.info/) instead?

- Chrome version: 60.0.3112.90 (Stable channel)
- Vimium version: 1.59

**Comment by giogziro95** [comment]
Woah, sorry. Just searched and it has already been reported several times.

**Comment by smblott-github** [comment]
From [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode):

![snapshot](https://user-images.githubusercontent.com/2641335/29752051-8c8e99f6-8b4e-11e7-87da-4637b29b4784.png)

**Comment by giogziro95** [comment]
@smblott-github Yes, I saw that. Is there a substitute for it?

**Comment by giogziro95** [comment]
The [example on the page](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Example) suggests a workable solution with a fallback.

**Comment by smblott-github** [comment]
It's not exactly satisfactory, but you could do something like [this](https://github.com/philc/vimium/wiki/Key-Mappings) for whatever you language is.  And you can leave the Latin bindings in place too.

Vimium is using `event.key`.

> The example on the page suggests a workable solution with a fallback.

No.  We're already using `event.key` (the default, on that page), and the other two are deprecated.    In fact, the other two would never fire because Chrome defines `event.key`.  Same for Firefox.

**Comment by mrmr1993** [comment]
The ideal solution would be to allow mapping keys by code ([`event.code`](https://developer.mozilla.org/en/docs/Web/API/KeyboardEvent/code), but this will complicate the key handling code quite a bit, and I don't think anybody's attempted it so far.

**Comment by giogziro95** [comment]
> We're already using `event.key` (the default, on that page), and the other two are deprecated. In fact, the other two would never fire because Chrome defines `event.key`. Same for Firefox.

That's really inconvenient for the purposes of Vimium. Almost nobody would want to fire different actions based on the layout they're using. Is there a more consistent method across the different layouts?

> It's not exactly satisfactory, but you could do something like this for whatever you language is. And you can leave the Latin bindings in place too.

Yeah, I know that. Unfortunately, for many users, that's a bit of hassle.

**Comment by giogziro95** [comment]
BTW, may I add the key bindings for the layout of my language in the [Wiki page](https://github.com/philc/vimium/wiki/Key-Mappings), so others can copy and paste?

**Comment by mrmr1993** [comment]
> may I add the key bindings for the layout of my language in the Wiki

Please do!

**Comment by giogziro95** [comment]
> Please do!

[Done!](https://github.com/philc/vimium/wiki/Key-Mappings/6ac9d026cf2db583b1de98798b691e4ef94dd140#georgian-language-keyboards) And I know, it is messy ([just like the Unicode](https://xkcd.com/1726/)).

**Comment by giogziro95** [comment]
Just checked and Facebook has working keyboard shortcuts on every layout. I haven't dug into the code yet.

Disable Vimium and hit <kbd>Shift</kbd>+<kbd>/</kbd> (<kbd>?</kbd>) to see the shortcuts.

**Comment by lydell** [comment]
In my opinion, this is a solved problem. [VimFx](https://github.com/akhodakivskiy/VimFx) used to have all sorts of keyboard layout issues, but we figured it out two years ago and haven't had a single bug about keyboard layouts since (except a few minor edge cases that we didn't think of straight away but were easy to fix). The important realization was that **there's no one-size-fits-all solution.** As I mentioned in https://github.com/philc/vimium/issues/2481#issuecomment-295609608 the trick is to provide a "Ignore keyboard layout" option (off by default in VimFx). Non-latin keyboard users tick that checkbox. End of story. Implementation wise, this means using _both_ `event.key` and `event.code`. VimFx's implementation can be found in [vim-like-key-notation](https://github.com/lydell/vim-like-key-notation) (which also contains more in-depth discussion/research); I'm sure that Vimium can use it as inspiration to do something similar. (Don't worry about the length readme, [the code](https://github.com/lydell/vim-like-key-notation/blob/master/index.js) is just ~200 pretty straight-forward lines). As VimFx is now officially declared dead and links to Vimium-FF as an alternative, I expect people coming from VimFx to miss this feature in Vimium.

**Comment by smblott-github** [comment]
Thanks, @lydell.  I think that's the way to go, and the change should be fairly trivial in Vimium.

**Comment by giogziro95** [comment]
@lydell Just tried VimFx with the _Ignore keyboard layout_ setting enabled. Works flawlessly on different layouts. And non-QWERTY users would have custom key mappings anyway since Vim is primarily designed for QWERTY keyboards.

**Comment by giogziro95** [comment]
This even works with the link hints. Awesome!

I think the [wiki page](https://github.com/philc/vimium/wiki/Key-Mappings) should be updated as well; the most of the information is obsolete there.

**Comment by BackSlasher** [comment]
Just found this. Thanks for brainstorming and implementing!
