### ISSUE TITLE
yank link (yf) command not yanking anything in Firefox

### ISSUE THREAD

**Issue by majewsky** [philc/vimium#2677]
On Firefox 55.0.3 with latest stable Vimium-FF from AMO, the yank link (yf) command is not working. I can see the UI (i.e. the overlays showing which letter to press to select a link), but when a link is selected, the X clipboard contents do not change. The standard "Copy Link Location" menu entry in the link's context menu is working fine, though.

OS is Arch Linux (kernel 4.12.12, X server 1.19.3 and Plasma desktop 5.10.5).

**Comment by mrmr1993** [comment]
Firefox doesn't provide a proper reliable clipboard API, so it's very difficult to get this working properly.

PR #2601 improves the situation so that copy/paste (mostly) work, but it hasn't been merged.

**Comment by majewsky** [comment]
Okay great. Thanks for your update.

Just for your reference, the same bug also occurs in Firefox 55.0.3 on macOS Sierra, and `yy` is affected as well (as is to be expected when general clipboard interaction is the problem).

**Comment by xuhdev** [comment]
Do you have a reference to the related bug in Firefox bugtracker?

**Comment by majewsky** [comment]
@xuhdev If you look at the PR which was linked above, you can see that the relevant Firefox issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1344410

**Comment by dessalines** [comment]
This is still an issue.

**Comment by vbauerster** [comment]
Still an issue with FF 67.0.3 on macOS 10.14.5.

**Comment by asheshambasta** [comment]
> @xuhdev If you look at the PR which was linked above, you can see that the relevant Firefox issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1344410

Looks like the issue on the FF bugtracker has been closed as "fixed". Does that mean it's been fixed in FF and  its only a matter of implementing changes in vimium to be able to use this fix?

**Comment by cronyakatsuki** [comment]
Yanking with any command being `yy`, `yf`, ... doesn't always work. I sometimes works right away but sometimes I have to try 10+ times it to get yanked.

**Comment by LaPeste** [comment]
Are you sure this problem still exists?
Currently it seems that `yf` works.
`yy` isn't working but it seems that a [fix](https://github.com/philc/vimium/issues/4173#issuecomment-1353185856) is on the way.
This issue is old and only referring to `yf`. All I'm trying to say is that I think it can be closed.

**Comment by deen1** [comment]
Neither `yf` nor `yy` work for me, and haven't for roughly the past month. Running Firefox 107.0 on Manjaro Linux.

**Comment by mocknen** [comment]
@cronyakatsuki  @deen1 
It is probably because you installed Vimium directly from source according to [this](https://github.com/philc/vimium/blob/99868023af1635350680c148f6ad98a2b2136895/CONTRIBUTING.md#installing-from-source) document.
Since [this](https://github.com/philc/vimium/commit/15ba534fc8eda6ed72d641e0002d00d6d255e1d0) commit, the [manifest.json](https://github.com/philc/vimium/blob/99868023af1635350680c148f6ad98a2b2136895/manifest.json) in the repository no longer contains permissions related to the clipboard.

You can simply add `clipboardWrite` and `clipboardRead` to the manifest.json permissions manually to make it work.
Alternatively, you can build the package by executing `./make.js package`  at the repository root, which may be preferred.

**Comment by deen1** [comment]
@mocknen 
I have not installed Vimium directly from source -- using version 1.67.4 as provided from the [Firefox extensions page](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/).

**Comment by philc** [comment]
This clipboard issued was fixed in 1.67.5, but that has not hit the store yet because of approval delays. Follow the saga in #4915.

**Comment by deen1** [comment]
@philc I see -- I wondered why the extension page on Firefox says "Last Updated: 4 years ago (May 21 2019)", with the latest version being 1.64.6! Hope this gets resolved. Thank you for your all your work on this project!

**Comment by philc** [comment]
This should be resolved now that #4195 is closed -- the latest version of Vimium is on the Mozilla addons site.
