### ISSUE TITLE
`F` doesn't open child tabs with Tree Style Tab

### ISSUE THREAD

**Issue by seschwar** [philc/vimium#2680]
Under Firefox Vimium 1.60.4 now supports opening links in new tabs (#2510). However when using it together with [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) I've noticed tabs opened by Vimium show up differently than tabs opened with the mouse.

I've configured Tree Style Tab to open them as children of the current tab. When using the mouse to open them (context menu, ctrl+click, middle click) they do show up as such, however new tabs opened by Vimium show up as independent tabs at the end of the tab list.

It would be nice if Vimium could open tabs the same way Firefox' mouse did and therefore honor my Tree Style Tab settings. 

Version information:

- Firefox 56.0
- FreeBSD 11.1-RELEASE
- Tree Style Tab  0.19.2017090601
- Vimium-FF 1.60.4

**Comment by mrmr1993** [comment]
Our tabs aren't opened 'from the current page' in the normal sense that TTS would use to detect them: Firefox applies the pop-up blocker to extensions, and so we have had to work around it by opening the tabs manually, outside the page.

We can't do anything about this, but you can vote (in the details section) for the [relevant Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1356309) and [the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1348213) it has been (IMO wrongly) duped into. Once that issue is fixed, this will work as expected.

**Comment by braham-snyder** [comment]
@posterity: note that you can even sign up (to vote) using your GitHub account

**Comment by hyiltiz** [comment]
Yay, also got fixed here in OSX El-Capitan 10.11.6, Firefox Developer Edition 57.0b3 (20170925150345). Thank you so much!
