### ISSUE TITLE
[Firefox] Bookmarklets not working in vomnibox

### ISSUE THREAD

**Issue by einhander** [philc/vimium#2731]
1. Firefox and OS Version:  Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
2. Vimium Version: 1.60.4

 Bookmarklets not working in vomnibox. 
They work it toolbar only. 
I use [https://github.com/nfahlgren/scihub_bookmark/blob/master/sci-hub.bookmark.js](url) as test.

**Comment by mrmr1993** [comment]
This is a Firefox bug, vaguely related to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1269456). Firefox won't let us run `tabs.update` with `javascript:` URLs, even when we have permission to access the page. We previously could, but it was ['fixed'](https://bugzilla.mozilla.org/show_bug.cgi?id=1227462), where the decision was made to block all extensions from switching to `javascript` URLs, to little ceremony.

Notably, none of the potential fixes on our end cover all the necessary cases:
* `tabs.executeScript` (suggested alongside the 'fix') runs code in *our* js context, not the page's, which breaks any bookmarklets that depend on access to the page's js, and can lead to Vimium being broken by some bookmarklets
* we can inject code into the page context to run, but then page CSP may block it from running (eg. on github), the pop-up blocker affects it, and the page itself can block our injection methods.

I couldn't find a Firefox issue specifically for this (possibly because bugzilla search is not great); if you open a Firefox issue for this, please post a link back here so we can vote on it and I can track it.

**Comment by einhander** [comment]
@mrmr1993 Thank you for fast and detailed answer.
It's hard to hear that upcoming Firefox is root of problem, because it really faster than chrome, but suffers from the same issues.

You can close this issue if you like.
