### ISSUE TITLE
Vimium for Firefox breaks rendering of XML documents

### ISSUE THREAD

**Issue by glindste** [philc/vimium#2737]
With Vimium installed and enabled in Firefox, XML is treated like HTML when rendering. This was tested with Firefox Developer Edition version 57.0b9

Example from https://www.website.com/sitemap.xml:

![image](https://user-images.githubusercontent.com/1015224/31880544-2a94d17e-b7e1-11e7-8a18-e755c83ec46f.png)

However when vimium is disabled proper rendering is restored:

![image](https://user-images.githubusercontent.com/1015224/31880623-62d12952-b7e1-11e7-9716-9ad662d07cad.png)

**Comment by mrmr1993** [comment]
This is fixed (as best we can; we can't workaround the underlying Firefox issue) in current master, and will be in the next version. See PR #2691 for more.

@smblott-github current master has been stable on Firefox AFAICT, and is only bugfixes + the AlphabetHints change since last FF version. Any chance of pushing a new version soon?

**Comment by smblott-github** [comment]
@mrmr1993 ...

> Any chance of pushing a new version soon?

Yes, I was thinking of doing that. I will do so.

(It would be good to make a firm decision about what to do re. copy/paste on FF, though.)

Closing this issue.
