### ISSUE TITLE
Not working on some pages

### ISSUE THREAD

**Issue by franklinyu** [philc/vimium#2739]
This applies only to Firefox.

Some page prevents Vimium from working, for example most (if not all) of the Microsoft support pages:

 - https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts
 - https://support.microsoft.com/en-us/help/13805/windows-keyboard-shortcuts-in-apps

At least `?` doesn't work.

**Comment by mrmr1993** [comment]
This seems to be the same underlying bug as #2675, since my testcase from [the Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1410642) fails here too. There's nothing we can do on our end.

If you log into bugzilla using your GitHub account and vote on the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1410642), the Mozilla devs are more likely to see it and work on it sooner.

**Comment by franklinyu** [comment]
Great, voted and subscribed. Will re-open this if it turns out to be a different one.
