### ISSUE TITLE
Does not seem to work on the BBC Weather page using Firefox

### ISSUE THREAD

**Issue by Noexpert** [philc/vimium#2799]
http://www.bbc.co.uk/weather/5128581

**Comment by mrmr1993** [comment]
This seems to be the same root cause as #2675. I've opened PR #2800 to fix the issue for this page.

This is caused by Firefox issue [1408996](https://bugzilla.mozilla.org/show_bug.cgi?id=1408996). This can make our (and other extensions') code fail in various ways on different websites, but there is nobody actively looking at the bug. You can help us bring attention to this on their side by:
* visiting [the issue page](https://bugzilla.mozilla.org/show_bug.cgi?id=1408996)
* log in (you can use your GitHub account)
* click the vote button, check the checkbox for the issue on the new page, and click "change my votes"
