### ISSUE TITLE
[Firefox] Cannot turn off smooth scrolling

### ISSUE THREAD

**Issue by dglava** [philc/vimium#2811]
In the preferences, under "Miscellaneous options", I have unticked "Use smooth scrolling". Yet scrolling with j/k or d/u is smooth.
I have turned off smooth scrolling in the browser and scrolling with the space-bar is not smooth, i.e.: as desired.

Firefox version: 57
Vimium version: 1.61.1

**Comment by mrmr1993** [comment]
Can't repro; this is working fine for me. Did you remember to press the "Save Changes" button (at the bottom of the page)?

**Comment by dglava** [comment]
Yes, I clicked the "Save Changes" button and it applied the other settings.
Here's a short video demonstrating it. First I'm scrolling with d/u and it's smooth. Then I used Page Up and Down to scroll and it's not smooth.

https://webmshare.com/oPm51

Is there anything else I could look into to rule out a problem on my end?

**Comment by mrmr1993** [comment]
The only points of failure I can see are:
* `element.scrollTop += 60` smooth scrolls (since this is what non-smooth scrolling should run)
* the setting isn't being loaded/recalled properly.
  - do other settings' changes (e.g. scroll step size) take effect?
* some other extension is doing the smooth scrolling
  - does the page still smooth scroll if Vimium is disabled?

**Comment by dglava** [comment]
My bad. I tested it on another computer and it works. Resetting everything on the other one and changing the options again fixed it.
