### ISSUE TITLE
[Firefox] Cannot switch tabs in certain scenarios

### ISSUE THREAD

**Issue by dglava** [philc/vimium#2812]
I did a quick search and couldn't find if this was already reported.

Basically when you open a link in a new tab and the page starts loading, you cannot move to a different tab with J/K until the page loads. When you open a new tab moving between tabs with J/K also doesn't work.
Is this a known limitation and how likely is it that this will be fixed?

Firefox version: 57
Vimium version: 1.61.1

**Comment by pcuinty** [comment]
same here, while page is loading one cannot switch tabs

Firefox: 58.0a1
Vimium: 1.61.1

**Comment by mrmr1993** [comment]
This is by design (of WebExtensions): we can only capture keys on webpages where our scripts have been loaded, and the browser doesn't load our scripts until the page has started loading.

**Comment by pcuinty** [comment]
> until the page has started loading

this would be fine. right  now the scripts don't get loaded until the page *has finished* loading

**Comment by mrmr1993** [comment]
> until the page *has finished* loading

I wasn't counting network time as loading. As soon as the network has responded, it should load our scripts and then start trying to parse the page.

This makes some sense, because the browser doesn't know what domain the request will end up pointing to (due to HTTP redirects, e.g. status 301), and an early-created `window` object associated with the wrong domain is a potential XSS vector. In the same vein, the browser doesn't know whether the redirect will lead to `addons.mozilla.org` (where extensions can't run), and loading the scripts before a redirect could give a malicious extension access to those URLs. (Ditto for URLs an extension hasn't requested access for.)

This is an annoyance, but the reality of WebExtensions is that we're running in the webpages not the browser, and we can't do much without a webpage to work in.

**Comment by dessalines** [comment]
Is there any way around this? It makes switching tabs _extremely_ frustrating. This worked as it should in vimperator, where you could switch tabs before a page had even really started loading.

**Comment by mrmr1993** [comment]
No.

A few people across related projects are working on an API proposal that should help. I don't expect anything to come from it quickly, if at all.

**Comment by sheeit** [comment]
@dessalines:
> Is there any way around this?

There is actually, but you won't like it: Use older versions of Firefox (or Firefox ESR) before the version where "legacy" add-ons were no longer supported, then install VimFX.
