### ISSUE TITLE
Back- and foreground colors are idential in options menu (FireFox, Arc-dark-solid gtk theme)

### ISSUE THREAD

**Issue by FichteFoll** [philc/vimium#2832]
So, I use the Arc-dark-solid gtk theme, which affects FireFox's default colors, and any text in the text areas of the options page is practically invisible. It's there because it shows up when you select text, but you can't see it by default. You can't even see a caret. This also affects single-line inputs in the advanced options.

Idk what exactly you are doing, but please set fore- *and* background color when you change either.

![2017-11-22_23-11-09](https://user-images.githubusercontent.com/931051/33151992-a637b560-cfda-11e7-8c6a-d39fadc1ea04.png)

ArchLinux, FF 57, Vimium 1.61.1

**Comment by rvolosatovs** [comment]
Same issue here using dark GTK theme

**Comment by mejo13** [comment]
Yup, same problem with firefox 58 (dark theme) and vimium 1.62.8 on ubuntu mate 17.10 (dark theme)...

**Comment by hackel** [comment]
This is a pretty extreme usability issue.  I use the addon "Text Contrast for Dark Themes" to fix this problem elsewhere on the web, but since extensions aren't allowed to run on extension option pages, it is useless to fix the issue.  I have sent a small PR that should be a good enough fix!

![screen shot 2018-03-08 at 18 46 57](https://user-images.githubusercontent.com/583677/37169975-78ff80c6-2301-11e8-920c-4c56020aec37.png)

**Comment by smblott-github** [comment]
Should be fixed in #2981.
