### ISSUE TITLE
Disable autofocusing on text box at the first time

### ISSUE THREAD

**Issue by kharazi** [philc/vimium#2898]
Hi,
When there are many open tabs in the browser and you want to switch between tabs using `J`, `K` (or `gT`, `gt`) tabs with activated text-box are annoying(for example a Google homepage in middle) and should press `Esc` before switching. Is there any faster way to switch tabs or disable focus on textboxes after entrance?

**Comment by ris58h** [comment]
@kharazi You could write your own web-extension to unfocus input elements after page is loaded.
Or you could use browser's default shortcuts like ctrl+tab/ctrl+shift+tab.

**Comment by gdh1995** [comment]
There's a setting item named " Don't let pages steal the focus on load" in the Vimium Options page, which may just meet your needs.

**Comment by JorgeLdeOz** [comment]
"Don't let pages steal the focus on load" does not work since it only prevents it from losing focus when the page loads, it does not prevent the focus from going to the text box when I change tabs.  I could try using ctrl+tab/ctrl+shift+tab but I really insist that I be able to move around with vimium's J,K

**Comment by lucmann** [comment]
> [@kharazi](https://github.com/kharazi) You could write your own web-extension to unfocus input elements after page is loaded. Or you could use browser's default shortcuts like ctrl+tab/ctrl+shift+tab.

@ris58h personally, ctrl+tab is fine to me, but i feel like ctrl+shift+tab is kinda less handy compared to shift+k.
