### ISSUE TITLE
Vimium does not work in Strict Site Isolation mode

### ISSUE THREAD

**Issue by wichtounet** [philc/vimium#2911]
Hi, 

I'm not sure this is really a bug, but I've tried to use Strict Site Isolation on Vivaldi (Chromium engine) and it does not work. 

For instance, t opens correctly the input search box but I cannot write inside. 

I don't know how Strict Site Isolation mode works, so maybe this is completely expected, I just wanted to report it in case you didn't know ;)

Thanks 

Baptiste

System
- Vivaldi | 1.13.1008.40 (Stable channel) (64-bit)
- Linux
- Vimium 1.62.4

**Comment by smblott-github** [comment]
Cannot reproduce in Chrome.  Anybody else?

@wichtounet Are there any error messages in the console?

**Comment by wichtounet** [comment]
@smblott-github The Console in the web tools ? Nothing here related to vimium.

**Comment by gdh1995** [comment]
I've reproduced this on Vivaldi with the flag `#enable-site-per-process` enabled, and I think it's a bug of Vivaldi and there's few things we can do about it.

In face, `#enable-site-per-process` is a highly experimental feature of Chrome (also Chromium-kind browsers) for a long time, and there're some bugs caused by it on old versions of browsers. For example, Chrome whose version <= 48 will break Vimium if only the flag is enabled, because the `Window.postMessage` API is implemented bugly.

So I suggest that you disable the feature - Chromium browsers are usually safe enough with default settings.

**Comment by wichtounet** [comment]
@gdh1995 Thanks for the investigation :)

I've already disabled the feature, I was mostly testing it but I don't really mind not having it. 

If it's a problem related to some versions of browsers, it's indeed not your problem :+1:
