### ISSUE TITLE
Vimium breaks website

### ISSUE THREAD

**Issue by paales** [philc/vimium#2921]
We've just recently released our new website, but it seems that with this plugin installed the site doesn't render as it should: https://www.reachdigital.nl/

Without:
![schermafbeelding 2018-01-19 om 10 56 16](https://user-images.githubusercontent.com/1244416/35145249-74b894b4-fd07-11e7-865a-027907544f28.png)

With:
![schermafbeelding 2018-01-19 om 10 56 38](https://user-images.githubusercontent.com/1244416/35145255-787a20a4-fd07-11e7-8e94-05ff7bacd054.png)

The site doesn't throw any errors or something so I'm not really sure how to debug. I don't use the module my self but got this bug report from my fellow-programmer-friends.

Hope you can solve this in your extension

**Comment by paales** [comment]
`Mac OS 10.12.6` + `Chrome 63.0.3239.132 (Officiële build) (64-bits)` + Clicked install here: https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en (sooo, latest version I guess?)

**Comment by smblott-github** [comment]
OK.  I upgraded my Chrome from 60.SOMETHING to 63.0.3239.132, and now I see the problem too.

Git bisect blames [this commit](https://github.com/philc/vimium/commit/0537ebb07670909a21134e16ed30b3786fc6f4a0).

It seems that the site fails if *either*:

1. the Vomnibar is initialised [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L126), or

2. the flash-frame element is created [here](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L255).

If we comment out **both** of those segments of code, then the page renders just fine.

It looks like just the presence Vimium's UI components causes the rendering to fail.

@paales, does that help you figure what the source of the problem is?

**Comment by paales** [comment]
Well your extension breaks a site, not planning on changing something on my side 😄 , the extension shouldn't break anything, right?

**Comment by paales** [comment]
@smblott-github Oh a thing that is interesting, your code uses ShadowDOM and our site uses that as well, so it might break with every ShadowDOM heavy website?

**Comment by gdh1995** [comment]
In my test on Chrome 63, this website worked well when disabling all `createShadowRoot()` of Vimium, while what's strange is that it failed if Vimium created shadow roots but didn't append it to document. On Chrome 64, the page https://www.reachdigital.nl/ works well with Vimium enabled.

So it may be an issue of Chrome before 64.

BTW, I found some crashes on your website:
* a race condition bug: it often reported that `ResizeObserver` is not defined on loading (2 / 3 times)
* in `app-shell.html:19908`, `this._mutationObserver` has no `unwatch` method function (on Chrome 63/64), which might crashes other extensions (include one of mine).

**Comment by paales** [comment]
@gdh1995 Wow that is a detailed analysis. If it works in Chrome 64 that should be fine then :)

About the bugs, thanks for the reports. We already knew the ResizeObserver issue working on that, will check the other one.
