### ISSUE TITLE
New tab 't' causes Vivaldi to crash

### ISSUE THREAD

**Issue by rangercej** [philc/vimium#2942]
_vimium 1.62.4_

Since upgrading to Vivaldi 1.14.1077, every time I hit 't' to open a new tab, Vivaldi immediately shuts down - no Windows crash reporter, etc, it just acts as if the application exits, but it shuts down immediately.

Starting Vivaldi with --enable-logging -v=5 gave me the attached events in the log after 't' was pressed. I'm not sure if this suggests a Vivaldi issue over an extension issue, but raising here as a first step. Opening a new tab with Vivaldi's built-in menus/functions doesn't cause a problem. 

Occurs across multiple computers, OS = Windows 8.1 and Windows 10.

[vivaldi.log](https://github.com/philc/vimium/files/1693100/vivaldi.log)

**Comment by Richdark** [comment]
Can confirm the bug. Moreover, it's happening on both stable and snapshot releases. It's pretty annoying since I always forget not to press t.

**Comment by talgarik** [comment]
confirmed here too
windows 10

**Comment by smblott-github** [comment]
The problem seems to be [here](https://github.com/philc/vimium/blob/master/background_scripts/main.coffee#L105).  Vivaldi crashes if the URL is `about:newtab`.  Really, this is a Vivaldi bug: there shouldn't be anything an extension can do to crash the browser.

As a workaround, on the Vimium options page (under advanced options), set any other URL to use for the `createTab` command; e.g.:

![image](https://user-images.githubusercontent.com/2641335/35865890-95e93162-0b4d-11e8-91db-9861ac8f0347.png)

**Comment by Richdark** [comment]
Thank you, this workaround looks like a decent solution until the problem is fixed. I reported the bug at Vivaldi's webpage.

**Comment by rangercej** [comment]
Can confirm the same workaround resolves this. I'll report the bug to them as well.

**Comment by rangercej** [comment]
This appears to be resolved in the latest Vivaldi release (1.14.1077.55 ) that I got notified of today.
