### ISSUE TITLE
Link hints for a <dialog> element are not visible

### ISSUE THREAD

**Issue by skarkkai** [philc/vimium#3031]
When I press 'f' to show controls, nothing within a <dialog> element is flagged. This can be tested in the example in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

Linux Chrome 65.0.3325.181, Vimium 1.63.3

**Comment by smblott-github** [comment]
Indeed.

It could be related to the fact that the dialog is within an iframe.  Haven't investigated further.

**Comment by gdh1995** [comment]
A `<dialog>` seems to be always most top, and hints of LinkHInts are hidden.

On Chrome 68, there's no `z-index` statement in user-agent styles on `<dialog>`, so I have no ideas how to fix this problem.

**Comment by ravindUwU** [comment]
While link hints that are appended to the body don't work because `<dialog>`s [seem to have their own "layer"](https://stackoverflow.com/a/41816764),

```html
<body>
	<div#vimiumHintMarkerContainer>
		<div.vimiumHintMarker></div>
		<div.vimiumHintMarker></div>
	</div>
</body>
```

...we might be able to fix this by including `<dialog>`-specific hints the same way, but within the `<dialog>` element.

```html
<body>
	<dialog>
		<!-- Markers for contents of the dialog -->
		<div#vimiumHintMarkerContainer>
			<div.vimiumHintMarker></div>
			<div.vimiumHintMarker></div>
		</div>
	</dialog>

	<!-- Markers for everything else -->
	<div#vimiumHintMarkerContainer>
		<div.vimiumHintMarker></div>
		<div.vimiumHintMarker></div>
	</div>
</body>
```

I used inspect element to move `#vimiumHintMarkerContainer` into the `<dialog>` of the cookie banner at https://try.devowl.io (thank you @JulianDeal for locating this in #4068), and they seem to work 🤔.

![Vimium hints within a dialog element](https://github.com/philc/vimium/assets/7352580/3643ddba-a831-4fe6-9a1a-d14cb28eef15)

A few points to think about,

1. Vimium would now have to manage multiple containers. `#vimiumHintMarkerContainer` → `.vimiumHintMarkerContainer`?

2. If the dialog is [shown modally](https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/showModal), you won't be able to interact with anything outside it anyway, so we could skip hinting the rest of the page.

**Comment by JulianDeal** [comment]
As suggested by you, @ravindUwU , I started injecting multiple hint containers into the code. 

For dialogs as in https://try.devowl.io/ you have to account for scroll position, because the dialog creates its own stacking context.

It works fine for devowl. Problem is with [mozilla page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog), because the dialogs are inside iframes. They get rendered with an offset, too, but not a scrolling offset.
I have to find out where this comes from.

If any of you have an idea how to handle this, feel free to reach out, especially you, Detective @ravindUwU.

Code can be found under https://github.com/JulianDeal/vimium/tree/bug/dialog-fix

**Comment by philc** [comment]
This looks like it's fixed by showing links hints in a popover element, for browsers that support popover (Chrome, soon Firefox): 412cc37621a578ee260925f31e0722539af33f39
