### ISSUE TITLE
Opera 55 "Enter" key stopped working if checked ignore keyboard layout

### ISSUE THREAD

**Issue by pochka15** [philc/vimium#3099]
![image](https://user-images.githubusercontent.com/24525928/44367753-54a8b080-a4d9-11e8-9324-29c27b6aadf5.png)
After updating my opera to 55 version, _enter_ key does nothing in search box. 
**But!** It works properly if I uncheck   _Ignore keyboard layout_
**And!** I jumped on firefox and it works there.
![image](https://user-images.githubusercontent.com/24525928/44368008-2081bf80-a4da-11e8-82e3-705008271584.png)

**Comment by atehnix** [comment]
+1
Google Chrome 68.0.3440.106

**Comment by leonorbert** [comment]
I also have this problem. Unchecking "Ignore keyboard layout" does fix it, but I like this feature because I often switch between different keyboard layouts.

Google Chrome 68.0.3440.106
Vimium 1.63.3
Windows 8.1

I think this problem only started a couple weeks ago, perhaps with the July 24th release of Chrome 68.0.3440. I don't remember any problems earlier in July or before that.

**Comment by smblott-github** [comment]
I cannot reproduce this, but I'm on Linux.

Could you go [here](https://f.smblott.org/keyboard), hit `<Enter>`, and post back the values you see, please?

**Comment by leonorbert** [comment]
I went to the link and opened the Vomnibar, typed in a query, and pressed enter. This did nothing, so I pressed escape to close the Vomnibar. Then I pressed "enter" while outside the Vomnibar.

Here are the key values, which don't show the "O" key, my query, or my attempts at "enter" while in the Vomnibar:

1 | keydown | ShiftLeft | Shift |  
2 | keyup | Escape | Escape |  
3 | keydown | Enter | Enter |  
4 | keypress |   | Enter |  
5 | keyup | Enter | Enter

Thanks for taking a look at this!

**Comment by smblott-github** [comment]
Good.  Thanks @leonorbert.

So.  The problem is that missing value on line 4, together with [this](https://github.com/philc/vimium/blob/master/pages/vomnibar.coffee#L107) special case.

If `event.key` is "`Enter`", then we should probably just use that.  But we're layering special case on top of special case, and it's all becoming very messy.

**Comment by smblott-github** [comment]
Fixed (I think) in 1.64, which is rolling out now.

**Comment by leonorbert** [comment]
Thanks @smblott-github for the quick fix!

I installed 1.64 and now the enter is working in Vomnibar, even with "ignore keyboard layout" selected.
