### ISSUE TITLE
Need Clarification about Vimium for Company Installation

### ISSUE THREAD

**Issue by chemturion** [philc/vimium#3141]
I have to get my company's permission to download Chrome extensions, and it has raised a few questions I'm hoping someone can help answer (so I can use Vimium at work!):

1. Is the Vimium extension code signed?

2. What is the process for updating these extensions?
- Do these extensions self-update or does a new version of Vimium have to be installed?

3. Is there any data being sent to any third party, and what is the permissions model?
- Often these extensions will have broad permissions to access data across all tabs. What are the permissions required by these extensions?

4. Are you going to use this in IE?
^^^ I know the answer to this one, but I left it in for a good laugh, so please disregard. :)

**Comment by smblott-github** [comment]
> Is the Vimium extension code signed?

The code we upload to the Chrome Store is not signed.

> What is the process for updating these extensions?

One of the three people listed on the Chrome Store must be logged in to Google, where they upload a new version.  In practice, that means me.

![image](https://user-images.githubusercontent.com/2641335/45913348-9609e400-be28-11e8-9145-bc27a21282b1.png)

> Do these extensions self-update or does a new version of Vimium have to be installed?

New versions are pushed by Google to users automatically.  Users receive a notification for major updates, but not for minor updates.

> Is there any data being sent to any third party, and what is the permissions model?

None.  None whatsoever.

(Actually, now that I think about it, there is.  If you use a custom search engine with search completion, then the search engine's completion provider sees your partial queries.  But that only happens if the user configures such a search engine.)

> Often these extensions will have broad permissions to access data across all tabs. What are the permissions required by these extensions?

Vimium needs [lots of permisssions](https://github.com/philc/vimium/blob/master/manifest.json#L29).  These permissions are all required for one or more of Vimium's commands.

> Are you going to use this in IE?

No.

**Comment by chemturion** [comment]
Thank you! My request for Vimium at work is still in process. Currently the security folks have a couple concerns (just FYI.. I'll update this issue and/or close after internal feedback next week):

> "Chrome and Edge extensions have to be signed before they can be published on their respective stores.”
* Our security folks are under the impression that all Chrome Store extensions are signed, so when I told them it wasn't signed, they're a bit confused. Not sure then why they asked in the first place.

> “an adversary could compromise a plugin, add code to send a copy of all data externally (as an example) and then push a new version of the plugin to the web store."
* They're going to investigate if we can prevent or monitor automated updates.

I will update/close this issue after our security people have their meetings. Thanks!

**Comment by rohitkrishna094** [comment]
@aaronkelton 
So what did your security team say? How did you get them to agree? 

Also since then, did you face any problems with Vimium? I am new to vim and was wondering if I could use Vimuim to increase my vim learning time since I spend quite a lot of time browsing as well.

**Comment by aaronkelton** [comment]
@rohitkrishna094  No problems with Vimium. I sent them the information they requested and it got approved. They primarily needed to know that Vimium wouldn't be making calls outside of our network. And then our security team sandboxed the app.

Yes, I would encourage you to use Vimium. It is very helpful!

**Comment by rohitkrishna094** [comment]
@aaronkelton Thank you so much for your reply. I have started using Vimium on my personal computer and so far it has been great.
