### ISSUE TITLE
[Firefox] grey highlight in find mode, followed by locked commands in visual mode

### ISSUE THREAD

**Issue by BiteMyProxy** [philc/vimium#3245]
**Environment:**
Firefox version: 65.0
Host OS: Win10
Vimium version: 1.64.3

**Addons:**
Smart HTTPS
uBlock Origin
Vimium

**Issue:**
After using find mode a grey highlight appears, which locks command functionality after entering visual mode.

**Solution after facing issue:** 
Use the mouse to focus back on the page, which removes the grey highlight, and allows for commands to operate again.

**Steps to replicate:**
1. Search for a word using find mode (ex. screenshot below, highlighting the word issue - the selected word has a grey highlight.)
![image](https://user-images.githubusercontent.com/1900650/52739970-48387880-2f8f-11e9-9c3f-2d43f0ba661a.png)
2. Immediately go into visual mode.
3. Attempt to use a command.

**Workaround:**
    1. Use find mode to search for a word.
    2. While the word still has grey highlight press n or N to change focus back to orange highlighting.
    3. Visual mode should now be operational.

**Additional troubleshooting:**
Disabled addons
Replicated steps across multiple types of websites
Wasn't able to replicate in Chrome
Able to enter visual mode first > use mouse to highlight > commands work

*edit*
Cleaned up formatting

**Comment by rwehe** [comment]
I also have this problem @BiteMyProxy

**Comment by BiteMyProxy** [comment]
**After further testing:**
figured out sites such as marketwatch.com, when searching for a word that is a URL, works as intended. Haven't been able to replicate a working use-case on other sites yet.

**Comment by gdh1995** [comment]
Firefox seems to blame for it.

Vimium creates a `<iframe>` to let users type query words and find them, but Firefox thinks you will not need normal highlighting on the main page (the parent frame of `<iframe>`) since the focus has moved away.

I've searched using Google, but no solution found. I'll read the source code of Firefox for potential tricks, if no other ideas can be proposed this week.

**Comment by leonorbert** [comment]
I just started using Firefox 69 instead of Chrome and I'm having this problem with Find --> Visual Mode --> commands locked. The suggested workaround is helpful, but I had to modify it slightly to work for me.

* Search for a word in find mode. Press enter to close the find box.
* Press n or N *twice* to move the *orange* highlighted text. If you do one of each you get back to the original location. This requires a second search selection, it can't be unique.
* Enter visual mode and the highlighting changes to blue. Commands work normally.

**Comment by gdh1995** [comment]
It seems that Firefox 69 has allowed orange as background color even when a frame has no focus - tested on Firefox 69 stable x64 for Win 10.

**Comment by norbert-op** [comment]
It's still a problem on Firefox 69 though, at least for me. I switched to your Vimium-C branch and that allows me to enter visual mode immediately after a search without locking up. I have Windows 8.1 x64.

**Comment by gdh1995** [comment]
@BiteMyProxy Well, I'm sorry that I didn't completely understand your issue, and only answered the first problem about colors for selection text. Today I've confirmed that the bug of locking visual mode does exist.
