### ISSUE TITLE
What are frames ?

### ISSUE THREAD

**Issue by Fandekasp** [philc/vimium#3269]
Can you elaborate on what frames are supposed to be and regular usage of keys like `gf` ? I've tried this shortcut on several websites, but they all have just a single frame, which makes the feature a bit useless.

Thank you for the details

**Comment by smblott-github** [comment]
Many websites have just a single frame, so your experience isn't that unexpected.

A frame, most commonly these days an [iframe](https://www.w3schools.com/tags/tag_iframe.asp), is essentially an (almost) independent page within a page.  It's a separate HTML/DOM and Javascript page rendered within another page.

Here's an example with an old fashioned [frameset](https://www.quackit.com/html/templates/frames/frames_example_2.html).

For Vimium, frames are important because only one frame has the focus, and keyboard events (e.g. scrolling) are sent to that frame.

I find that `gf` is only sometimes (quite rarely) useful.  On Twitter, for example, after scrolling a bit, you can end up with a hundred iframes, and `gf` is useless.  `gF` is **very** useful though.  It returns the focus to the main/top frame (which is usually the one you want to scroll).  In fact, I bind `gF` to `#` for quick use.

**Comment by Fandekasp** [comment]
I see, many thanks for the detailed explanation !
