### ISSUE TITLE
Pressing "z" then "x" will still activate "close tab" action even when "x" hotkey is disabled.

### ISSUE THREAD

**Issue by davionboy** [philc/vimium#3271]
I have disabled "x" hotkey for all websites (.*) and have tested that pressing "x" by itself will not activate the "close tab" action.

However, if I press "z" and then "x' (doesn't have to be simultaneously, as long as "z' is pressed and the next key you press is "x", "Close Window" action will be executed.

This bug also works for "X" (reopen closed tab)

Steps to reproduce:
1) Press "z"
2) Press "x"
^"Close Tab" action will be executed.

extension version: 1.64.5
---
ua
rawUa: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
family: Chrome
major: 72
minor: 0
patch: 3626
device: Other 0.0.0
**os**
string: Windows 10 0.0.0
family: Windows 10
major: 0
minor: 0
patch: 0

**Comment by gdh1995** [comment]
Confirmed.

But I thinks this is just a feature~ but not a bug. This can allow a key mapping of <kbd>Fx</kbd> to work as intended.

**Comment by smblott-github** [comment]
> ... This can allow a key mapping of `Fx` to work as intended.

Correct.  But there's still something wrong here.

The problem arises because `zH` and `zL` are mapped, so Vimium is incorrectly treating the `x` of `zx` as *not* a pass key.  The problem seems to be that we're only disabling the effect of pass keys when we're **exactly** in a clean reset state (see [here](https://github.com/philc/vimium/blob/master/content_scripts/mode_key_handler.coffee#L75).

I think that [this](https://github.com/smblott-github/vimium/commit/3ed13fa2371910a0826abb100fea0959edb703e4) should fix things.

**Comment by gdh1995** [comment]
Okay. Your new method is also acceptable and easy to understand.
