### ISSUE TITLE
Vimium stops working on discarded tabs

### ISSUE THREAD

**Issue by umuluto** [philc/vimium#3382]
When I get low on memory, Chrome discards some of the opened tabs and the Vimium icon is greyed out on those tabs. I have to re-activate Vimium to make it work again.

**Comment by gdh1995** [comment]
Do you mean you have switched to and reloaded the tabs and Vimium was still not working?

**Comment by umuluto** [comment]
Sorry, that was misleading. Reloading those tabs does get Vimium working again.

**Comment by innaterebel** [comment]
This is because when you switch to a discarded tab for the first time to restore it, the content area somehow does not receive focus. You can find all page-oriented keyboard operations such as <kbd>PgUp</kbd>/<kbd>PgDn</kbd> don't work wholly in fact.
So you just make the tab receive proper focus to workaround it, either by:
1. <kbd>Shift</kbd>+<kbd>F6</kbd>
2. <kbd>Tab</kbd> three times
3. Switch tab away and back (via the native hotkeys of Chrome, of course)

Guess you can call it a bug of Chrome and try to report it to Chromium. However as tab-discarding feature has launched for quite some time and this focus issue is noticeable, chances are this had been reported and resolved as WorkAsIntended/WontFix. Still you can try (as I am unable to find an existing issue on [crbug](https://crbug.com/)).

**Comment by zenVentzi** [comment]
> 

neither of the solutions works for me. The focus goes different places but vimium does not resume working and I need to refresh the page
