### ISSUE TITLE
Pressing esc on insert mode on a fullscreen application exits fullscreen first

### ISSUE THREAD

**Issue by jzhong92** [philc/vimium#3435]
For example, full screen a Youtube video. Press i for insert mode. Then when I press esc, it exits fullscreen.. It would feel more appropriate, modularly, to exit insert mode first.

**Comment by gdh1995** [comment]
<kbd>Escape</kbd> and <kbd>Ctrl+[</kbd> is always hooked by a browser, so you may add this to key mappings on Vimium Options:

```
mapKey <c-i> <c-[>
```

And then use <kbd>Ctrl+I</kbd> to exit insert mode. Other composed keys usually work, too, if only they're not forced to be hooked by your browser.

**Comment by jzhong92** [comment]
Thank you, it worked. But what is `Ctrl+[` exactly?

I noticed that it exited full screen without the remapping, but, per your suggestion, it can exit insert mode without exiting full screen.

**Comment by gdh1995** [comment]
As far as I know, on the text editor [Vim](https://www.vim.org/), `<c+[>` has the same functionality as `<esc>`, and Vimium inherits it. Chrome also uses this as Escape by default.

BTW, if you have `map <c-[> ......` in your key mappings, then it will be translated as a command, instead of a replacement of `<esc>`, and then `mapKey <c-i> <c-[>` will make `<c-i>` also trigger a command.
