### ISSUE TITLE
Vimium doesn't work on Chromium gerrit

### ISSUE THREAD

**Issue by Gyuyoung** [philc/vimium#3438]
Hello Vimium maintainers,

I've been using this awesome extension well. Thank you so much. BTW, recently Vimium doesn't work on the Chromium Gerrit after it updated. Could you please make it work on the Gerrit?

URL: https://chromium-review.googlesource.com/q/status:open

**Comment by gdh1995** [comment]
What version of Chromium and what's your opearting system ?

**Comment by gdh1995** [comment]
This issue is a duplicate like #3376 and #3366 , and there's a PR for it: #3406 , which is waiting to merge.

The following is an AD: I have a customized version of Vimium: https://github.com/gdh1995/vimium-c , and it can visit all shadow trees in "open" mode. Compared with Vimium itself, Vimium C lacks the `filterHint` mode ("number & text" mode) up to now, but the support is being developed.

**Comment by gdh1995** [comment]
As said in https://github.com/philc/vimium/issues/3484#issuecomment-583795570, this is fixed in #3406, and a new version will be released in 1-2 days.

**Comment by Gyuyoung** [comment]
The updated vimium works on the Chromium gerrit! Thanks for the fix!
