### ISSUE TITLE
[enhancement request] toggle window

### ISSUE THREAD

**Issue by sarnobat** [philc/vimium#3458]
Vimium is incredible. Almost everything I could want is in it. 

But one missing action is to switch between windows. `Cmd + backtick` is painful. 

I have a bad feeling that there are some limitations of plugins preventing you from implementing this.

**Comment by philc** [comment]
Seems reasonable to add as bindable command.

Is there a conventional keybinding for this that exists in Vim, in case we bind it by default?

**Comment by philc** [comment]
After deliberating some more, I'm reversing my conclusion on this, and closing this issue:

1. This is the first time I've heard this request, so it's likely niche.
2. I'm generally skeptical about the usefulness of keybindings like this one. This is the type of keybinding that you want to have defined at the OS level using something like Karabiner, so that it works consistently across all of your applications. It adds insidious cognitive overhead to have a window-switching shortcut defined for Chrome which doesn't work on other apps, because your muscle memory needs to account for that. Vimium has commands for "next tab" and "previous tab", and those commands have this same problem, which is one reason I've never used them. Instead, I've used Karabiner to define Cmd+J and Cmd+K to switch tabs in all applications. While this requires using a modifier, at least this common command is bound to home row keys, and it's consistent across all apps.

Thank you for the idea!

**Comment by sarnobat** [comment]
Thanks for explaining the thought process. Karabiner sounds like it will achieve what I want.

I should say - the next and previous tabs via Vimium is still attractive though maybe I'll end up not using it, as painful as the platform-based one is.

**Comment by drewauff** [comment]
@sarnobat try MacVim..kinda like vimium for you Mac..

**Comment by sarnobat** [comment]
@drewauf - isn't MacVim a text editor, not a web browser? Or am I misunderstanding the range of features of MacVim?
