### ISSUE TITLE
Baidu knows that many links cannot display shortcut keys after pressing F

### ISSUE THREAD

**Issue by OakMolecule** [philc/vimium#3464]
**Describe the bug**
百度知道，按F后许多链接无法显示快捷键，但这些链接可以用鼠标点击
Baidu knows that many links cannot display shortcut keys after pressing F, but these links can be clicked with the mouse

**To Reproduce**
1. Go to URL 'https://zhidao.baidu.com/question/485603071.html'
2. Click on 'f'

Include a screenshot if applicable.
![image](https://user-images.githubusercontent.com/17940262/72202727-cfdb7f80-349d-11ea-87d0-fde0d8fdbaa8.png)

**Browser and Vimium version**
Chrome Version: 79.0.3945.117 (正式版本) （64 位） (cohort: Stable)
Vimium Version: 1.64.6

**Comment by gdh1995** [comment]
This issue is because Baidu Zhidao does not use a standard-compliant way to declare clickable buttons and links, so Vimium can not find enough clues to learn that the two links are clickable.

BTW, the correct title should be "Some links on Baidu Zhidao (a Q&A community for the public) have no hints in LinkHints mode".

**Comment by gdh1995** [comment]
Translation / 翻译：这个是因为“百度知道”本身没有遵守一些网页开发的规范，按钮实现得很随意，导致 Vimium 因为缺少线索而无法认定这两个按钮是可以点击的。

另外，标题中“百度知道”不应该被翻译成“Baidu knows”，因为“百度知道”是一个专有名词。

**Comment by OakMolecule** [comment]
好的，谢谢
