### ISSUE TITLE
Missing imagemap links in current version

### ISSUE THREAD

**Issue by jzekeb** [philc/vimium#3493]
Describe the bug
When hitting f for links, some imagemap links are not labeled.

To Reproduce
Go to http://fjdk.com
Hit f

Notice that none of the links on the right side of the imagemap are labeled.  This has worked for years with Vimium.  The site hasn't changed in a couple of years, either.

Vimium version 1.65.2
Version 79.0.3945.130 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/3065488/74269673-75695500-4ccf-11ea-9a87-3138a6d0b72b.png)

**Comment by magios** [comment]
issue still exists in firefox and vimium 1.65.1

**Comment by philc** [comment]
@gdh1995 you got this working on vimium-c? Would you be up for porting your changes to Vimium?

**Comment by gdh1995** [comment]
OKay, I'll take a try tonight.

**Comment by lydell** [comment]
@jzekeb Just out of curiosity, do you have an example site that you visit sometimes and that uses image maps? (I’m guessing you don’t visit fjdk.com regularly?) I haven’t stumbled upon any image maps in years.

**Comment by jzekeb** [comment]
I do.  ;)  That's my personal homepage.  And yes, I set up that original imagemap about 20 years ago.

**Comment by philc** [comment]
This will be fixed in v2.0 with 5f415a0882ba83df1ce22555c79ca0e1be05f0e6. Thank you for waiting.

@jzekeb I notice your personal homepage has been redesigned and no longer has an image map, so I tested on a previous version of your site [here](https://web.archive.org/web/20150322081511/http://fjdk.com/). Hopefully Vimium's broken support for image maps wasn't the reason you changed it -- I really enjoyed the retro version!
