### ISSUE TITLE
[Nightly regression / 20200519] Vimium causes pages to fail to load

### ISSUE THREAD

**Issue by ronjouch** [philc/vimium#3569]
**Describe the bug**
Since Tuesday May 19 2020, all pages fail to load if Vimium 1.66 is enabled.

**Steps to reproduce**
1. Enter an address in the url bar
2. Press enter

**Expected**: page loads.

**Actual**: spinner spins, and page never finishes loading.

![vimium-causes-pages-to-fail-to-load](https://user-images.githubusercontent.com/522085/82399487-3e6bb380-9a23-11ea-8d2e-44d72e3e8135.gif)

**Browser and Vimium version**

- Nightly 78.0a1 (2020-05-19), fresh profile with zero conf and zero addon (except for Vimium)
- Vimium 1.66

**Comment by gdh1995** [comment]
Reproduced on http://ftp.mozilla.org/pub/firefox/nightly/2020/05/2020-05-19-16-05-49-mozilla-central/firefox-78.0a1.en-US.win64.zip, Vimium master (fbddc22) , and all web pages ... with an empty user data folder.

Seems a bug of Firefox nightly, although some other extensions do work there.

I guess it may be because of some DOM operations during page loading.

**Comment by s-marios** [comment]
Affected by this. 
Firefox nightly 78.0a1 (2020-05-19) on Linux.
Vimium-FF version 1.66 updated March 3 2020.
Since I'm using an older version of the plugin, I guess this is a change on nightly's side. 

All other extensions are working fine. Can provide info if necessary. Waiting with baited breath.

**Comment by s-marios** [comment]
There was a new Nightly version out, and it seems fixed right now. Anybody else cares to confirm?

**Comment by ronjouch** [comment]
Yup, for me too, fixed in 78.0a1 (2020-05-20) (64-bit)

**Comment by gdh1995** [comment]
According to my tests, the version of Firefox hangs when an extension's `manifest.json` requests to inject CSS files on `document_start` in its `content_scripts` field - apparently it's a bug of the Firefox.
