### ISSUE TITLE
Problem installing in Firefox 

### ISSUE THREAD

**Issue by pwlodawi** [philc/vimium#3695]
I'm trying to install in Firefox 78.3.1(32bit). After I accept permissions I get the following error
![vimium_fail](https://user-images.githubusercontent.com/49796436/96924981-c31b9b80-14b3-11eb-89cc-15080ed59888.png)
The message says: Add-on "Vimium" can not be installed because Firefox is not able to modify required file.

When I do Load Temporary Add-on it  loads and seems to work fine.
Any clues what could be the cause of the problem or how to troobleshoot further ?

**Comment by kamkudla** [comment]
The problem arises because the Extension ID is not explicitly set in the `manifest.json` for the Firefox build in the `browser_specific_settings` key and Firefox requires this. The `application` key as used for the temporary debug version is ignored when trying to install an `.xpi` or `.zip`. I'm submitting a PR on this.

**Comment by philc** [comment]
I believe this is fixed in 8e3c529af78423fe37e94c404286313a7a8220a5 and f5a14083fe45049e0d5b06be5b4dcff9feacca39 as part of v2.0. We can now generate a firefox-specific manifest during development with `./make.js write-firefox-manifest`
