### ISSUE TITLE
Vimium transparency not working with Github Dark mode

### ISSUE THREAD

**Issue by aotarola** [philc/vimium#3732]
**Describe the bug**
When using vomnibar or the search function in Github with Dark Mode activated, it displays a white background. It seems that transparency gets messed up somehow 🤔  

**To Reproduce**
1. Go to https://github.com/settings/appearance and activate `Dark` mode
2. Use either the vomnibar or hit `/` to open search box.

 ## Vomnibar

![Screen Shot 2020-12-21 at 12 04 13 PM](https://user-images.githubusercontent.com/1557740/102807929-3000c400-4385-11eb-9226-8abe2662c114.png)

## Search function

![Screen Shot 2020-12-21 at 12 04 00 PM](https://user-images.githubusercontent.com/1557740/102807931-30995a80-4385-11eb-8cd2-02e9bfd0fcd1.png)

**Browser and Vimium version**

Chrome Version: 88.0.4324.50 (Official Build) beta (x86_64)

Vimium version: 1.66

**Comment by gdh1995** [comment]
This works as intended, because GitHub (or any other website)'s styles should not affect Vimium UI.

Vimium now has a dark mode following a system's dark mode, but this feature is not released as a new version yet.

**Comment by aotarola** [comment]
Great to know that Vimium will soon have a dark mode 😄 

Just curious, so it works as intended, then what causes the white background to be displayed (or the lack of transparency rather)? 🤔

**Comment by gdh1995** [comment]
Well, this issue is because:
* Recent versions of browsers, like Firefox, Edge and Chrome, have supported pages' "dark mode" and elements' "color-scheme"
* `color-scheme: dark`, which is used by Github Dark mode, will cause the transparent area white
* But this can not be worked-around by Vimium's `CSS for Vimium UI`, because the CSS text won't be applied to Vimium's iframe shadow trees.

Up to now, the fastest way is to modify Vimium's CSS file (as said in https://github.com/philc/vimium/issues/3452#issuecomment-748420873), add `.vimiumUIComponentVisible { color-scheme: light; }`, and restart your browser.

**Comment by aotarola** [comment]
I see, thanks for the explanation 👍🏼

**Comment by weeebdev** [comment]
> Well, this issue is because:
> 
> * Recent versions of browsers, like Firefox, Edge and Chrome, have supported pages' "dark mode" and elements' "color-scheme"
> * `color-scheme: dark`, which is used by Github Dark mode, will cause the transparent area white
> * But this can not be worked-around by Vimium's `CSS for Vimium UI`, because the CSS text won't be applied to Vimium's iframe shadow trees.
> 
> Up to now, the fastest way is to modify Vimium's CSS file (as said in [#3452 (comment)](https://github.com/philc/vimium/issues/3452#issuecomment-748420873)), add `.vimiumUIComponentVisible { color-scheme: light; }`, and restart your browser.

It doesn't work for me anymore
