### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by Semro** [philc/vimium#3738]
Since a lot of web pages have a dark theme it's good for Vimium to have that too. Opening vomnibar or help page on the dark page is painful.

**Comment by qx-775** [comment]
Have you tried reading the wiki? It is possible to theme vimium using custom themes https://github.com/philc/vimium/wiki/Theme
There is a dark theme included. Just copy paste into the CSS pane, just go to Vimium options -> Show Advanced Options ->  Paste in CSS for Vimium UI

**Comment by Semro** [comment]
Thank you!

There is another problem that I am encountering on GitHub dark layout. Vimium UI elements background are white:
![image](https://user-images.githubusercontent.com/3332159/103465901-ff3f6800-4d50-11eb-9bd0-86a2b708c901.png)
OS: Windows 10
Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Vimium 1.66

The solutions found so far:
Add style:
```css
iframe.vimiumUIComponentVisible {
    color-scheme: none;
}
```
(what can't be done through Vimium custom CSS)

or with some other extension make the same change to the html element of the GitHub page.

**Comment by BachoSeven** [comment]
@Semro 

Regarding the dark theme: in addition to the already present possibility for manual  theming, [this](https://github.com/philc/vimium/pull/3595) PR implemented a global dark mode for vimium which respects the CSS `prefers-color-scheme: dark`,  set by the OS.  The feature has not been released in a new version yet, but you use the master version.

Your second issue is the same as #3732, [this](https://github.com/philc/vimium/issues/3732#issuecomment-749997600) comment has the solution as yours :)

Feel free to close this if your issue is solved.

**Comment by J-Kappes** [comment]
I like the built in dark theme but I'd also like to resist fingerprinting. Is there an easy way to set it independently of `prefers-color-scheme: dark`? If not, could it be easily implemented, or is there a one-to-one custom CSS replacement for it?
