### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by FranklinYu** [philc/vimium#3746]
Last release is almost a year ago. #3595 would be very nice for many users.

**Comment by josalhor** [comment]
Is this project abandoned? Last comment was over half a year ago and I don't see any other branches.

**Comment by philc** [comment]
Not abandoned — just busy. Yes, we should cut a new release. I'll look into this in the next 10 days.

**Comment by Songkeys** [comment]
@philc any chance to publish a new version? we're still waiting for it

**Comment by NightMachinary** [comment]
@philc @gdh1995 Perhaps the main fork should be Vimium C and this original branch should be in maintenance mode? Vimium C has more than 5k more commits and is under active development. It has fixed bugs left unfixed here for months (e.g., using `J` on unloaded tabs, the alt key on macOS). I don't know what advantage vanilla Vimium currently has over that fork, but I imagine it should be much faster to send PRs over there than to make this branch match the development there.

**Comment by gdh1995** [comment]
@NightMachinary I'm glad that you noticed Vimium C, but I have to admitted that **it's not a "main" fork**. I write Vimium C just because I want more and more commands, detailed logic and options, but (up to now) I don't promise that Vimium C will get well tested because I release new versions. In fact, I'll just open a fresh Chrome and Firefox and manually test basic functions of LinkHints, Vomnibar, find HUD, help dialog and tab switching.

Its commit count is not so import - I wrote lots of tiny commits of only 1~10 lines.

Vimium's advantages compared with my Vimium C:
1. Vimium's LinkHints works across all iframes, including those of 3rd-party websites. While Vimium C will only show hints in a group of iframes of "a same origin" and provide a hint marker to focus a 3rd-party iframe instead
2. Vimium's Vomnibar has auto-completion: it requests online services like Google search engine to get completion results of user query and then shows them as Vomnibar suggestions. While Vimium C doesn't send web requests, so it can not provide such auto-completion.

BTW, Vimium C also welcomes PRs - my rest time is getting less this year.

**Comment by Davidgithub1** [comment]
> Is this project abandoned? Last commit was over half a year ago and I don't see any other branches.

Hey! Has anyone tried Vimium C - All by Keyboard and can tell me the differences?
https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en

**Comment by gdh1995** [comment]
It adds many new command options, and a few new commands, to implement what I (and some users) want, like clickable CSS selectors in LinkHints, better regexp finding, parsing queries in search result pages and browser-level shortcuts.


It lacks:
* singleton LinkHints across same-origin and 3rd-party frames in Vimium (Vimium C only supports LinkHints across same-origin frames)
* auto-complement for query words in Vomnibar - Vimium C won't send user queries to search engine services like Google or Bing, so it can't do so.



---Original---
From: ***@***.***&gt;
Date: Sat, May 15, 2021 01:37 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [philc/vimium] Cut a new release? (#3746)




  
Is this project abandoned? Last commit was over half a year ago and I don't see any other branches.
  
Hey! Has anyone tried Vimium C - All by Keyboard and can tell me the differences?
 https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en

**Comment by gliptak** [comment]
https://github.com/philc/vimium/releases/tag/v1.67.1 was tagged although doesn't seem to be made available at Chrome Web Store
