### ISSUE TITLE
How do I assign some Chrome hotkey as an action?

### ISSUE THREAD

**Issue by NightMachinary** [philc/vimium#3788]
I want to make pressing `.` in normal mode enter fullscreen (presentation) mode, which can be done using `Shift-CMD-F`. I have tried:
```
map . <c-s-f>
mapKey . <c-s-f>
```

The first one complains about the command not existing, and the second one says:
```
Error: The key "." has been mapped to another key: <c-s-f>.
The related option "Ignore keyboard layout" is disabled
```

PS: I know `c-s` is probably not `cmd+shift`, but I got stuck at this first step. What is the proper modifier code?

**Comment by gdh1995** [comment]
> assign Chrome hotkey

No, there's no way to do so with web-extensions.

> enter fullscreen

Vimium and Vimium C don't have such a command, although it is indeed possible to add it. However, there seems no API to implement what your browser does - If you want Vimium C to tell Chrome exit fullscreen, then Chrome will always give a current window "state=normal", but not a `state=maximum` before entering fullscreen.

> `c-s` is not ...

`c-` is Ctrl/Control, and `s-` is Shift. `a-` is Alt/Option. `m-` is Win/Command.

==== 

BTW, according to the tip text, are you using Vimium C ?

> `Command "..." doesn't exist!`

It's because `map` only maps a key sequence to a command with zero or some options: like `map . createTab`

> `The key "." has been mapped to another key: <c-s-f>.`

It seems that you have a second `mapKey` which is not shown in the code block. This error means two `mapKey` lines have a same source key.

**Comment by NightMachinary** [comment]
> BTW, according to the tip text, are you using Vimium C ?

? Yes, I am using this fork.

> It seems that you have a second mapKey which is not shown in the code block. This error means two mapKey lines have a same source key.

You're right, I had this mapped in my Persian->English mappings, even though it was redundant.

Thanks. Feel free to close the issue.

**Comment by gdh1995** [comment]
Um, it's an issue of Vimium, so I have no permission to close it. You may close it manually since there's no good way to exit fullscreen.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 18, 2021 20:41 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [philc/vimium] How do I assign some Chrome hotkey as an action? (#3788)




  
BTW, according to the tip text, are you using Vimium C ?
  
? Yes, I am using this fork.
  
It seems that you have a second mapKey which is not shown in the code block. This error means two mapKey lines have a same source key.
  
You're right, I had this mapped in my Persian-&gt;English mappings, even though it was redundant.
 
Thanks. Feel free to close the issue.

**Comment by NightMachinary** [comment]
@gdh1995 Sorry, I got the wrong repo. 🤦 I'll close the issue.
