### ISSUE TITLE
Allow link hints to stay active, even across page loads

### ISSUE THREAD

**Issue by 74yy48** [philc/vimium#3792]
Is there any way we can keep LinkHints Active, I mean the functionality of the f key, every time for navigation I've to press the f key. Can't it stay active all the time? Or maybe if I can use this f key to activate or deactivate the link till I finished with them.

**Comment by gdh1995** [comment]
Do you mean the command named "`LinkHints.activateModeWithQueue`"?

**Comment by pimlottc** [comment]
> `LinkHints.activateModeWithQueue`

I'm having trouble finding any documentation on what this command does, it doesn't seem to be documented anywhere?

**Comment by C-Loftus** [comment]
Has anyone found a way to implement this functionality?  I was looking for a way for the tags to always be visible even on a page refresh ( without needing to press the f key again). The aforementioned options don't seem to provide this functionality if I am understanding correctly

**Comment by fzadow** [comment]
I'd love this, too! I imagine hitting <s-f> to toggle and then having LinkHints stay active (even on new pages!) until I hit <ESC>. This would make navigating so much easier.

**Comment by philc** [comment]
I believe the common use case for general browsing is to read and scroll the page before navigating a link. Having link hints active on page load impedes both of those tasks (you'd have to exit link hints mode to remove link hint noise on the page, or to scroll).

For single page web apps, I can see how navigation would be the primary action and this would be useful. #2197 is tracking this use case directly.

I'm closing this for now because I think both are niche use cases, and difficult to implement correctly in Vimium.
