### ISSUE TITLE
Support vi editing in textfields

### ISSUE THREAD

**Issue by phoerious** [philc/vimium#389]
This is just a suggestion. I'm not sure myself how to properly implement this as it seems to force some heavy modifications to textareas and input fields (and could easily cause incompatibilities with on-site JavaScript).
The idea is that a textfield is in command mode by default, which enables me to jump through the text by using vi/vim keys. i toggles to insert mode, which behaves like a normal textarea, ESC goes back to command mode. In command mode, v starts the visual mode for selecting passages. Just the way, vim works.
i vs. I and a vs. A for different insert and append modes could also be implemented.

I know, this is very complex and maybe it can't be implemented, but it as a suggestion. I'll think about it and it's implementation myself the next days.

**Comment by rrsahutwo** [comment]
That is why our company has insurance strategy employees in the get in touch with who also provide the features of insurance strategy features. So you do not worry about the mess of your items or house goods.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
For the protection of the items, it's a wise idea to pay for such type of alternatives. These will pay you the variety of benefits with the alternatives. If you are waiting for moving for your house moving, don’t forget to try our efficient alternatives provided by expert experts in moving alternatives to the utmost securely of your items.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
While moving and moving from one position to another, one main factor always strikes in our mind and this is the problem keep during the moving of all that large things. Home and workplace moving process become more annoying, if one has to do all the perform alone. This is really a tedious process but now now intensive process have become very simple because of the existence of packers movers Bangalore . They are perfect remedy to solve your issues which comes during packaging and moving from present property to a new one.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Dealing in new area is already a stressful process. Movers and packers in Bangalore help you to settle in your new area, by providing their best alternatives. They provide exact alternatives of moving issues. Process of moving is not simple, as we have to shift not only simple things clothes but have to handle much sensitive and large things too like digital items, glass items, etc.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
