### ISSUE TITLE
“Hover” to see link/anchor URL target

### ISSUE THREAD

**Issue by babramczyk** [philc/vimium#3893]
I know there’s a way to hover an element.

However, that doesn’t seem to put the URL of anchor tags in the bottom right of a window, like hovering a link would:

![image](https://user-images.githubusercontent.com/16885191/130410792-a0a0fb55-85e0-4bef-8c29-f6f0ddd1687c.png)

Wondering if this is possible currently, or could be supported / Chrome has an API for this.

Thanks! 😀

**Comment by gdh1995** [comment]
no, there's no API to do so.



---Original---
From: "Brett ***@***.***&gt;
Date: Mon, Aug 23, 2021 15:53 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [philc/vimium] How to see link’s target (#3893)




 
I know there’s a way to hover an element.
 
However, that doesn’t seem to put the URL of anchor tags in the bottom right of a window, like hovering a link would:
 

 
Wondering if this is possible currently, or could be supported / Chrome has an API for this.
 
Thanks! 😀
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by babramczyk** [comment]
Ah, bummer

Thanks for the response 🙂
