### ISSUE TITLE
[Bug] Vimium conflicts with Web Search Navigator

### ISSUE THREAD

**Issue by kleenkanteen** [philc/vimium#3912]
**Describe the bug**
Look at my last issue comment here: https://github.com/infokiller/web-search-navigator/issues/307

**To Reproduce**
1. Set this as your key mappings
```
# Insert your preferred key mappings here.
unmapAll
map l scrollDown
map u scrollUp
map m scrollLeft
map i scrollRight
map gg scrollToTop
map G scrollToBottom
map n scrollPageDown
map e scrollPageUp
map w reload
map jj copyCurrentUrl
map t LinkHints.activateMode
map T LinkHints.activateModeToOpenInNewTab
map 3 goBack
map 4 goForward
map f previousTab
map p nextTab
map bp visitPreviousTab
map 1 moveTabLeft
map 2 moveTabRight
map ? showHelp
map gs toggleViewSource
map d duplicateTab
map b Vomnibar.activate
```
2. Install web search navigator and use some mappings with 7 8 9 and 0. The ones with 7 8 9 won't work on google search page.

3. Disable vimium and now the ones with 7 8 9 work.

Include a screenshot if applicable.

**Browser and Vimium version**

Chrome: Version 93.0.4577.63 (Official Build) (64-bit)

Vimium: 1.67

**Comment by gdh1995** [comment]
&nbsp;It's a feature since Vimium supports count prefix and treat 2x as "running command mapped to 'x' twice".



---Original---
From: "Sabih ***@***.***&gt;
Date: Thu, Sep 16, 2021 07:17 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [philc/vimium] [Bug] Vimium conflicts with Web Search Navigator (#3912)




 
Describe the bug
 Look at my last issue comment here: infokiller/web-search-navigator#307
 
To Reproduce
 Steps to reproduce the behavior:
  
Set this as your key mappings 
 # Insert your preferred key mappings here. unmapAll map l scrollDown map u scrollUp map m scrollLeft map i scrollRight map gg scrollToTop map G scrollToBottom map n scrollPageDown map e scrollPageUp map w reload map jj copyCurrentUrl map t LinkHints.activateMode map T LinkHints.activateModeToOpenInNewTab map 3 goBack map 4 goForward map f previousTab map p nextTab map bp visitPreviousTab map 1 moveTabLeft map 2 moveTabRight map ? showHelp map gs toggleViewSource map d duplicateTab map b Vomnibar.activate   
 
Install web search navigator and use some mappings with 7 8 9 and 0. The ones with 7 8 9 won't work on google search page.
 

 
Disable vimium and now the ones with 7 8 9 work.
 
 
Include a screenshot if applicable.
 
Browser and Vimium version
 
Chrome: Version 93.0.4577.63 (Official Build) (64-bit)
 
Vimium: 1.67
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kleenkanteen** [comment]
Can I disable this?

**Comment by gdh1995** [comment]
you may use exclusion rules



---Original---
From: "Sabih ***@***.***&gt;
Date: Thu, Sep 16, 2021 14:42 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [philc/vimium] [Bug] Vimium conflicts with Web Search Navigator (#3912)




 
Can I disable this?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kleenkanteen** [comment]
I tried adding this rule and pressed save: 

`https?://www.google.com/search?q=* and 67890`
also tried 
`https://www.google.com/search?q=* and 67890`

None work. Is this correct?

**Comment by kleenkanteen** [comment]
Does this work for you?

**Comment by gdh1995** [comment]
`Pattern` should look like a RegExp, so your rule is wrong.

A correct one is `https?://www.google.com/search\?q=*`.

`https?://www.google.com/search` also work.

**Comment by kleenkanteen** [comment]
Ok that solves it, thanks.
