### ISSUE TITLE
Feature Request: Fuzzy Search in Omnibar

### ISSUE THREAD

**Issue by aheinous** [philc/vimium#3939]
I think it's pretty obvious why I want this. Same reason it's so great in Sublime Text and VS Code. Say, for example, I wanted to go to a page somewhere on `embeddedartistry.com` . I might, for example, type `em` and get a large number of results, all starting with `embeddedartistry.com`, and the one I want is way down at the bottom, or not even on the list yet.  I either have to type `beddedartistry.com/` etc. or scroll through the whole list. 

Fuzzy search saves a lot of typing. Say, for example, I wanted to go to `https://embeddedartistry.com/course/heapless/`, I could likely just type `emhe` and be done with it.

**Comment by gdh1995** [comment]
You may type "em he" (a space to sllit query into two words)



---Original---
From: "Alex ***@***.***&gt;
Date: Sun, Oct 17, 2021 10:01 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [philc/vimium] Feature Request: Fuzzy Search in Omnibar (#3939)




 
I think it's pretty obvious why I want this. Same reason it's so great in Sublime Text and VS Code. Say, for example, I wanted to go to a page somewhere on embeddedartistry.com . I might, for example, type em and get a large number of results, all starting with embeddedartistry.com, and the one I want is way down at the bottom, or not even on the list yet.  I either have to type beddedartistry.com/ etc. or scroll through the whole list.
 
Fuzzy search saves a lot of typing. Say, for example, I wanted to go to https://embeddedartistry.com/course/heapless/, I could likely just type emhe and be done with it.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by reergymerej** [comment]
Totally not obvious!  I've been using this extension forever and just assumed "emhe" would work.
