### ISSUE TITLE
"Open a link in the current tab" function makes the new page not focused on top of the new page

### ISSUE THREAD

**Issue by xiao1201** [philc/vimium#4012]
sometimes when i type the "f" key to open a link in the current tab, the newly opened page wont focused on top of the page, instead, focused on the middle or bottom of the page, which makes me to type "gg" to go to the top which is very annoying. Is there a way to fix this? Thanks!

**Comment by gdh1995** [comment]
Usually this behavior depends on your visited websites - Vimium hasn't done anything related to this.

**Comment by xiao1201** [comment]
> Usually this behavior depends on your visited websites - Vimium hasn't done anything related to this.

Hi thanks for the reply, but why then cliking the link by mouse is ok? that's strange.

**Comment by gdh1995** [comment]
What websites? Any URLs and specific links on which others may reproduce this?

**Comment by xiao1201** [comment]
> What websites? Any URLs and specific links on which others may reproduce this?

Yeah e.g., the linke is: https://ngabbs.com/read.php?tid=30755832&_fp=3

**Comment by gdh1995** [comment]
What links? You may give a screen snapshot and draw a circle around a button. It would help a lot.

**Comment by xiao1201** [comment]
> 



> What links? You may give a screen snapshot and draw a circle around a button. It would help a lot.

oh i'm sorry the previous link cannot be accessed, pls try: https://ngabbs.com/read.php?tid=30737468 and test the page navigator at the bottom.

![](https://files.catbox.moe/77dkr9.png)

**Comment by gdh1995** [comment]
Um, reproduced, but I haven't found what causes this issue.

**Comment by xiao1201** [comment]
> Um, reproduced, but I haven't found what causes this issue.

ok thanks for the effort though, it's not a big deal anyway.

**Comment by gdh1995** [comment]
I've found the root cause. Vimium shows a border box wrapping the clicked element at a "absolute position" - in this case, the position is 4000+ pixels from the top.

The intial process is:
1. on clicking 2/3/4, the page removes most of old page content, so it should has a small height of 120+ pixels
2. then it shows new content without any scrolling request, so you'll be at the top

When Vimium clicks the button, Vimium adds a blue border box at `y = 4000+ pixels`
1. then after the page removes old content, the page still has a large height of 4000+ pixels
2. after a while, new content is added at `y = 0 pixels`, so you'll see its bottom area.

This might be solved, but is too small to make Vimium decide to accept such a change.

You may try my customized version of Vimium, Vimium C (https://github.com/gdh1995/vimium-c), and it works well in this case. It also has many new commands and usages.

**Comment by xiao1201** [comment]
> ok thanks for the effort

ok thank you very much for the help i'll try vimium c then, and i'll close this issue.
