### ISSUE TITLE
Vomnibar and Dark Reader

### ISSUE THREAD

**Issue by Dim-Tim-1963** [philc/vimium#4125]
When I open the Vomnibar (and the Help popup), it follows the site theme set by **Dark Reader addon**, though everywhere in Vimium settings I forced **dark** mode.   I may change the Vomnibar theme manually, but it remembers it until restart only.

My browser: Waterfox, G5.0b2, Vimium C: 1.99.3, Dark Reader: 4.9.57.

**Comment by gdh1995** [comment]
Hello, please re-open this issue in https://github.com/gdh1995/vimium-c/issues, now that your mentioned extension is `Vimium C`

**Comment by gdh1995** [comment]
And this issue seems because it's not "Vimium C's UI follows configuration of Dark Reader", but "Dark Reader forces Vimium C's UI in dark" - however the Vomnibar is in a standalone "iframe" and Dark Reader can not affect it directly.

You may force Vimium C in dark (on all tabs) if you want, by:
![image](https://user-images.githubusercontent.com/5547703/190892161-1952adeb-e81c-4675-9ccf-f94356595862.png)

**Comment by Dim-Tim-1963** [comment]
> ...in https://github.com/gdh1995/vimium-c/issues
Ah, I see, sorry!  The wrong Vimium. :)

**Comment by Dim-Tim-1963** [comment]
> You may force Vimium C in dark (on all tabs) if you want, by:

Yes, I did that, but it seems Dark Reader forces its scheme _after_ Vimium C.

**Comment by gdh1995** [comment]
Sorry I might misunderstand your issue. Could you give more detailed description about what you want, on https://github.com/gdh1995/vimium-c/issues ?

**Comment by Dim-Tim-1963** [comment]
> Could you give more detailed description about what you want

Done! :)  I just want dark theme always (due to my vision issues).
