### ISSUE TITLE
Tabs as links

### ISSUE THREAD

**Issue by ivstog** [philc/vimium#4142]
Is it possible to add a feature to display tabs as links?
I.e. after pressing f key (or another preset key) the tabs are highlighted and can be accessed by the corresponding letter-link.
It was a great feature in some of the similar apps for Firefox...

**Comment by gdh1995** [comment]
Vimium can not show UI on an area which doesn't belong to a tab's content, because it's a natural limitation of Chrome's web-extension features. You may use the command of `Vomnibar.activateTabSelection` to select tabs on Vomnibar, and its default mapped key is `T` (<kbd>Shift</kbd> and <kbd>T</kbd>).

**Comment by ivstog** [comment]
Ah, ok then. If there are principal limitations lets close this ticket.

**Comment by gdh1995** [comment]
This comment https://github.com/gdh1995/vimium-c/issues/565#issue-1160061740 mentioned such an extension: https://chrome.google.com/webstore/detail/fullscreen-tab-bar/hlackdnjlfblchoenkpcbbophehmeijb?hl=en , though I think it's not well designed and cost too much CPU.
