### ISSUE TITLE
Shift+F Opens two Tabs Instead of One

### ISSUE THREAD

**Issue by bhagwad** [philc/vimium#4194]
**Describe the bug**
Pressing Shift + F to open a link in a new tab now opens two tabs instead of one.

**To Reproduce**
1. Press Shift + F
2. Hit the alphabet combination for the link you want
3. It should open the link in a new tab. Instead, two new tabs are opened with the same URL

Include a screenshot if applicable.

**Browser and Vimium version**
Firefox 108.0.1
Vimium version: 1.64.6
OS: Windows 11 . Windows_NT 10.0 22621

**Comment by mbatson** [comment]
I also encountered this problem today when I installed Vimium on a fresh Firefox installation. This is actually an old bug that had been fixed in the past.

I'm sure Phil will correct me if I'm wrong, but it seems what's happened is that the version of Vimium being offered by the Firefox add-on store has suddenly been rolled back several versions (specifically, version 1.64.6) to before this bug was fixed.

It looks though like Phil has already addressed the problem in #4195, so I assume we just need to wait now for Firefox to put the proper version of Vimium back up in the add-on store, and then download the update 🤞.

**Comment by danilo-alm** [comment]
Yes. It's a Firefox issue, not a Vimium one. No problems installing it through my distro's package manager. Try building it from source

**Comment by mesbahamin** [comment]
For reference, I believe the original bug (fixed in current Vimium, but not the currently out of date version in the add-on store) was #3964.

**Comment by philc** [comment]
Sorry for the confusion everyone. The Firefox team reinstated the latest version of Vimium on the addons store (#4195), so this should now be resolved.
