### ISSUE TITLE
Feature request: warning for closeTabsOnRight and closeTabsOnLeft and closeOtherTabs.

### ISSUE THREAD

**Issue by politicus** [philc/vimium#4248]
Just experienced this: I lost (closed) around 20 tabs I opened since yesterday morning using one of my fine tuned Vimium keyboard shortcut. 

So I was wondering if, besides setting one harder to use keyboard shortcut, there was a way to warn the user to perform a potentially damaging action when using closeTabsOnRight and closeTabsOnLeft and closeOtherTabs.

Thank you.

**Comment by HamzaMateen** [comment]
This would actually be an awesome feature for sure!

**Comment by philc** [comment]
There is functionality in Vimium to warn if a command looks like it has been mistakenly repeated. This warning check only applies to some commands:

openCopiedUrlInNewTab (20)
createTab (20)
duplicateTab (20)
removeTab (20)
restoreTab (20)

closeTabsOnRight and closeTabsOnLeft could be added to that list.

However, this repeat limit was added for the above commands because it almost never makes sense to repeat those commands many times. In contrast, for closeTabsOnRight, you often do want to close a long list of tabs. If you make a mistake, you can recover by (laboriously) using restore tab many times.

So I think it makes sense for the above list to have a repeat limit, but to exclude closeTabsOnRight from this list.

Related: once #4296 is merged, you can implement this yourself by appending a "count=n" to your key mapping. Then, at most n tabs will be deleted.

**Comment by politicus** [comment]
@philc First of all my apologies for my late reply, I am not an expert at using github.com and just didn't you posted one. 

About your answer. Thank you for your complete answer! That completely makes sense and thank you for the hint about "count=n". I see a lot of potential in my daily use!
