### ISSUE TITLE
F doesn't work on google search results

### ISSUE THREAD

**Issue by action-server** [philc/vimium#4303]
**Describe the bug**
When trying to visit a page on the google search results page by hitting the f key and then key for the desired link, nothing happens.

**To Reproduce**
Install Vimium and try visiting a page from the google search results page.

**Browser and Vimium version**
Brave Version 1.57.62 Chromium: 116.0.5845.180 (Official Build) unknown (64-bit)
Vimium Version 1.67.7

**Comment by chanha-park** [comment]
I'm having the same issue.
I found out that it works if I use a label for the icon, instead of the website title.

**Browser and Vimium version**
Chrome Version 116.0.5845.110 (Official Build) (x86_64)
Vimium version 1.67.7

**Comment by Musta-Art** [comment]
I confirm this, Vimium is not working fully on Google search page for some reason, whenever you try to go to the desired link, nothing seems to happen
![msedge_1gVp0AAdIt](https://github.com/philc/vimium/assets/69529761/d3dee6b2-e6ea-4238-b136-214bae3cbb87)

**Comment by mezdelex** [comment]
Definitely, happens to me also.

**Comment by philc** [comment]
I'm suddenly experiencing this today too. I'll take a look.

**Comment by lihuelworks** [comment]
Same here, I logged the F keypress events and they are setting all the events as "isTrusted: false". Maybe Google is now blocking those events?
![image](https://github.com/philc/vimium/assets/49965980/f1cefaf5-3e03-4b9a-a690-5b5762200d90)

Here is the same thing but I'm tabbing to a result and pressing Enter:
![image](https://github.com/philc/vimium/assets/49965980/0ed6598b-d3e5-408e-adeb-7319ed33ce11)

**Comment by atomic** [comment]
not just google search results, even the github post thumbs also have shows fake mirror links where the bottom one does not work
<img width="266" alt="image" src="https://github.com/philc/vimium/assets/5234009/2e6cb93b-ac66-4140-a4c7-f3f1185b89a3">

**Comment by myin-rga** [comment]
Same here. 
**Chrome Version:** 116.0.5845.179 (Official Build) (arm64)
**Viumium Version:** 1.67.7

**Comment by sidouglas** [comment]
On Brave.
Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (arm64)

It appears to be blocked by Brave. But even allowing Google.com does not resolve the issue.

https://github.com/philc/vimium/assets/1107946/b737f0aa-3936-4871-9995-79277d75bfc6

I feel very hamstrung now. I use Vimium daily.
There is https://shortcat.app/ for mac users, but it's clunky in comparison.

**Comment by Dev9133** [comment]
Same here, worked perfectly on a Chromium week old build.
Something changed in recent builds.

**Comment by EvoBloody** [comment]
Same to me. Even though tried this in incognito mode (disabled all extensions but Vimium)

**Comment by philc** [comment]
I took a look. Here are my notes so far, in case anyone has input. I'll return to this tomorrow.

* I personally haven't seen this happen on any page other than Google's search results.
* This is only an issue on Chrome/Chromium, not Firefox. I haven't yet looked to understand why.
* For many search results on Google when the site has a favicon, there is a span tag which contains an anchor tag as a child, and they are sized exactly the same. Vimium generates a hint for both elements. The top hint is for the anchor tag, and the bottom is for the span tag.
* In Chromium, triggering the link hint for the span tag does nothing, but triggering the hint for the anchor tag correctly navigates to the result's URL.
* I don't know why this behavior recently changed in Chrome.
* I haven't looked into whether the isTrusted field that @lihuelworks mentioned is related.

It seems to me that arguably, we should be generating only one hint rather than two for each google search result. I recall there was an issue or PR which discussed this, but I couldn't find it.

I pushed an experimental change (3192274b) which flags clickable spans as potentially false positives, and Vimium will no longer show hints for them if they have clickable descendants. While I think that's conceptually reasonable, it's a large change and may not be a good heuristic for many sites that use span elements as legitimately clickable items which should be handled separately from their clickable descendants.

This change also results in only one hint being shown for each search result, and the hint is shown on top of the result's favicon, rather than the result's title. I think people would expect to see it on the title, so this is probably a regression.

Here's a screenshot of before and after.

Before
<img width="620" alt="before" src="https://github.com/philc/vimium/assets/8598/dd77ae5e-7b97-42f2-bf1f-64fa07194cc6">
After
<img width="599" alt="after" src="https://github.com/philc/vimium/assets/8598/35e10039-695f-41af-89f4-3f70fe927182">

Another option is to revert this span change (3192274b), and special-case Google's results page: if a clickable span is clicked on a search engine results page, then look for a descendant <a> tag and click that instead.

Any thoughts?

@gdh1995 I see this issue currently reproduces on Vimium-C, and I see that you made some related commits recently. Have you looked into it?

**Comment by philc** [comment]
@backstab5983 From Vimium C's current master, I triggered these hints. Clicking on the top one (KJ) for the first result does not navigate to the search result's page. It may be the case that this is expected behavior, but on the surface it looked like a similar issue to me.

<img width="459" alt="image" src="https://github.com/philc/vimium/assets/8598/ee261a67-f11e-4396-85a3-cf42415729d7">

**Comment by ryan-williams** [comment]
Great to see the discussion and progress here, thanks all.

Just want to highlight a workaround (from @philc's [comment](https://github.com/philc/vimium/issues/4303#issuecomment-1713285737) above):

![Screenshot 2023-09-11 at 9 05 15 AM](https://github.com/philc/vimium/assets/465045/528af330-3835-4051-9828-8933bc17f6ac)

"SJ" works here, but "AJ" does not. That is good enough for me, though I appreciate the work going into figuring out why they don't both work, and what the correct behavior should be.

**Comment by philc** [comment]
Update:

* I didn't test this on Brave. It's curious that brave is triggering the popup blocker as per @sidouglas's video. That may be related to the root cause.
* On Chromium, I saw no popup blocked notice when selecting the link hint for the span in the search results. I turned on the Chrome setting "allow sites to send popups and redirects" but this didn't have any effect.

I reverted the previous workaround (3192274) because I just want to narrowly fix this issue.

I've pushed a new workaround in (06a2ceda) which special-cases the google search results page and clicks on the descendant anchor tag in the search results when the user selects the hint for a span.

I don't like special-casing a site, but this should do the trick until the root cause is understood. Maybe this will turn out to be a transient Chrome bug introduced in 116.

Please try out this change. I plan to ship this change to the store tomorrow. I won't release Vimium v2.0 -- I'll create a new patch release on top of v1.67.7.

**Comment by glokta1** [comment]
Now fixed on Brave v1.57.62 Chromium to 116.0.5845.180

**Comment by sidouglas** [comment]
@phil I am no longer seeing issues
* There is no blocking triggered by Brave
* Performing F search works perfectly fine now on google search results.

Wonderful 🎉 !

**Comment by philc** [comment]
This seems to be a fast-moving target as presumably google the HTML for their search results.

While preparing a release, I noticed this morning that on the currently released version v1.67.7, there is now only **one** hint shown per Google search result, and the hint works correctly.

This is the case on Chrome 117.0.5938.62 and Chromium 114.0.5724.0.

Assuming this is the case for everyone, then for now, I will leave the workaround in place for v2.0 and revert it prior to release, and I will forgo making a new release of v1.67 unless the Google hints issue surfaces again.

**Comment by fandy** [comment]
Looks like this is still an issue in the latest version of Brave...

**Comment by Evidlo** [comment]
I'm still seeing this on Google with FF 142 and Vimium 2.3.

Interestingly it only happens with [udm14 AI-free results mode](https://old.reddit.com/r/LifeProTips/comments/1g920ve/lpt_for_cleaner_google_searches_use_udm14/) enabled.

<img width="925" height="398" alt="Image" src="https://github.com/user-attachments/assets/3dd45677-a261-41b8-ad91-79838d3f8ec9" />

https://www.google.com/search?client=firefox-b-1-d&q=napoleon+bonaparte&udm=14

The `AG` hint works correctly, but selecting `G` does not.

**Comment by Drowze** [comment]
Just reporting that I see the exact same behaviour as @Evidlo (strictly when using `udm=14` query parameter as well).

My setup:
- Vimium 2.3
- browser: Brave 1.83.118 (Chromium 141.0.7390.108)
- os: MacOS 15.7.1 (arm)

**Comment by miomao34** [comment]
+1 to @Evidlo and @Drowze, experiencing the same problem.
- vimium 2.3
- firefox 144.0 (64-bit)

**Comment by Osten** [comment]
same at
- vimium 2.3.1
- librewolf 144.0.2
- pikaOS4 x86_64
- &udm=14

**Comment by philc** [comment]
The specific issue with links working only on Google.com's "all" tab is tracked in #4750; I'll move further discussion there.
