### ISSUE TITLE
F to open link in new tab doesn't work on www.wikiwand.com

### ISSUE THREAD

**Issue by eggbean** [philc/vimium#4327]
**Describe the bug**

`F` to open link in new tab doesn't work with links on www.wikiwand.com. The links open on the same tab, just like `f` would do.

**To Reproduce**

1. Go to URL https://www.wikiwand.com/en/Oriel_window
3. Select any link used `F`

**Browser and Vimium version**

Chrome 117
Vimium 1.67.7

----------------------------------
All my Wikipedia visits get redirected to this site, so I use it a lot.

**Comment by eggbean** [comment]
@GianniGi Are you sure you are using capital F and that the page opens in a new tab and not the same one, like lowercase f?

**Comment by GianniGi** [comment]
yes

f works
F works

both work as intended

**Comment by philc** [comment]
I couldn't reproduce this -- it works for me.

**Comment by mcint** [comment]
@eggbean often a relatively approachable way to hunt this is with private mode.
In concept, disable all other extensions in private mode, and then bisect. You may also be able to "disable extension until clicked on" -- I find using private mode helpful because the debugging triage doesn't interfere with my daily use configuration.

**Comment by eggbean** [comment]
Good method, thanks, but in this case it did start working for me correctly at some point without me finding out what was causing it.
