### ISSUE TITLE
'Vomnibar.activateTabSelection' no longer ordering tab list in chronological order (of most recent)

### ISSUE THREAD

**Issue by Baggydawg** [philc/vimium#4368]
**Description**

This has been an issue for the last year or so; my tab history using ⇧ T no longer is in chronological order of last open. Have no idea how the ordering is currently working. But I loved having this shortcut to quickly switch between most-recent, just like ⌘⇥ switches between most-recent applications.

I tried looking in the chrome extension settings and couldn't find anything that might be preventing vimium from configuring the action correctly, with chronologically-ordered tab history, as I had before.

**To Reproduce**

Vomnibar.activateTabSelection – which I have currently set to ⇧ T

**Browser and Vimium version**

Chrome Version: 117.0.5938.92 (Official Build) (arm64)

Vimium Version: 1.67.7

**Comment by tobez** [comment]
This seems to be related to #4326.

It looks like the chronological order is broken even the most recent (as of February 2024) repository version.
It would appear that at the start, when I start switching between tabs by whatever means, the stack is maintained correctly, however, after a brief period of time (less than 5 minutes) it is somehow reset to the default tab order returned by the `chrome.tabs.query({})` call.

It still works correctly in Vimium 1.67.1, so it got broken some time between that and 1.67.7...

**Comment by Baggydawg** [comment]
Thanks for your comment tobez, you expanded on my issue perfectly. That's a shame it's not working on the latest version. Is there a way to downgrade Vimium to version 1.67.1?

**Comment by tobez** [comment]
> Thanks for your comment tobez, you expanded on my issue perfectly. That's a shame it's not working on the latest version. Is there a way to downgrade Vimium to version 1.67.1?

One way to do it:
Deinstall vimium if you installed it from Chrome Web Store.  Then:

```
$ git clone https://github.com/philc/vimium.git
$ cd vimium
$ git checkout v1.67.1
```

In Chrome: ⋮ -> Extensions -> Manage Extensions
Enable Developer mode (at the top right corner).
Load Unpacked (button close to the top left), navigate to the vimium directory you checked out, install.

**Comment by philc** [comment]
@tobez, you gave me the needed clue. If it works at the start, but gets reset with time, it must be the case that the state of tab recency is getting lost when the service worker gets unloaded by Chrome.

Good news: while investigating how to rework that state management, I discovered that Vimium no longer needs to do so because Chrome just introduced the `tab.lastAccessed` property in Chrome 121.

I've created #4431 which should resolve this. Feel free to give that branch a try.

**Comment by tobez** [comment]
Hi @philc, I am glad that you got to the root cause of it;  I've been dreading the moment Google removes manifest V2 support with this unfixed;  I would probably switch to Firefox right the second it happens just to keep Vimium running.

With the current fix, for some reason I am getting

```
Uncaught (in promise) TypeError: rules.filter is not a function
Context
background_scripts/exclusions.js
Stack Trace
background_scripts/exclusions.js:40 (anonymous function)
```

when I try this branch on Chrome Version 122.0.6261.94 (Official Build) (arm64) for Mac.

**Comment by philc** [comment]
Hey @tobez, based on that error log, your settings may have been corrupted by downgrading prior to Vimium 2.0, and then upgrading again (Vimium's version number changed from v1.67->v2.0 because the settings data model was no longer compatible).

Can you try clearing your settings and seeing if you still get that error? You can clear your settings like this:

1. Open `chrome://extensions
2. Click on Vimium's service worker link
3. In the Javascript console for the service worker, run `chrome.storage.sync.clear()`
4. Reload the Vimium extension

**Comment by Baggydawg** [comment]
hey @tobez & @philc – thanks so much for all of that information, super helpful.

@philc I have never actually updated Vimium manually before – and it seems fix #4431 is a separate branch and not yet merged.

Sorry to ask such a basic question but how can I pull that specific branch? I presume I need to checkout to it in the terminal or something? If so, do I need to remove Vimium from chrome entirely and clone the repo on my machine? As I have no idea which directory it would be in.

**Comment by Baggydawg** [comment]
apologies guys ignore the above comment – I followed the instructions to delete from chrome and reinstall via terminal. Checked out the the use-tab-lastaccessed branch and it now works @philc !!!!!!!! thanks so much guys!!!!!!!!!!

**Comment by Baggydawg** [comment]
@philc apologies, after some testing it appears the chronological ordering of recent tabs still resets after a while.

Running on Chrome Version 122.0.6261.112 (Official Build) (arm64) – Mac

I am on [branch](https://github.com/philc/vimium/pull/4431) `use-tab-lastaccessed`, which I checked out to earlier this evening. 

Not sure how to reproduce. It was working earlier as I tested navigating to a bunch of different tabs. Then I went on Slack to send some messages back and forth. After that the chronological tab ordering seems to have reset, showing the tabs in physical order (from leftmost tab to rightmost) inside Chrome.

**Comment by Baggydawg** [comment]
@tobez have you had any success on the `use-tab-lastaccessed` branch?

**Comment by philc** [comment]
@Baggydawg I wasn't able to reproduce the tab order resetting itself after idle time. I let Chrome idle for 10m (with Vimium's service worker JS console closed) and the recency worked as expected.

However, as raised by @tobez, I'm noticing the `lastAccessed` API seems to be broken in several ways. Based on the code review comments [here](https://chromium-review.googlesource.com/c/chromium/src/+/4505903) it may take awhile for this feature to work in all cases without bugs, because there are probably a lot of edge cases to consider when updating this. I don't expect we'll be able to rely on it.

1) On Firefox, the API only has millisecond precision, so the source tab and the destination tab of a visitPreviousTab command will end up having the same `lastAccessed` timestamp. Chrome gives sub-milliseconds precision so the timestamps are different. This is not an issue in practice for Vimium because we always exclude the current tab when deciding which tab to navigate to next.

2) At least on Mac Firefox, when multiple windows are open, every tab that is visible in all windows has its lastAccessed timestamp updated when a tab is changed in any window.

You can observe this by opening the JS console for the Vimium background page in Firefox and pasting this snippet when you have multiple windows open. All focused tabs in every window will have the same lastAccessed timestamp.

    async function test() {
      const sortedTabs = (await chrome.tabs.query({}))
        .sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0));
      for (const t of sortedTabs) {
        console.log(t.lastAccessed, t.url, t.id);
      }
    }
    await test();

3) On Chrome, the active tab in a window sometimes won't get updated. You can observe this by clicking between windows and running the `test()` function above in the JS console for Vimium's background service worker. (You first type "allow pasting" to sidestep the Chrome warning against pasting into the dev console...)

Issues 2 and 3 breaks our use case for this API.

If anyone could help by posting a clean bug report of 2 and 3 on the chrome and firefox bug trackers, that would be very helpful to the cause.

Meanwhile, I'll discard this approach and investigate repurposing Vimium's former implementation in a manifest v3 compatible way.
