### ISSUE TITLE
Vimium doesn't run on firefox's restricted websites

### ISSUE THREAD

**Issue by rajarshikhatua** [philc/vimium#4508]
by default vimium cannot run on restricted website, but if i explicitly allow the extension the permission to "Run on sites with restrictions" or set "extensions.quarantinedDomains.enabled" to false all together in about:config, still the extension refuses to run on those pages.
Is this a bug in firefox itself or vimium isn't recognizing the granted permissions?

**Comment by UncleSnail** [comment]
The restricted domains refer to other websites that firefox deems as risky, not the config pages etc. The addon cannot run on config pages because of Firefox's design. Either of the options mentioned will allow Vimium to run on all external websites, even those Mozilla restricts, but not on the config, addons, etc pages, or pages created by other addons (addons are not allowed to effect each other's pages). IE, it cannot run on "local browser related" pages.
If that is what you mean, this issue can be closed, because everything is behaving correctly.

**Comment by sankl** [comment]
But how Fast Tab Switcher, and "Search Bookmarks, History and Tabs" are able to do it?
