### ISSUE TITLE
Unable to get key for google search results

### ISSUE THREAD

**Issue by vgnshiyer** [philc/vimium#4550]
**Describe the bug**

When I press "f", tool shows keybindings for everything but google search results. Example screenshot below.

**To Reproduce**

1. Open google search results for any query.
2. Press "f"

![Screenshot 2024-10-03 at 2 04 22 PM](https://github.com/user-attachments/assets/63882f08-65ce-497d-92ed-5b9492e3e66f)

**Comment by Sama-004** [comment]
AG would still take you to that page

**Comment by UncleSnail** [comment]
Sama is correct. It's a bit odd that yours looks like that though. Going to exactly the same Google search result for that stack overflow post mine shows the hints over the text for the link itself.
I've seen similar behavior to what you are describing before in various places though, and you'll just need to get used to it. Sometimes the website designers put the clickable element on strange things or places that you aren't expecting, and you just need to figure out which one is the one you want. The picture being the thing that has a hint is actually decently common, so if the link doesn't have one, look for a logo or picture.

**Comment by Sama-004** [comment]
hey @UncleSnail can you help me with one thing. Sometimes when the focus is gone from the page how can we get the focus back using vimium. I have to use mouse for this and it's very annoying

**Comment by UncleSnail** [comment]
I'm not sure completely what you mean. Are you meaning when focus goes to the navbar or tabs? In that case, you can usually push escape, and then tab a few times until focus is back in the page.
If you mean that a different operating system window is focused, the only option is to focus back to Chrome/Firefox. On most "normal" desktop environments I would use alt+tab, but I use a tiling window manager, so on my system I can use the keyboard to easily switch back and forth between applications with something like super+h or super+1 to change workspace.
Or are you meaning something else?
Also note that if you enter visual mode or get selected on a text box and would like to control the page again, you can usually just push escape and control the page again. On pages like the "new tab" which are special pages, there isn't a whole lot of choice since addons aren't allowed to control them (we can't fix that, it's a browser thing), so you need to use built in browser shortcuts like ctrl+tab or ctrl+w to close the tab.

**Comment by Sama-004** [comment]
> Are you meaning when focus goes to the navbar or tabs? In that case, you can usually push escape, and then tab a few times until focus is back in the page.

yeah this is what i meant. Nice hack i used to do this before vimium so i forgot about this thanks..

**Comment by vgnshiyer** [comment]
@Sama-004 Did you mean "Shift + a + g", I tried both with and without shift. It does not open the first link on the search page. FYI: I am using the Arc browser.

**Comment by vgnshiyer** [comment]
@Sama-004 You are right. AG works.

@UncleSnail I know it's kind of wierd that it does not show it on top of the search result. I used to use safari before with Vimlike. That didn't seem to be a problem. 

I am using the Arc browser now.

**Comment by philg-dev** [comment]
@vgnshiyer since your issue seems to be resolved, would you mind closing it?
