### ISSUE TITLE
Feature request: Support for Ctrl + D/U for scrolling actions?

### ISSUE THREAD

**Issue by vgnshiyer** [philc/vimium#4555]
**Describe the bug**

Support for Ctrl + D/U for scrolling actions?

J and K allow scrolling.

Ctrl + D/U allows scrolling faster and used a lot in vim.

PS: Something like this might be cool.

```
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
```

Brings the view pane to the center every time.

**Comment by philg-dev** [comment]
These bindings exist already. The defaults are `d` and `u` without `CTRL`. That's probably been implemented that way as a slight convenience because when browsing websites, you wouldn't really need the normal functionality that "just" `d` and `u` have in vim.

If you want to have it consistent with your vim experience you can just add custom mappings for those half-page scrolls in the "Custom key mappings" section in the Vimium options:
```
map <c-d> scrollPageDown
map <c-u> scrollPageUp
```

**Comment by vgnshiyer** [comment]
Thanks @philg-dev!
