### ISSUE TITLE
Wish: Reverse of J and K for vertical Tabs

### ISSUE THREAD

**Issue by bupd** [philc/vimium#4594]
Since I use vertical tabs. pressing J should move one tab down which is to the right. and pressing K should move one tab up which is in normal tabs moving to the left.

Wish this would be possible.

I currently define this as a custom rule in my config. If we can do this automatically by detecting the presence of vertical tabs would be nice.

BTW, Thanks for your effort on creating and maintaining this.

**Comment by philg-dev** [comment]
You can just change the key mappinge in the Vimium options to swap the functions. These settings might require you to refresh the tabs / restart the browser to fully apply, since open tabs have the content script with the old bindings already injected.

This was also mentioned in:
https://github.com/gdh1995/vimium-c/issues/710
https://github.com/philc/vimium/issues/59

```
map J nextTab
map K previousTab
```

**Comment by bupd** [comment]
@philg-dev Thanks I have done it.

Keep up the good work
