### ISSUE TITLE
Alt Gr and Shift do not work in "Open bookmark" popup window

### ISSUE THREAD

**Issue by oskarkv** [philc/vimium#463]
I have a Swedish Colemak keyboard layout http://img834.imageshack.us/img834/2610/minu.png . I have noticed some problems with it in "Open bookmark" mode. 

In the grey box that appears after pressing 'b' to open a bookmark, I can't use Alt Gr, Shift, ÅÄÖ, periods, commas, etc. Basically only keys that are letters on the American qwerty keyboard layout work correctly, i.e. they have my correct mappings working. But the rest of the keys are the American qwerty mappings, kinda. For example the keys next to Enter is Slash and Semicolon, so not exactly. Anyway, it's totally fubar. And, as I said, Shift and Alt Gr do nothing. 

Note that everything is fine in command mode and in text fields, it's just "open bookmark" mode that has problems.

I have Vimium 1.30, Windows XP, and Chrome 16.0.912.75 m

**Comment by rrsahuone** [comment]
The solutions of packers and movers Companies usually include house shifting, workplace shifting, automobile transportation, pet moving, and other unique specifications. They guarantee moving and shifting of all of your individual products or valuables without any harm / reduction. Bangalore Packers and movers are providing best expert solutions including everything like product packaging, moving, running, moving, unloading etc. unique attention is given on each phase to avoid any accidental harm.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by rrsahuone** [comment]
When you are choosing expert Movers packers Bangalore , more than half of your job is done at some point. You don’t have to take any favor from family associates, friends or colleague for product packaging or moving your belonging. Just sign the cope with some expert Company and keep everything on to them. They will look after everything from cleaning, product packaging to unloading components to new position.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers in Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by rrsahuone** [comment]
Sometimes, it becomes hard getting right expert for right job. Although internet service is there to help you but that is not sufficient. You need other factors too like believe in, stability and stability. How can you believe in someone just because his website is outstanding or he is getting outstanding reviews from customers? Reviews can even be written or posted artificially. Is there any middleman who can guarantee about the Company? Here, we come at the front to take the responsibility that your cope is 100 % safe and effective.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers in Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>

**Comment by rrsahuone** [comment]
We record you with best Packers movers in Bangalore having outstanding popularity and always getting positive feedback from client. They not only help in moving or shifting but also manage most fragile products with highest appropriate care that are most susceptible to damage. These all individual valuables are handled in most expert style by Company.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
