### ISSUE TITLE
Vimium's scrolling does not respect Chrome's native smooth scrolling setting

### ISSUE THREAD

**Issue by lamnatos** [philc/vimium#506]
By going to `chrome:flags`, I've enabled the native _Smooth Scrolling_ setting. This makes Up/Down, PageUp/PageDown & Home/End scroll smoothly, **without using external extensions**.

The same movements when performed via Vimium's shortcuts, are not smooth (as if the setting was never enabled). This breaks consistency with the native behavior.

**Comment by rrsahu** [comment]
During visit, the Company’s representative will also note down the content he required at plenty of duration of product packaging so that it should not break or mishandled during transportation.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
After this, last procedure is to shift products safely to the desired place. Packers and movers will fill the products from old position and it will be unloaded to the new position by Company itself. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
You just have to create sure that you have chosen best cope for you. If you are pleased then keep the rest on product packaging moving group. They will put highest possible initiatives so that you can enjoy your shifting and moving a chance to the fullest without any harm or reduction.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
We record you best packers and movers in Bangalore we create sure that all detailed Information mill 100 % safe, authentic, certified and well-known qualifications. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>
