### ISSUE TITLE
Save images

### ISSUE THREAD

**Issue by heichblatt** [philc/vimium#712]
Is it possible to implement a shortcut for saving images without opening a save dialog window?

**Comment by smblott-github** [comment]
No.  There's no API for that.

**Comment by mvrozanti** [comment]
@smblott-github thanks for the quick response. Maybe there's a way to only download images without opening the context menu? I've seen issues around refering to this use case

**Comment by gregorias** [comment]
Here's how I (partially) address the problem of saving images using LinkHints on Firefox.

I've remapped `F` to [focus an object instead of clicking it](https://github.com/philc/vimium/wiki/Tips-and-Tricks#hovering-over-links-using-linkhints):

```
unmap F
map F LinkHints.activateMode action=focus
```

then whenever I want to save an image, I:

1. Press F and select the image (if it's also a link).
2. Press Shift + F10 to open the context menu.
3. Select "Save Image As."

On Chrome, the Shift + F10 equivalent is apparently [the super key below the R Shift](https://stackoverflow.com/questions/31046321/what-is-right-click-keyboard-shortcut-in-chrome).
