### ISSUE TITLE
Opera 15+ support

### ISSUE THREAD

**Issue by msieradzki** [philc/vimium#930]
Edit (by @smblott-github):  See [this comment](https://github.com/philc/vimium/issues/930#issuecomment-56307712) and the subsequent comments.  Original post follows.....

Opera 15+ is based on Chromium. Has anyone investigated amount of effort required to support it with vimium?

http://dev.opera.com/extension-docs/

I have experimented with opera://extensions and developer mode and extension seems to have loaded properly.

**Comment by bimawa** [comment]
Yea DCE RockS:
First install [DCE](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/)
Then [Vimium] (https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb/related)

**Comment by scanf** [comment]
+1

**Comment by zkanda** [comment]
Showing demand here as well. :+1:

**Comment by rrsahutwo** [comment]
We comprehend the protection of the factors comes under the required the movers not for you. If you seek the services of inexperienced movers and packers, you may have to face an excellent loss because of mess of expensive items during packaging, running or unloading. That is why be careful to seek the services of the well-known packaging and movers and get relaxed from the issues of messing useful items.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment]
Since we aim at providing the most efficient alternatives of transportation, we have a huge group of experts to perform with us for handling all the required deeds. Apart from expert packers, loaders, drivers; we has knowledgeable insurance strategy employees to deal with the required insuring the house keep items and items what you are cared about. Insuring the precious items and items create the owners totally exempt from the issues of damaging the items.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment]
EXPERT Packers has a group of experts who look into the matter concerned about the maintenance and fitness of the automobiles. We don’t let even the small issues go on with any aspect of our automobiles and get them mended soon to make sure the fitness of the automobile. Our new and well handled automobiles have capacity to take your house goods and workplace items to any remote place. If you need the efficient alternatives of Packing Moving Bangalore to take your baggage to any aspect of the nation, you can take the items with confidence. In your need you can also seek the services of our worldwide moving alternatives.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment]
Our worldwide alternatives consist of car carrier & transportation alternatives, parcel alternatives, sea cargo alternatives, insurance strategy alternatives, air cargo alternatives, etc. You need not worry about how you will handle to shift your workplace, house, or company. The only factor our clients require to do is to contact us and tell your need. Let the experts do all the rest.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by bimawa** [comment]
Twitter bots come on github ? :(

**Comment by skywinder** [comment]
:+1:

**Comment by xuen** [comment]
show demand

**Comment by akashnimare** [comment]
DEMAND :100:

**Comment by smblott-github** [comment]
Reopening and adding "Help wanted" label.

**Comment by akashnimare** [comment]
To install this follow -
1. Install [DCE](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/)
2. Go to [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb/related)

@smblott-github @philc I am interested in porting this extension to opera. Can you tell me what exactly needs to be done for this?

**Comment by smblott-github** [comment]
I haven't a clue, @akashnimare.  I think we're looking for somebody to figure it out.  Then we can decide whether Opera is something we can support.

**Comment by akashnimare** [comment]
@smblott-github Just figured out we don't need to do anything different. Should I publish it on opera?

**Comment by smblott-github** [comment]
> Should I publish it on opera?

It's @philc's baby.  His call.

**Comment by philc** [comment]
Thanks for scoping this guys. Let me investigate what it takes to publish
this to Opera's store.

**Comment by dansdantas** [comment]
Any news on that @philc ? Looking forward to shift away from chrome but without vimium it is a big no.

**Comment by akashnimare** [comment]
@dansdantas try this https://github.com/philc/vimium/issues/930#issuecomment-213398760

**Comment by smblott-github** [comment]
Closing.  See [this comment](https://github.com/philc/vimium/issues/930#issuecomment-56307712).

**Comment by rdewolff** [comment]
Using DCE as a few suggested works fine for me!
