### ISSUE TITLE
Ability for web developers to disable Vimium

### ISSUE THREAD

**Issue by vicramon** [philc/vimium#940]
I'd like to be able to disable Vimium on a web app I'm building because it conflicts with key bindings that I would like to create myself. Is there a way to turn it off with javascript?

**Comment by rrsahu** [comment]
We have already set a benchmark of success in product packaging and moving industry. Our successfully finished projects talk about our solutions themselves. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment]
Till plenty of time we started perform, we have never looked back. Our strengths are positive attitude, innovative perform strategy and dedication for our work We help our customers in two ways. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment]
Either we are providing finish information of customers so that you can get in touch with them directly either through phone or email. Secondly we provide you with estimates of most well-known packers movers within Bangalore and you can compare provides from authorized suppliers and get certified vendor now. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment]
In this way, customers are completely involved during the whole procedure. We don’t force you to cope with any particular packers and movers Company. The option is completely yours and decision is up to you only

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by bolasblack** [comment]
@philc I really hope Vimium can provide a way to detect if it has been installed, because some user of my app asked me to resolve the conflicts of key binding (we also using <kbd>j</kbd><kbd>k</kbd> in app)

I think I can change the key like <kbd>C-j</kbd><kbd>C-k</kbd>, but I need to know is it has been install at first.
