### ISSUE TITLE
Add support for image preview via hovering?

### ISSUE THREAD

**Issue by Foxboron** [philc/vimium#950]
I am currently browsing image boards, forums and websites in general, but i use Hover Zoom to preview images.
Since Hover Zoom just requires you to "hover" over the image, shouldnt it be possible to somehow add this into vimium?

This might be too specific to have inside vimium, but i was wondering if anyone have any code solving this or are capable of doing coding this, before i start digging my neck deep inn coffeescript.

**Comment by esperx** [comment]
I would like to necro this feature. I currently use Imagus( https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab?hl=en ) to have this feature with mouse, but it would be really nice to have a hotkey image zoom functionality so I don't have to use the mouse which is why I use Vimium. Image zooming is the only thing making me put my hand on the mouse beside gmail.
