### ISSUE TITLE
Get Vimium Input on new Tab

### ISSUE THREAD

**Issue by casaper** [philc/vimium#979]
Hello

I just didn't find anywhere else to put this, so please point me elsewhere if there is a better place for this.

How can I get vimium input on a new tab opened. I tryed to set alternate NewTab pages, but this didn't help. I still get the focus in the Location bar, and cant get out of there.

Thank you in Advance for hints on this.

**Comment by craigforr** [comment]
I searched and searched for a way to achieve two goals:

A. Vimium operable for new tabs (e.g., via `Ctrl-T`).
B. A *fast* load page load.

There are extensions that would make one or the other of these work, but I couldn't find any that would make **both** happen.  I could either get Vimium to work, but have to wait for a slow loading page (anything over a split second is unacceptable), or get a lightning fast page load that required navigating somewhere *else* before I could use Vimium.

In the end I was able to make both happen... Here are the steps I took:

1. Create a new directory somewhere on the local system that Chrome can get to.
2. Create new file in that directory (e.g., `newtab.html`).
3. Put a `http-equiv` redirect to `http://localhost` in the header:
```html
<!DOCTYPE html>
<head><title>New Tab</title>
<meta http-equiv="refresh" content="0; url=http://localhost/" />
</head><body></body></html>
```
4. Create a `manifest.json` in the same directory:
```json
{
  "name": "New Tab",
  "description": "Overrides the new tab page and redirects to localhost",
  "version": "0.1",
  "incognito": "split",
  "chrome_url_overrides": {
    "newtab": "newtab.html"
  },
  "manifest_version": 2
}
```
5. Open `chrome://extensions` and select the "Developer Mode" checkbox.
6. Select "Load unpacked extension..." and select the directory you created in Step 1.

At this point, you should have a basic working setup, even if you don't have a web server running locally: If you open a new tab, Chrome should attempt to refresh to `http://localhost`, where Vimium will work.  If you want to customize that page instead of seeing an error message, you could run a web server locally and host a page.

**Comment by LiamKearn** [comment]
Followed on from @craigforr's instructions and replaced the webserver with extensions enabled for files. [OSX Gist here](https://gist.github.com/LiamKearn/fa9381547a00dbb89ea70225b2e5040e)

Note all the redirection nonsense is needed, you can't inline <script> in manifest version 3 and you can't directly link to `file:///` in chrome without a call to a runtime API.
